= Collection 개요

* Collection은 요소로 구성된 개체를 말함
** 요소는 기본 유형이거나 개체에 대한 참조일 수 있음
* 배열은 요소를 메모리상에 연속적으로 저장함
** 개별 요소에 액세스하지 않고도 즉시 배열의 요소에 빠르게 액세스 할 수 있음
** 상대적 위치가 주어졌을 때 빠르게 액세스 할 수 있는 저장 구조
** 배열의 위치가 고정되고, 배열에 데이터를 추가하는 모든 동작에 대한 코드를 직접 작성해야 함
* Collection은 요소의 저장 방식을 추상화 함
** 요소의 추가, 삭제 등 요소에 액세스하는 모든 추상화 된 동작을 제공

---

*_Collection_* 은 익숙한 요소(Element)로 구성된 개체를 말합니다. 요소는 기본 데이터 타입(int 등) 이거나 참조 타입 객체일 수 있습니다. 익숙한 예로 배열은 같은 타입의, 메모리상에 연속하여 저장된 요소의 Collection 입니다. 아래와 같이 5개의 String 요소(String 개체에 대한 참조) 배열을 만들 수 있습니다.

[source, java]
----
String[] names = new String[5];
----

여기에서 new 연산자는 5개의 문자열 참조의 배열에 대한 공간을 할당하고 할당된 공간의 시작 부분에 대한 참조를 반환합니다. 이 참조는 names 변수에 저장됩니다.

배열의 연속적으로 저장된다는 것은 중요한 의미를 가집니다. 다른 개별 요소에 먼저 액세스 하지 않고도 즉시 배열의 요소에 액세스 할 수 있습니다. 배열의 임의 액세스 속성은 코드에서 상대적인 위치가 주어졌을 때 요소에 빠르게 액세스 할 수 있는 저장 구조가 필요할 때 유용하게 사용됩니다.

하지만 배열에는 몇 가지 단점이 있습니다. 요소가 배열에 저장되기 전에 전체 배열에 대한 공간이 할당되어야 합니다. 크기가 너무 작으면 더 큰 배열을 할당하고 더 작은 배열의 내용을 더 큰 배열로 할당해야 합니다. 또 배열에서의 동작을 위한 모든 코드를 작성해야 한다는 문제가 있습니다.

Collection은 요소의 저장 방식을 추상화합니다. Collection에 요소를 추가하고 삭제하는 등 내부의 모든 요소에 적용되는 방식을 미리 제공합니다.

link:./03_java_collections_framework.adoc[다음: Java Collections Framework]