= 포커 게임

포커는 플레잉 카드로 할 수 있는 대표적인 카드 게임 중 하나입니다. 플레이어들은 본인이 가진 카드의 조합을 확인하고 금액을 배팅한 후, 서로의 카드를 모두 공개하여 그 결과 가장 높은 조합을 가진 플레이어가 승자가 되어 배팅한 판돈을 모두 차지하는 게임입니다.

2~5 명의 플레이어가 5장씩의 카드를 받은 후, 서로의 카드를 모두 공개하고 순위를 결정하여 승자와 패자를 가리는 poker 게임을 작성하세요.

== 플레잉 카드

카드 게임에 널리 쓰이는 카드로, 트럼프 카드라고도 불립니다. 이 카드는 다이아몬드(♦), 스페이드 (♠), 하트( ♥), 클럽(♣) 등 네 가지 문양과 각각의 무늬를 가지는 1~13을 의미하는 A, 2, ~ 10, J, Q, K의 숫자를 가진 카드로 구성됩니다. 각각의 숫자 카드는 각각의 무늬를 가지며, 총 52장의 카드로 게임을 진행합니다.

플레잉 카드의 숫자 순위는 높은 순에서 낮은 순으로 다음과 같습니다.

A -> K -> Q -> J -> 10 -> 9 -> 8 -> 7 -> 6 -> 5 -> 4 -> 3 -> 2

무늬 순위는 높은 순에서 낮은 순으로 다음과 같습니다.

스페이드(♠) -> 다이아몬드(♦) -> 하트(♥) -> 클럽(♣)

가장 높은 카드는 스페이드 A(♠) 이며, 가장 낮은 카드는 2(♣) 가 됩니다.

== 순위

카드 조합의 순위는 아래와 같습니다.

1. 스트레이트 플러시(Straight Flush): 숫자가 이어지고 무늬가 같은 카드 5장 (0.00154%, 로열 포함한 수치)
2. 포 카드 - 포 오브 어 카인드(Four of a Kind): 숫자가 같은 카드 4장 (0.024%)
3. 풀 하우스(Full House): 쓰리 오브 어 카인드 + 페어 (0.1441%)
4. 플러시(Flush): 무늬가 같은 카드 5장 (0.1965%)
5. 스트레이트(Straight): 숫자가 이어지는 카드 5장 (0.3925%)
6. 트리플 - 쓰리 오브 어 카인드(Three of a Kind): 숫자가 같은 카드 3장 (2.1128%)
7. 투 페어(Two Pairs): 2쌍의 페어 (4.7539%)
8. 원 페어 / 투 오브 어 카인드(One Pair / Two of a Kind): 숫자가 같은 카드 2장 (42.2569%)
9. 하이 카드(High Card / No Pairs): 숫자가 높은 카드 1장 (아래 어떤 족보(조합)에도 해당되지 않을 때) (50.1177%)

== 프로그램의 동작

프로그램은 아래와 같은 방식으로 실행되어야 합니다.

1. 게임이 시작되면, 플레이어가 몇 명인지를 입력 받습니다.
2. 사용자의 이름을 입력 받습니다. 사용자 이외의 플레이어는 임의로 이름을 부여합니다.
3. 각 플레이어는 5장씩의 카드를 받습니다.
4. 받은 카드들의 순위를 결정한 후 각 플레이어의 순위(원 페어, 투 페어 등)와 가장 높은 순위를 가진 플레이어의 이름을 출력합니다.
5. 프로그램이 종료됩니다.

== 제출 방법

* main 메소드가 포함된 클래스를 public으로 선언하고 학번_Poker 로 작성한다.
* 프로그램 동작에 필요한 모든 소스파일을 학번_Poker.zip 으로 압축한다.
* 학번_Poker.zip 파일을 제출한다.