= 명세에 의한 추상화(Abstraction by Specification)

* 구현 세부사항에서 사용자가 의존할 수 있는 동작까지 Abstraction
* 의존하는 동작을 지원하는 구현에서 모듈을 분리
* 프로시저 본문에 의해 설명된 계산을 Abstraction
* 두 가지 고유한 규칙을 사용
** 프로시저를 실행한 후 호출이 수행될 때 사전 조건(Pre-condition)의 유지되면 사후 조건이 유지된다고 가정
** 프로시저 사용자가 프로시저를 사용하기 위해 프로시저 본문을 볼 필요가 없음
* 사후 조건(Post-condition)에서 추론할 수 있는 속성만 가정
* 관련성이 없는 것으로 추정되는 일부 정보를 생략한다는 것을 분명히 함

---

명세에 의한 추상화(Abstraction by Specification)을 통해 프로시저 본문에서 처리하는 계산을 Abstraction할 수 있습니다. 각 프로시저와, 프로시저의 결과로 의도된 효과의 사양을 연관시킨 다음 프로시저의 본문이 아닌 명세를 기반으로 하는 호출의 의미를 고려하여 수행합니다.

프로시저를 사용하는 측에서 본문을 보지 않고 해당 프로시저를 사용할 수 있도록 충분한 설명을 사용하여 명세에 의한 Abstraction을 수행할 수 있습니다.

[source, java]
----
float sqrt (float coef) {
	// REQUIRES: coef > 0
	// EFFECTS: coef의 제곱근에 대한 근사값을 반환
	float ans = coef/2.0
	int i = 1;
	while (i < 7) {
		ans = ans - ((ans * ans - coef)/(2.0 * ans));
	}
	return ans;
}
----

이는 계약에 의한 설계(Design by contract)에 의해 언급된 것으로, 해당 프로시저를 프로시저의 코드를 보지 않고도 사용할 수 있을 정도로 충분한 주석을 제공함으로서 명세에 의한 Abstraction을 수행하고 있습니다.

프로시저 호출의 의미에 대해 추론하기 위해 사양을 사용할 때 두 가지 고유한 규칙을 따릅니다.

1.	프로시저를 실행한 후 호출이 수행될 때 사전 조건(Pre-condition)이 유지되면 사후 조건(Post-condition)이 유지된다고 가정합니다.
2.	사후 조건에서 추론할 수 있는 속성만 가정할 수 있습니다.

두 가지 규칙은 명세에 의한 Abstraction의 두 가지 이점을 반영합니다. 첫 번째는 프로시저 사용자가 프로시저를 사용하기 위해 프로시저의 코드를 볼 필요가 없다는 것입니다. 두 번째 규칙은 실제로 프로시저 본문에서 관련이 없는 것으로 추정되는 일부 정보를 생략한다는 것을 분명히 합니다.

link:./05_abstraction_by_specification.adoc[이전: 명세에 의한 추상화] +
link:./06_kind_of_abstraction.adoc[다음: 추상화의 종류]