= Lab 15-3 : Circle-ellipse Problem

LSP를 위반하는 전형적인 예로, 너비와 높이를 조회하고 할당하는 메소드를 가진 Rectangle(직사각형) 클래스로부터 Square(정사각형) 클래스를 파생하는 경우를 들 수 있습니다. 정사각형 클래스는 항상 너비와 높이가 같습니다. Square 객체가 Rectangle을 다루는 컨텍스트에서 사용되는 경우, Square의 크기는 독립적으로 변경할 수 없기 때문에 예기치 못한 행동을 하게 됩니다. 이 문제에서 Square 클래스의 불변 조건을 유지하면, 이 메소드는 크기를 독립적으로 변경할 수 있다고 설명한 Rectangle의 setter의 사후 조건을 위반합니다.

이 연습에서는 Rectangle과 Square 객체의 상속 관계를 통해 LSP를 위반하는 설계를 알아봅니다.

== 직사각형을 구현하는 Rectangle 클래스 선언

1. Visual Studio Code를 실행합니다.
2. 파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab15-3\Starter 폴더를 엽니다.
3. 작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4. Rectangle.java 파일을 열고 코드를 확인합니다.
5. Rectangle 클래스는 직사각형을 구현한 객체입니다. 너비와 높이를 지정할 수 있으며, 지정된 값을 통해 넓이를 계산할 수 있습니다.
6. Rectangle 클래스는 직사각형의 너비와 높이를 표시하는 `width`, `height` 두 개의 int 타입 필드를 가지고 있습니다. Rectangle 클래스의 두 필드의 getter와 setter 메소드를 작성하고 넓이를 int 타입으로 반환하는 getArea 메소드를 작성합니다.
7. 완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public class Rectangle {
    protected int width;
    protected int height;

    public int getWidth() {
        return this.width;
    }

    public int getHeight() {
        return this.height;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getArea() {
        return this.width * this.height;
    }
}
----
+
8. Visual Studio Code에서 Test.java 파일을 엽니다.
9. Test.,java 파일의 main 메소드에서, Rectangle 클래스의 인스턴스를 생성하고 높이 10, 너비 5을 할당하고 넓이를 출력하는 테스트 코드를 작성합니다.
10.	완성된 코드는 아래와 같을 것입니다.
+
[source, java]
----
public class Test {
    public static void main(String[] args) {
        Rectangle rectangle = new Rectangle();
        rectangle.setWidth(10);
        rectangle.setHeight(5);

        System.out.println(rectangle.getArea());
    }
}
----
+
11.	작업을 저장합니다.
12.	아래 명령을 수행하여 프로그램을 컴파일합니다.
+
----
$ javac Rectangle.java Test.java
----
+
13.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java Test
50
----

== Rectangle 클래스에서 파생된 Square 클래스 생성

정사각형은 너비와 높이 같은 직사각형의 한 종류입니다. Rectangle을 상속하면 Square를 빠르게 만들 수 있을 것이라 가정합니다.

[source, mermaid]
----
classDiagram
    Rectangle <|-- Square
    class Rectangle {
        +setwidth()
        +setHeight()
    }
    class Square {

    }
----

1. Visual Studio Code 탐색기에서 Square.java 파일을 엽니다.
2. 정사각형은 높이와 너비가 같은 사각형입니다. 따라서, 너비 또는 높이 입력되는 값은 모두 동일하게 `width` 와 `height` 필드에 할당되어야 합니다.
3. 높이와 너비에 같은 값이 할당되도록 `setWidth` 메소드를 오버라이드 합니다.
4. 완성된 코드는 유사할 것입니다.
+
[source, java]
----
public void setWidth(int width) {
    super.setWidth(width);
    super.setHeight(width);
}
----
+
5. 높이와 너비에 같은 값이 할당되도록 setHeight 메소드를 오버라이드 합니다.
6. 완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public void setHeight(int height) {
    super.setHeight(height);
    super.setWidth(height);
}
----
+
7. 작업을 저장합니다.
8. 아래 명령을 수행하여 프로그램을 컴파일합니다.
+
----
$ javac Square.java
----

=== 테스트

리스코프 치환 원칙에 따르면, 파생된 객체는 기본 객체를 완전히 대체할 수 있어야 합니다. 객체를 사용하는 클라이언트 입장에서, 아래와 같이 테스트하는 코드를 작성합니다.

1. Visual Studio Code 탐색기에서 Test.java 파일을 엽니다.
2. main 메소드에서 Rectangle 타입의 객체 Square를 생성하고, 너비와 높이에 각각 10과 5를 입력하고 넓이를 출력하는 코드를 작성합니다.
3. 완성된 테스트 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public class Test {
    public static void main(String[] args) {
        Rectangle rectangle = new Square();
        rectangle.setWidth(10);
        rectangle.setHeight(5);

        System.out.println(rectangle.getArea());
    }
}
----
+
4. 작업을 저장합니다.
5. 아래 명령을 수행하여 프로그램을 컴파일 합니다.
+
----
$ javac Test.java
----
+
6. 아래 명령을 수행하여 응용 프로그램을 실행합니다.
+
[source, java]
----
$ java Test
50
----

리스코프 치환 원칙은 “타입 S가 타입 T의 서브타입이라면 프로그램의 속성 변경없이 T 타입의 객체를 S 타입으로 치환할 수 있어야 한다”라고 정의합니다. 따라서 Rectangle이 Square 타입인지에 상관없이 기대하는 값(50)을 출력해야 하지만 Rectangle은 Square 객체이므로 25을 출력합니다. 이는 리스코프 치환 원칙을 위반합니다.

link:./15_lsp.adoc[이전: 리스코프 치환 원칙] +
link:./17_lab15-4.adoc[다음: Solve Circle-ellipse Problem]