= 디렉토리와 폴더


* 현대 컴퓨터에서 파일을 분류하기 위해 사용되는 이름공간(namespace)
* 디렉토리는 전화번호부와 유사한 성격을 가진 파일의 한 형태
** 실제 데이터가 담겨 있는 것이 아닌 파일의 구조화된 속성 정보를 담아 하위 디렉토리 또는 파일과 연계해주는 특수한 형태의 파일
** 데이터를 저장하는 것이 아닌 하위 디렉토리와 파일들의 포인터 정보
** 많은 운영체제는 디렉토리 계층 구조를 통해 시스템을 체계화 함
* 폴더는 일종의 가상 분류로, 일반 폴더와 가상 폴더가 존재
** 디렉토리는 절대 경로 중심의 수직적 구조에 가까우나, 폴더는 Shell 네임 스페이스의 개체를 포함한 수평적 구조

---

디렉터리를 지원하는 운영체제에서는 파일을 관리하기 위해 디렉토리 또는 폴더를 사용할 수 있습니다. 파일은 실제 데이터를 담고 있는 개발 문서를 의미하며, 디렉토리는 파일을 분류해 놓은 파일을 담을 수 있는 공간으로 생각할 수 있습니다.

디렉토리(Directory)는 사전적으로 ‘이름이나 주소등의 관련 정보를 알파벳순으로 나열한 안내 책자’의 의미를 가집니다. 디렉토리는 그 의미에서 보듯이 관련 정보를 나열할 수 있는 묶음의 의미를 가집니다. 디렉토리에 실제 데이터를 포함하는 파일 포함되어 있는 것이 아니라 하위 디렉토리(Sub Directory)나 파일의 구조화된 속성 정보를 담아 파일을 연결해주는 특수한 형태의 파일입니다. 디렉토리를 파일과 구분하지만 디렉토리 역시 파일의 일종입니다.

폴더는 디렉토리에서 확장된, 일종의 가상 분류 개념입니다. Windows 운영체제에는 디렉토리와 동일한 역할을 하는 일반 폴더와 달리 제어판, 네트워크 환경, 장치 등의 다른 유형의 특수한 형태의 폴더가 존재합니다. 이는 운영체제가 개별 항목들의 절대 경로를 알 필요 없이 같은 의미를 가지는 개체들을 개념별로 한 군데 모아 관리할 수 있는 형태로 제공하는 것으로, 이런 유형의 개체들을 폴더라는 이름으로 관리합니다. 

폴더는 특수 형태의 가상 폴더와 일반 폴더로 구성됩니다. 디렉토리가 절대 경로 중심의 수직적 구조라면, 폴더는 파일이나 서브 디렉토리를 뿐만 아니라 파일에 해당하지 않는 Shell 네임 스페이스의 개체를 포함한 가상 분류 중심의 수평적 구조라고 볼 수 있습니다.

link:./04_유닉스_디렉토리.adoc[다음: 유닉스 디렉토리]