= 프로세스 스케줄링

* 컴퓨터의 CPU는 한정되어 있고, 대부분의 프로세스는 CPU 보다 많다
* 멀티 프로세싱과 시분할
** 멀티 프로세싱의 목적은 CPU 이용을 최대화하기 위해 항상 어떤 프로세스가 실행하도록 하는 것
** 시분할의 목적은 각 프로그램이 실행되는 동안 사용자가 상호작용할 수 있도록 프로세스들 사이에서 CPU 코어를 빈번하게 교체하는 것
* 프로세스 스케줄러
** 코어에서 실행가능한 여러 프로세스 중 하나의 프로세스를 선택
* 프로세스 스케줄링
** CPU 할당 순서 및 방법을 결정하는 일종의 계획
** 일정한 기준인 알고리즘을 통해 결정

---

멀티 프로세싱의 목적은 CPU 이용을 최대화하기 위해 항상 어떤 프로세스가 실행되도록 하는데 있습니다. 시분할의 목적은 각 프로그램이 실행되는 동안 사용자가 상호작용할 수 있도록 프로세스들 사이에서 CPU 코어를 빈번하게 교체하는 것입니다.

이 목적을 위해 프로세스 스케줄러는 코어에서 실행 가능한 여러 프로세스 중에서 하나의 프로세스를 선택합니다. 각 CPU 코어는 한 번에 하나의 프로세스를 실행할 수 있습니다. 단일 CPU 코어 시스템의 경우 한 번에 하나의 프로세스만을 실행할 수 있고, 멀티 CPU 코어 시스템의 경우 한번에 코어만큼의 프로세스를 실행할 수 있습니다. 

대부분의 경우 실행되는 프로세스의 수는 시스템의 CPU 코어 수보다 많습니다. 따라서 초과 프로세스는 프로세스가 사용 가능해지고 다시 스케줄 될 때까지 메모리에서 대기해야 합니다.

현대의 운영체제는 시분할 방식을 사용한 멀티 프로세싱 환경에서 동작합니다. 운영체제는 어떤 프로세스를 선택해서 CPU에서 실행을 하고 어떤 방식으로 원활하게 교체하는지가 중요합니다. 이런 프로세스 운영방식을 스케줄링(Scheduling) 이라고 합니다.

운영체제는 프로세스의 스케줄링을 위해 스케줄러를 두고, 스케줄러는 프로세스 중 어떤 프로세스를 CPU에 할당할지 선택합니다. 

== 스케줄링 방식

Non-preemptive (비선점형) + 
프로세스가 스스로 다음 프로세스에게 자리를 넘겨주는 방식

Preemptive (선점형)
운영체제가 강제로 프로세스의 사용권을 통제하는 방식

== 선점 스케줄링 알고리즘

* Round Robin +
각 프로세스가 동일한 크기의 할당 시간을 갖고 할당 시간이 끝나면 자동으로 선점(Preemptive)당하고, Ready Queue의 제일 뒤로 할당됩니다. n 개의 프로세스가 Ready Queue에 존재하고 할당 시간이 q라면 어떤 프로세스도 (n – 1)q 이상 기다리지 않으므로 기아 현상이 발생하지 않습니다.
* SRT(Shortest Remaining Time) +
SJF의 선점형 구현입니다.
* 다단계 큐(Multilevel Queue) +
정적 우선순위를 사용하는 스케줄링 방식으로, 다단계 큐를 자료구조로 사용합니다. 같은 우선 순위 값을 가지는 프로세스들을 위해 큐가 필요하고, 다른 우선순위의 프로세스들을 구별하고 관리하기 위해 우선 순위의 개수만큼 큐가 필요합니다. 프로세스들은 자신의 우선순위 값에 해당하는 큐에 들어가게 되며, 우선순위가 낮은 하위 단계 큐의 작업은 실행 중이더라도 상위 단계 큐에 프로세스가 도착하면 CPU를 뺏기게 됩니다.
* 다단계 피드백 큐 (Multilevel Feedback Queue) +
짧은 프로세스에게 유리하도록 할 수 있으며, 입출력 프로세스를 우대함으로써 CPU를 포함한 전체 자원들의 활용도를 높여 시스템의 성능을 높일 수 있는 스케줄링 방식입니다. 동적 우선 순위를 기반으로 하며, 우선 순위 개수 만큼의 큐가 있으며 각 단계마다 다른 CPU 시간 할당량을 가집니다.

== 비선점 스케줄링 알고리즘

* FCFS(First Come First Serve) +
CPU에 먼저 도착하는 순서대로 프로세스를 할당하는 방식으로, 각 작업이 종료될 때 까지 CPU를 빼앗지 않으므로 Non-preemptive 방식이며, FIFO 방식의 Queue와 동일하게 동작합니다. 
* SJF(Short Job First) +
프로세스의 수행 시간이 짧은 순서대로 프로세스를 할당하는 방식으로, 항상 주어진 프로세스에 대해 최소의 평균 대기 시간을 보장합니다. 수행 시간이 긴 프로세스는 계속 뒤로 밀려는 기아(Starvation) 현상이 발생할 수 있으며, 각 프로세스가 얼마나 CPU를 사용할지 모르는 경우 사용하기 어렵습니다.
* Priority Processing +
특정 기준으로 프로세스에게 우선 순위를 부여해 우선순위가 제일 높은 프로세스에게 CPU를 할당하는 방식의 스케줄링입니다. 우선순위가 낮은 프로세스는 기아 현상이 발생할 수 있는데, 오래 대기한 프로세스의 우선 순위를 높이는 에이징 방식으로 해결합니다. 
* HRN(Highest Response-ratio Next) +
SJF의 단점을 보완하는 알고리즘이며, 우선 순위 계산식을 사용하여 자원을 할당합니다.

link:./19_Thread.adoc[다음: Thread]