= Thread 개요

* 하나의 응용 프로그램이 여러 작업들을 동시에 수행해야 하는 경우가 많음
* 워드 프로세스의 경우 맞춤법 검사와 입력이 동시에 일어나야 함
* 웹 서버는 많은 클라이언트로부터 동시에 페이지 요청을 받음
* 프로세스 생성은 많은 시간/자원을 필요로 하며, 동일한 프로세스를 여러 개 만들 필요가 없음
* 프로세스안에 Thread를 만들어 나가는 것이 효율적임

---

프로세스를 보는 한 관점은 자원을 그룹화하는 것입니다. 프로세스는 프로그램 텍스트, 데이터와 기타 다른 자원을 포함하는 주소 공간을 가지고 있습니다. 이들 자원은 오픈 파일, 자식 프로세스, 정의되지 않은 알람, 시그널 처리가, 계정 정보 등입니다. 프로세스 형식으로 이들 자원을 다루면 관리가 쉬워집니다.

프로세스가 갖는 다른 개념은 보통 Thread라 부르는 Thread 실행입니다. Thread는 다음에 수행할 명령을 유지하기 위하여 프로그램 카운터를 갖고 있습니다. 이외에 호출되었지만 아직 반환되지 않고 있는 변수를 유지하는 레지스터도 갖고 있습니다. 이외에 호출되었지만 아직 반환되지 않고 있는 프로시저에 대한 실행 정보를 갖고 있는 스택도 있습니다. Thread는 프로세사 내에서 동작하지만 Thread와 프로세스는 다른 개념이며 분리하여 취급해야 합니다. 프로세스는 자원을 그룹화하는데 사용되지만 Thread는 CPU 실행을 위하여 이미 스케줄링된 상태의 엔티티입니다.

Thread는 동일 프로세스 환경에서 서로 독립적으로 다중 수행이 가능합니다. 한 프로세스 내에서 병렬로 동작하는 다중 Thread를 갖는다는 것은 한 컴퓨터에서 병렬로 수행되는 다중 프로세스를 갖는것에 유추됩니다. 전자의 경우 Thread가 주소 공간, 오픈 파일, 기타 자원을 공유하는데 반하여 후자의 경우 프로세스는 실제 메모리, 디스크, 프린터와 기타 자원을 공유합니다. Thread는 프로세스의 일부 특성을 갖고 있기 때문에 경량 프로세스라고 부르기도 합니다. 멀티 스레딩이라는 용어 역시 동일 프로세스 내에서 다중 Thread를 허용하는 상황에서 사용됩니다.

link:./21_프로세스와_Thread.adoc[다음: 프로세스와 Thread]