= 증가/감소 연산

* 값을 1씩 증가시키거나 감소시키는 연산은 매우 자주 사용됨
+
[source, java]
----
customerCount += 1;
customerCount -= 1;
----
+
* 다음과 같이 단항 연산자를 사용하여 줄여 쓸 수 있음
+
[source, java]
----
// 선행 표기
customerCount++;
customerCount++;

// 후행 표기
++customerCount;
--customerCount;
----

---

*1씩 증가되거나 감소하는 연산은 매우 일반적으로 사용됩니다*

아래와 같이 작성되는 변수의 값을 1씩 증가시키거나 감소시키는 구문은 매우 자주 사용됩니다.

[source, java]
----
customerCount = customerCount + 1;
customerCount = customerCount – 1;
----

합성 할당 연산을 사용하여 아래와 같이 단축된 형식으로 짧게 쓸 수 있습니다.

[source, java]
----
customerCount += 1;
customerCount -= 1;
----

*1씩 증가/감소를 위해 단항 연산자 사용*

값이 1씩 증가하는 일반적인 연산을 위해, 단항 연산자를 사용하여 아래와 같이 줄여 쓸 수 있습니다.

[source, java]
----
customerCount++;
customerCount--;
----

++ 연산자는 증가 연산자(increment operator)라고 부르며 -- 연산자는 감소 연산자(decrement operator)라고 부릅니다. 증가 연산자와 감소 연산자를 변수의 앞에 사용하느냐 또는 뒤에 사용하느냐에 따라 동작이 다습니다. 변수의 뒤에 증가 dustsk자 또는 감소 연산자를 쓰면 값을 후행으로 변경하고, 앞에 쓰면 선행으로 변경합니다.

*두 가지 사용 용법*

++ 연산자와 -- 연산자는 두 가지 용법으로 사용할 수 있습니다.

1.	연산자를 변수 앞에 표시합니다. 이를 선행 표기법(prefix notation)이라고 부릅니다.
+
[source, java]
----
++customerCOunt;
--customerCount;
----
+
2.	연산자를 변수 뒤에 표시합니다. 이를 후행 표기법(postfix notation)이라고 부릅니다.
+
[source, java]
----
customerCount++;
customerCount--;
----

두 경우 모두 customerCount는 1씩 증가(++) 또는 감소(--) 됩니다.

Java의 중요한 기능 중 반드시 이해해야 하는 것 중 하나는 할당이 연산자라는 것입니다. 이는 변수에 값을 할당하는 것 이외에도 할당이 발생한 후 결과(값)이 있음을 의미합니다.

[source, java]
----
int customerCount = 0;
System.out.println(customerCount = 2);	// 2를 출력
System.out.println(customerCOunt = customerCount + 20);	// 22를 출력
----

복합 할당 연산자도 역시 할당 연산을 수행해야 합니다. 이는 변수에 값을 할당하는 것 이외에도 결과가 있음을 의미합니다.

[source, java]
----
int customerCount = 0;
system.out.println(customerCOunt += 2);	// 2를 출력
System.out.println(customerCount -= 2);	// 0을 출력
----

증가/감소 연산 역시 할당 연산입니다. 이는 증분식이 변수를 1씩 증가시킨다는 것 외에 결과 자체도 값을 갖는다는 것을 의미합니다.

[source, java]
----
int customerCount = 22;
int prefixValue = ++customerCount;	// prefixValue의 값은 23
int postfixValue = customerCount++;	// postfixValue의 값은 23
----

증분식의 값은 선행 표기 또는 후행 표기를 사용하는지에 따라 다릅니다. 두 경우 모두 변수의 값이 증가하지만 증분식의 값이 무엇인지가 중요합니다. 선행 표기를 사용한 표현식의 값은 증가/감소가 발생한 후의 값이고, 후행 표기를 사용한 식의 값은 증가/감소가 발생하기 전의 값입니다.

[source, java]
----
int customerCount = 22;
System.out.println(++customerCount);	// 23을 출력
System.out.println(customerCount++);	// 23을 출력
System.out.println(customerCount);	// 24를 출력
----

link:./13_operator.adoc[이전: 일반 연산자] +
link:./15_priority.adoc[다음: 연산자 우선 순위]