= 지역 변수

* 지역 변수(Local Variable)
** 메소드가 시작할 때 생성됨
** 메소드 내에서만 유효함
** 메소드가 종료될 때 제거됨
* 공유 변수
** 클래스 수준에서 선언된 변수는 공유될 수 있음
* 범위 충돌
** 로컬 변수 이름과 클래스 이름이 같은 경우 컴파일러는 이를 경고하지 않음

---

각 메소드에는 고유한 지역 변수가 있습니다. 지역 변수는 선언된 메소드 내에서만 사용할 수 있으며, 메소드 밖 다른 곳에서 접근할 수 있습니다.

== 지역 변수

메소드 내에서 변수를 선언할 수 있으며, 이를 지역 변수(Local Variable)라고 합니다. 아래와 같이 선언할 수 있습니다.

[source, java]
----
static void myMethod() {
   int i = 1;    // 변수를 선언하면서 초기화
   long l;
   …
}
----

위의 예제 에서처럼 지역 변수를 선언하면서 값을 할당할 수 있습니다. 값을 할당하지 않거나 값을 결정하는 식을 사용하지 않으면 변수가 초기화되지 않습니다.

한 메소드에서 선언된 변수는 다른 메소드의 변수와 값이 같더라도 완전히 다릅니다. 지역 변수가 저장되는 메모리 공간은 메소드가 호출될 때마다 할당되고 메소드가 종료되면 해제됩니다. 따라서 변수에 저장된 값은 메소드 호출이 종료되면 완전히 사라지며 다음 메소드 호출 등에서 유지되지 않습니다.

== 전역 변수(클래스 내 공유 변수)

아래의 코드는 myMethod 메소드가 몇 번 호출되었는지를 알기 위해 작성된 코드입니다.

[source, java]
----
public class MethodCall {
    static void createCountVariable() {
        int count = 0;
    }

    static void myMethod() {
        int count = 0;
        ++count;
        System.out.printf("메소드가 %d 번 호출되었습니다.", count);
    }

    public static void main(String[] args) {
        createCountVariable();
        myMethod();
        myMethod();
    }
}
----

코드는 컴파일되지 않습니다. `myMethod` 에서 `count` 변수의 값이 초기화되지 않았기 때문입니다. 이는 `createCountVariable` 메소드에 선언된 `count` 변수와 `myMethod` 메소드에 선언된 `count` 변수가 완전히 다름을 의미합니다. `myMethod` 메소드가 종료될 때 지역 변수 `count` 는 없어집니다. 몇 번 호출하는지에 성관없이 `count` 변수는 생성되고 소멸됨을 반복합니다.

코드를 원하는대로 동작하게 만들려면, 클래스 변수를 사용하여 메소드가 같은 변수를 공유하게 해야 합니다.

[source, java]
----
public class MethodCall {
    static int count = 0;

    static void myMethod() {
        ++count;
        System.out.printf("메소드가 %d 번 호출되었습니다.\n", count);
    }

    public static void main(String[] args) {
        myMethod();
        myMethod();
    }
}
----

위 코드에서 `count` 변수는 클래스 레벨에서 선언되어 전역 변수라고 불리며, 모든 메소드에서 공유됩니다.

== 범위 충돌

Java에서는 클래스 변수와 이름이 같은 지역 변수를 선언할 수 있습니다. 같은 코드를 작성할 수 있지만 아래 코드에서 `method2` 가 참조하는 `count` 변수는 `method1` 의 지역 변수가 아닌 클래스 레벨에서 공유된 공유 변수임에 주의해야 합니다.

[source, java]
----
public class Scope {
    static int count = 0;

    static void method1() {
        int count = 50;
    }

    public void method2() {
        count = 90;
    }
}
----

link:./05_return_statement.adoc[이전: return statement] +
link:./07_value_return.adoc[다음: 값 return]