= return statement

* return에는 두 가지 뜻이 있음. "귀환" 과 "반환"
* return문을 만나면 메소드는 실행을 멈추고 즉시 호출자 코드로 돌아감
* return문을 만나면 메소드는 즉시 종료되고, 뒤의 코드는 실행되지 않음
* 조건문에서 return 할 수 있음

[source, java]
----
static void myMethod() {
    int number;
    // ...
    System.out.println(“Hello”);
    if (number < 10)
        return;
    System.out.println(“World!”);
}
----

---

`return` 문을 사용하여 메소드가 호출자에게 즉시 돌아가도록 할 수 있습니다. 메소드에 return문이 없으면 일반적으로 실행이 메소드의 마지막에 도달하면 호출자로 돌아갑니다.

== return

기본적으로, 메소드는 코드 블록의 마지막에 도달하면 호출자에게 돌아갑니다. 메소드가 호출자에게 즉시 돌아가도록 하려면 return문을 사용합니다.

아래의 코드는 Hello를 화면에 출력한 후 호출자에게 돌아갑니다. 아래 코드에서 World를 출력하는 코드는 실행되지 않습니다. 이 코드는 unreachable statement 오류를 발생시킵니다.

[source, java]
----
static void example() {
    System.out.println(“Hello”);
    return
    System.out.println(“World!”);
}
----

== 조건문에서 return

`if` 또는 `switch` 문 등의 조건문에서 `return` 을 사용하는 것이 일반적이고 유용합니다. 조건문에서 `return` 문을 사용하면 주어진 조건에 따라 메소드가 호출자에게 돌아가도록 할 수 있으며, 주어진 조건에 따라 다른 값을 호출자에게 반환할 수 있습니다. 조건절에서 `return` 하면 컴파일러는 오류를 발생시키지 않습니다.

아래 코드는 변수의 값이 10보다 작을 경우 즉시 `return` 하며, 그렇지 않을 경우 World!를 출력합니다.

[source, java]
----
static void method1() {
    int i = 10;
    System.out.println("Hello");
    if (i < 10)
        return;
    System.out.println("World!");
}
----

== 값 반환

메소드가 `void` 가 아닌 다른 타입으로 정의된 경우 반환 메커니즘을 사용하여 호출자에게 값을 반환합니다.

link:./04_method_invocation[이전: 메소드 호출] +
link:./06_local_variable.adoc[다음: 지역 변수]