= 값 return

* void가 아닌 타입으로 메소드 선언
* return 문을 사용하여 식을 return
** return할 값을 설정
** 메소드 호출자에게 값을 return
* void가 아닌 메소드는 반드시 값을 return해야 함

[source, java]
----
static int onePlueTwo() {
    int a, b;
    a = 1;
    b = 2;
    return a + b;
}

int i;
i = onePlusTwo();
System.out.println(i);
----

---

메소드에서 `return` 문을 사용하면 메소드가 즉시 종료됩니다. 메소드 호출자에게 메소드 실행의 결과로 계산된 값을 리턴하기 위해서도 역시 `return` 문을 사용합니다. 값을 리턴하려면 아래 규칙을 따라야 합니다.

1.	리턴하려는 값 유형(return type)으로 메소드를 선언합니다.
2.	메소드 블록에 return문을 추가합니다.
3.	호출자에게 반환할 값을 메소드에 추가합니다.

== void가 아닌 타입으로 메소드 선언

호출자에게 값을 반환하는 메소드를 선언하려면 메소드의 void를 반환하려면 값의 타입으로 변경합니다.

== return문 추가
식과 함께 작성된 return문은 즉시 메소드를 종료하고 식을 메소드의 반환값으로 변환합니다. 아래 코드는 `onePlusTwo` 메소드를 호출하는 호출자에게 3을 반환합니다.

[source, java]
----
public class Scope {
    static int onePlusTwo() {
        int a, b;
        a = 1;
        b = 2;
        return a + b;
    }

    public static void main(String[] args) {
        int i;
        i = onePlusTwo();
        System.out.println(i);
    }
}
----

`onePLusTwo` 메소드가 반환하는 값은 int 타입이며, 메소드가 호출되면 `return` 문 뒤에 선언된 식에 따라 3이 반환됩니다. 값은 `main` 메소드의 지역 변수에 반환됩니다.

== void가 아닌 메소드는 반드시 값을 반환해야 함

`void` 가 아닌 형식으로 메소드를 선언하는 경우 반드시 return문을 선언하고 값을 반환해야 합니다. 컴파일러는 void가 아닌 모든 메소드가 값을 반환하는지 확인해야 합니다. 컴파일러는 void가 아닌 메소드가 값을 반환하지 않는 것을 감지하면 오류를 표시합니다.

link:./06_local_variable[이전: 지역 변수] +
link:./08_parameter.adoc[다음: 파라미터]
