= 메소드 오버로딩 정의

* 클래스 내에서 같은 이름을 사용하는 메소드
* 파라미터의 개수와 타입을 검사하여 구분
* Java에서 다형성을 표현하는 한 가지 방법

[source, java]
----
static int add(int i, int j) {
    return i + j;
}

static int add(int i, int j, int k) {
    return i + j + k;
}

public static void main(String[] args) {
    int i = Add(1, 2);
    int j = Add(1, 2, 3);
    System.out.println(i + j);
}
----

---

오버로드 된 메소드는 동일한 이름을 가진 단일 클래스의 메소드입니다. 컴파일러는 파라미터 목록을 비교하여 오버로드 된 메소드를 구분합니다.

== 오버로드 메소드 예제

다음 코드는 같은 클래스 내에서 다른 타입과 개수의 파라미터를 가진 같은 이름의 메소드를 정의하는 것을 보여줍니다.

[soruce, java]
----
public class OverLoading {
    static int add(int i, int j) {
        return i;
    }

    static int add(int i, int j, int k) {
        return i + j + k;
    }

    public static void main(String[] args) {
        int i = add(1, 2);
        int j = add(1, 2, 3);
        System.out.println(i + j);
    }
}
----

컴파일러는 클래스에서 `add` 라는 두 개의 메소드를 찾고 `main` 메소드에서 `add` 메소드에 대한 두 호출을 찾습니다. 컴파일러는 같은 이름의 메소드 호출에서 메소드를 호출할 때 사용하는 파라미터의 개수와 타입을 비교하여 두 add 메소드를 구별하여 호출합니다.

첫 번째 `add` 메소드는 int 타입 파라미터를 두 개 사용합니다. 두 번째 `add` 메소드는 int 형식의 파라미터를 2개 사용합니다. Java는 파라미터의 목록(개수, 타입)이 다른 같은 이름의 메소드를 정의할 수 있도록 하고, 파라미터의 목록이 다르기 때문에 컴파일러는 같은 클래스에서 두 메소드를 구분할 수 있습니다.

`main` 메소드의 첫 번째 문에는 두 개의 int 타입 파라미터를 가진 add 메소드를 호출합니다. 컴파일러는 이를 첫 번째 `add` 메소드에 대한 호출로 변환합니다. `add` 에 대한 두 번째 호출은 세 개의 int 타입 파라미터를 사용하고, 컴파일러는 이를 두 번째 `add` 메소드에 대한 호출로 변환합니다.

메소드 오버로딩은 파라미터에만 적용되고, return 타입에는 적용되지 않습니다. 아래 코드는 두 메소드가 return 타입은 다르지만 파라미터의 타입과 개수가 같기 때문에 컴파일시 오류를 출력합니다.

[source, java]
----
public class OverLoading {
    static int add(int i, int j) {
        return i + j;
    }

    static long add(int i, int j) {
        return i + j + k;
    }
}
----

아래 예제는 int는 long으로 암시적 형 변환이 허용되므로 메소드 오버로딩이 허용됩니다.

[source, java]
----
public class OverLoading {
    static int add(int i, int j) {
        return i + j;
    }

    static long add(int i, int j, int k) {
        return i + j + k;
    }

    public static void main(String[] args) {
        …
    }
}
----

link:./14_method_overloading.adoc[이전: 메소드 오버로딩] +
link:./16_method_signature.adoc[다음: 메소드 시그너처]