= foreach statement (foreach 문)

* 반복되는 변수의 타입과 이름을 선택
* Collection 클래스의 각 요소에 대해 포함된 구문 실행

[source, java]
----
ArrayList<Integer> numbers = new ArrayList<Integer>();
for (int i = 0; i < 10; i++) {
    System.out.println(i);
}

for (int i: numbers) {
    System.out.println(i);
}
----

---

컬렉션은 객체를 저장하고 동일한 방법으로 순환, 반복, 삽입, 삭제하는 것을 목적으로 만들어진 개체입니다. 

Java 라이브러리는 `ArrayList` 라고 불리는 단순한 컬렉션을 저장합니다. `ArrayList` 를 사용하여 변수 집합을 생성하고 집합에 요소를 추가할 수 있습니다. 다음과 같이 정수형 집합을 포함하는 `ArrayList` 를 생성하고 요소를 추가할 수 있습니다.

[source, java]
----
ArrayList<Integer> numbers = new ArrayList<Integer>();
for (int i = 0; i < 10; i++) {
    numbers.add(i);
}
----

이 컬렉션의 각 요소에 차례로 액세스하고 출력하는 코드를 for 문을 사용하여 작성하면 아래와 같이 됩니다.

[source, java]
----
for (int i = 0; i < numbers.size(); i++) {
    System.out.println(i);
}
----

이 `for` 문에는 컬렉션에 포함된 각 정수 요소를 반복하는데 사용되는 메커니즘을 조합하여 구현하는 많은 문들이 포함되어 있습니다. 많이 사용되지만 같은 방식의 반복에 대해 많은 코드를 작성해야 합니다.

이 문제를 해결하기 위해 Java는 여러 문을 사용하지 않고 컬렉션을 반복할 수 있는 `foreach` 문을 8 버전에 추가했습니다. 특정 컬렉션에 특정한 구문을 사용하여 컬렉션에서 요소를 추출하는 대신 `foreach`` 문을 사용하여 보다 효과적으로 요소를 추출할 수 있습니다.

`foreach` 문을 사용하여 위의 `for`` 문을 아래와 같이 고쳐 쓸 수 있습니다.

[source, java]
----
for (int i : numbers)
    System.out.println(i);
----

`foreach` 문은 컬렉션 내의 각 요소에 대해 포함된 문을 실행합니다. 이를 위해서는 반복을 수행할 변수의 유형과 컬렉션의 이름만 필요할 뿐, 다른 구성요소들을 필요하지 않습니다. 위의 코드에서는 `int` 와 `number` 입니다.

> **정보**  foreach 문은 Iterable 인터페이스의 forEach 메소드를 사용하여 컬렉션에서 요소를 반복합니다.

`foreach` 문을 사용할 때는 반복할 변수의 유형을 결정하는 것이 중요합니다. 반복할 변수의 유형을 잘못 선택하면 런타임 오류가 발생할 수 있습니다.

== 예제

아래 예제는 foreach 문을 사용하여 정수형 배열의 모든 요소의 값을 출력합니다.

[source, java]
----
int[] array = {3, 4, 5, 2, 3, 4, 6};
for(int i: array) {
    System.out.print(i + “ “);
}
----

아래 예제는 foreach 문을 사용하여 구구단을 출력합니다.

[source, java]
----
int[] tableNumber = {2, 3, 4, 5, 6, 7, 8, 9};
int[] digits = {2, 3, 4, 5, 6, 7, 8, 9};

for (int i : tableNumber) {
    for (int j: digits) {
        System.out.println(i + " * " + j + " = " + i * j);
    }
}
----

link:./12_for.adoc[이전: for statement (for 문)] +
link:./14_jump_statement.adoc[다음: Jump Statement (분기 문)]