= for statement (for 문)

* 반복의 시작 부분에 반복 종료를 위한 업데이트를 명시

[source, java]
----
for (int i = 0; i < 10; i++) {
    System.out.println(i);
}
----

* for 블록 변수의 범위는 블록 내로 한정됨

[source, java]
----
for (int i = 0; i < 10; i++) 
    System.out.println(i);
System.out.println(i);    // i는 for 범위를 벗어남
----

* for 반복은 여러 개의 값을 반복에 사용할 수 있음

[source, java]
----
for (int i = 0, j = 0; ...; i++, j++) {
    …
}
----

---

`for` 문은 `while` 문에서 종종 발생하는 개발자의 실수를 방지하고 보다 명확한 시작 조건과 종료 조건을 명시할 수 있는 반복문입니다.

`while` 문에서, 개발자는 가끔 반복문 종료를 위한 변수를 업데이트하는 것을 잊어버립니다. 아래 코드는 종종 실수로 작성되는 코드입니다.

[source, java]
----
int i= 0;
while (i< 10) {
    System.out.println(i);	// 무한 루프: 업데이트 조건(i++)이 없음
}
----

이런 실수는 개발자가 반복문을 작성할 때 반복 상태 업데이트보다 `while` 문의 코드에 더 집중하기 때문입니다. 또한, `while` 문에서는 키워드와 업데이트 코드가 떨어져 있어 실수를 유발하기 쉽습니다.

`for` 문을 사용하면 이런 에러를 최소화할 수 있습니다. `for` 문은 업데이트 코드가 반복의 시작 부분에 위치하여 업데이트 누락 문제가 발생하지 않도록 합니다. `for` 문의 구문은 다음과 같습니다.

----
for (초기자; 종료 조건; 조건 업데이트) 
    embedded-statement
----

== 예제

`for` 문의 초기자, 종료 조건 및 조건 업데이트 구성요소는 선택적으로 삽입될 수 있습니다. 빈 조건은 암시적으로 `true` 로 간주되어 쉽게 무한 루프를 구성할 수 있습니다. 다음 `for` 문은 무한 반복됩니다.

----
for ( ; ; )
    System.out.println(“infinite loop”);
----

while 및 do 문과 마찬가지로 다음 예제와 같이 한 줄로 이루어진 문 또는 블록 문을 사용할 수 있습니다.

[source, java]
----
for (int i = 0; i < 10; i++) 
    System.out.println(i);

for (int i - 0; i < 10; i++) {
    System.out.println(i);
    System.out.println(10 - i);
}
----

== 변수 선언

`while` 문과 `for` 문의 차이점 중 하나는 `for` 문의 초기화 코드에 선언된 변수의 범위가 `for` 문 내에서만 지정된다는 것입니다. 다음 코드는 컴파일 오류를 발생시킵니다.

[source, java]
----
for (int i = 0; i < 10; i++) 
    System.out.println(i);
System.out.println(i);	// i는 for 범위를 벗어남
----

Java의 문 블록 규칙에 따르면, 블록과 그 상위 블록은 같은 이름의 변수를 가질 수 없습니다. 이 규칙은 for 블록에도 적용됩니다. 따라서, 아래와 같은 코드는 허용되지 않습니다.

[source, java]
----
int i = 0;
for (int i = 0; i < 10; i++);	// 오류: 상위 블록과 같은 이름의 변수를 사용할 수 없음
----
for 문의 초기화 코드에서 둘 이상의 변수를 초기화 할 수 있습니다.

[source, java]
----
for (int i = 0, int j = 0; ... ; , , )
----

for 문에서 두 변수를 사용할 때는 같은 타입이어야 합니다. 아래 코드는 허용되지 않습니다.

[source, java]
----
for (int i = 0, long j = 0; i < 10; i++)	// 오류: 다른 타입의 초기자를 사용할 수 없음
----
for 문의 업데이트 코드에서 쉼표 또는 쉼표로 구분된 둘 이상의 식을 사용할 수도 있습니다.

[source, java]
----
for (int i = 0, j = 0; ... ; i++, j++) 
----
for 문은 반복 횟수를 알고 있는 상황에 가장 적합합니다. 특히 배열의 각 요소를 수정하는데 특히 적합합니다.

link:./11_do.adoc[다음: do statement (do 문)] +
link:./13_foreach.adoc[다음: foreach statement(foreach 문)]