= 표준 출력

* System.out의 메소드들로 화면에 정보를 표시함
**  **print**   표준 화면 출력
**  **println**  표준 화면 출력에 줄 바꿈을 같이 표시함
**  **printf**  출력에 포맷을 지정
* printf와 format 메소드를 사용하여 문자열과 숫자에 대해 출력 포맷을 표시할 수 있음

---

`System.out.print` 및 `System.out.println` 메소드를 사용하여 콘솔 화면에 정보를 표시할 수 있습니다. 두 메소드의 사용 방법은 거의 비슷합니다. 차이점은 `println` 은 새 라인/캐리지 리턴 쌍을 끝에 추가하지만 `print` 는 그렇지 않다는 것입니다.

두 메소드는 오버로드 되어 있습니다. 숫자 변수와 매개변수 유형 모두를 사용하여 두 메소드를 호출할 수 있습니다. 예를 들면, 다음 코드를 사용하여 화면에 “100”를 표시할 수 있습니다.

----
System.out.println(100);
----

다음 코드는 화면에 “Hello, World”를 출력합니다.

----
System.out.println(“Hello, World!”);
----

== 텍스트 포맷

`printf` 메소드 또는 `format` 메소드를 사용하면 표준 화면 출력에 형식 문자열을 사용할 수 있습니다. 형식 문자열은 데이터가 출력되는 방식을 지정하고 마커를 포함할 수 있으며, 마커는 뒤에 오는 매개 변수로 순서대로 대체됩니다. 예를 들어 “2 더하기 3은 5”라는 문자열을 화면에 표시할 수 있습니다.

----
System.out.printf("%d 더하기 %d은 %d", 2, 3, 5);
2 더하기 3은 5
----

`%s` 는 문자열을 출력하며, `%S` 는 모두 대문자로 변환 후 출력합니다.

----
System.out.printf("%s, %S", "Hello", "World");
Hello, WORLD
----

`%` 와 `s / S` 사이에 숫자를 입력하면 입력한 숫자만큼의 공간을 할당합니다. 숫자가 양수면 오른쪽으로, 음수이면 왼쪽으로 정렬합니다.

----
System.out.printf("[%15s]%n", "Hello");
System.out.printf("[%-15s]%n", "World");
[               Hello] 
[World               ]
----

`%` 와 `s / S` 사이에 소수점을 입력하면 해당하는 숫자만큼의 문자만을 표시합니다.

----
System.out.printf("%.4s%n", "Hello World!");
Hell
----

`%n` 은 줄 바꿈을 표시합니다.

== 숫자 포맷

지시자들을 사용하여 다양한 숫자 형식을 표시할 수 있습니다. 

[%header, cols="1, 3", width=50%]
|===
|지시자|	설명
|%d	|Integer 형식으로 출력
|%f	|Float 형식으로 출력
|%o	|8진수 형식으로 출력
|%x	|16진수 형식으로 출력
|%b |Boolean 형식으로 출력
|%e	|지수 형식으로 출력
|===

----
System.out.printf("정수와 float, 16진수 포맷: %d, %f, %x", 88, 88.888, 15);
정수와 float, 16진수 포맷: 88, 88.888000, f
----

== 시간 포맷

`%t` 지시자를 사용하여 시간과 날짜를 출력할 수 있습니다.

[%header, cols="1, 3", width=50%]
|===
|지시자|	설명
|%t|	시간을 출력합니다.
|%tH|	시간 값을 출력합니다.
|%tM|	분 값을 출력합니다.
|%tS|	초 값을 출력합니다.
|%tA|	요일 값을 출력합니다.
|%tB|	월 값을 출력합니다.
|%tY|	연도 값을 출력합니다.
|%tD|	월/일/연도 형식 값을 출력합니다.
|%tF|	YYYY-MM-DD 형식 값을 출력합니다.
|%tR|	시간:분 형식 값을 출력합니다.
|%tT|	시간:분:초 형식 값을 출력합니다.
|===

아래 코드는 YYYY-MM-DD 시간:분:초 형식 값을 화면에 출력합니다.

----
Date date = new Date();
System.out.printf("%tF %tT", date, date);
2022-06-07 00:50:24
----

link:./09_systemclass.adoc[이전: System 클래스] +
link:./11_scanner_class.adoc[다음: Scanner 클래스]