= 강력한 타입 검사

* Generics는 타입 안정성(Type Safety)를 지원
** 타입 파라미터를 통해 전달된 타입 정보를 이용하여 컴파일 타임에 검사
* java.lang.Object 타입으로 변환되는 객체 형 변환은 런타임에 검사됨
** 컴파일시에 오류를 발견할 수 없음
** java.lang.ClassCastException 예외 발생
* Generics는 타입이 명확히 명시되므로 컴파일 타임에 오류를 검출할 수 있음

---

Generic이 적용되면 타임 파라미터를 기준으로 타입 안정성을 검사합니다. 이는 코드 작성 중 빈번히 발생될 수 있는 타입 검사 오류를 컴파일시에 확인해 줌으로써, 코드 작성 중 검출할 수 없고 런타임에 발생하는 오류 처리에서 발생하는 손실 비용을 최소화할 수 있도록 해 줍니다.

Generoc이 적용되지 않은 코드에서 일반적인 데이터를 처리하기 위해서는 데이터를 최상위 타입인 java.lang.Object로 처리합니다. 

[source, java]
----
public class TypeSafetyExample {
    public static class Box {
        Object item;

        public void set(Object item) {
            this.item = item;
        }

        public Object get() {
            return this.item;
        }
    }
    public static void main(String [] args) {
        Box box = new Box();
        box.set("Hello");
        Integer value = (Integer) box.get();
        System.out.println("Value is " + value);
    }
}
----

위 코드는 전역변수 item이 일반적인 데이터를 처리하도록 하기 위해 Object 타입을 사용합니다. item의 setter 메소드에서 item에 Hello 문자열을 저장할 경우, String 타입은 Object의 서브타입이므로 item의 값을 가져오기 위해서는 Object 타입을 String 타입으로 타입 변환해야 합니다. 이 경우 컴파일러는 특정 타입을 Object로 타입 변환하는 것에 대해 오류를 발생하지 않습니다.

오류는 프로그램을 실행할 때 발생합니다. 프로그램은 타입 사이의 변환 실패로 오류를 출력하고 실행을 종료합니다. 

----
$ java TypeSafetyExample    
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at TypeSafetyExample.main(TypeSafetyExample.java:16)
----

해당 코드에 Generic을 적용하면 이런 종류의 런타임 오류를 회피할 수 있습니다.

[source, java]
----
public class TypeSafetyGenericsExample {
    public static class Box<T> {
        T item;

        public void set(T item) {
            this.item = item;
        }

        public T get() {
            return this.item;
        }
    }
    public static void main(String [] args) {
        Box<String> box = new Box<>();
        box.set("Hello");
        Integer value = box.get();
        System.out.println("Value is " + value);
    }
}
----

Generic을 사용하여 수정한 위 코드는 컴파일 타임에 오류를 검출합니다.

----
$ javac TypeSafetyGenericsExample.java
TypeSafetyGenericsExample.java:16: error: incompatible types: String cannot be converted to Integer
        Integer value = box.get();
----

Generic의 적용은 타입 검사를 통해 런타임에 발생할 수 있는 타입 오류를 컴파일시에 찾아 줌으로써 오류 발생 지연을 방지하는 기능을 수행할 수 있습니다.

link:./03_generics_overview.adoc[이전: Generics 개요] +
link:./05_reduce_type_check.adoc[다음: 타입 변환 감소]

