= 타입 파라미터 제약

* 타입 파라미터 인자로 기본 데이터 타입을 사용할 수 없음
** 컴파일 과정에서 타입 파라미터 정보는 모두 삭제되고, Object 타입으로 처리됨
* 타입 파라미터 변수의 객체를 생성할 수 없음
** 타입 파라미터는 타입의 인자가 주어지지 전까지는 생성할 수 없음
* static 필드로 선언할 수 없음
** 타입 파라미터 인자가 달라질 수 있어 특정 타입으로 생성할 수 없음

---

Generic 타입은 타입 파라미터와 관련하여 몇 가지 제약 사항들이 있습니다.

== 타입 파라미터 인자로 기본 데이터 타입을 사용할 수 없음

Generic 타입은 컴파일시 삭제되고, 정해진 규칙에 따라 Object 또는 첫 번째 바인딩 된 타입으로 치환됩니다. 타입 파라미터는 타입 파라미터의 슈퍼 타입 제약 또는 서브 타입 제약에 따라 정해진 타입으로 치환되고, 치환되는 타입은 참조 타입이어야 합니다. 따라서, 타입 파라미터 인자로 기본 데이터 타입을 사용할 수 없습니다.

== 타입 파라미터 변수의 객체를 생성할 수 없음

클래스의 인스턴스를 생성하기 위해서는 객체를 위한 메모리 공간을 할당한 후 클래스의 생성자를 호출 해야 합니다. 타입 파라미터의 타입은 결정되지 않은 상태이기 때문에 클래스의 생성자를 호출랄 수 없어, 컴파일 시 오류가 발생합니다. 필요한 경우, 리플렉션을 사용할 수 있습니다.

[source, java]
----
public static <E> void append(List<E> list, Class<E> cls) {
    E elem = cls.newInstance();
    list.add(elem);
}
----

== static 필드로는 선언할 수 없음

static 필드는 객체와 다른 영역에 할당되는 공유 수준 변수이고, 클래스가 로드 될 때 생성됩니다. 타입 파라미터 인자가 달라질 수 있으므로, 특정 타입으로 생성되어야 하는 static으로 선언될 수 없습니다.

link:./23_generics_limitations.adoc[이전: Generics 제약] +
link:./25_generic_type_limitations.adoc[다음: Generic 타입 제약]

