= Lambda Expression의 필요성

* 코드의 간결성
** 익명 클래스를 대신해 짧고 간결한 코드 작성 가능
+
[source, java]
----
Runnable r = () -> System.out.println("Hello, World!");
----
* 가독성 향상
** 장황한 코드 대신 함수의 목적에만 집중 가능
* 보일드플레이트 제거
** 클래스 이름, 메소드 선언 등 반복적인 코드 제거로 유지보수 용이
* 함수형 프로그래밍 지원
** 스트림 API와 결합해 선언적이고 직관적인 코드 작성
+
[source, java]
----
names.stream()
    .filter(name -> name.startsWith("C"))
    .forEach(System.out::println);
----
+
* 병렬 처리 지원
** 스레드 관리 없이 병렬 데이터 처리를 쉽게 구현 가능
+
[source, java]
----
numbers.parallelStream()
    .map(n -> n * n)
    .forEach(System.out::println);
----
+
* 콜백 및 이벤트 처리 간소화
** 간단한 Lambda Expression으로 이벤트 리스트 및 콜백 작성 가능
+
[source, java]
----
button.setOnAction(event -> System.out.println("Button clicked!"));
----

---

Lambda Expression은 Java 8에서 도입되었으며, 주로 코드의 간결성, 가독성, 생산생을 높이기 위해 필요합니다. 

1. 코드의 간결성
+
기존 자바에서는 익명 클래스를 사용해 간단한 작업을 수행하는데도 장황한 코드가 필요했습니다. 람다 표현식을 사용하면 동일한 기능을 훨씬 더 간단하게 작성할 수 있습니다.
+
**익명 클래스를 사용한 구현**
+
[source, java]
----
@FunctionalInterface
public interface AInterface {
    void doSomething();
}

AInterface anomymousObject = new AInterface() {
    @Override
    public void doSomething() {
        System.out.println("Hello, World!");
    }
};
anomymousObject.doSomething();
----
+
**Lambda Expression 사용**
+
[source, java]
----
@FunctionalInterface
public interface AInterface {
    void doSomething();
}

AInterface lambda = () -> System.out.println("Hello, Lambda!");
lambda.doSomething();
----
+
위와 같이 Lambda Expression을 사용하면 코드가 짧아지면서 가독성이 크게 향상됩니다. 복잡한 익명 클래스 선언 대신 함수의 목적에만 집중할 수 있습니다.
+
또한, 익명 클래스 작성시 필요했던 메소드 이름, 클래스 이름, 중괄호 등 불필요한 보일러플레이트(반복적인 코드)를 제거하여 필요 없는 코드가 줄어들어 유지 보수를 쉽게 합니다.

2. 함수형 프로그래밍 지원
+
함수형 프로그래밍은 함수(function)를 일급 시민(First-class citizen)으로 취급하여 프로그램의 상태 변경을 최소화하고 순수 함수(Pure function)를 통해 문제를 해결하는 방식을 강조하는 프로그래밍 기법입니다.
+
Lambda Expression을 사용하면 Java에서 함수형 프로그래밍을 가능하게 하여, 이를 통해 더 선언적이고 직관적인 코드를 작성할 수 있습니다. Stream API와 함께 사용하여 데이터를 처리하는데 유용합니다.
+
[source, java]
----
List<String> names = Arrays.asList("Alice", "Bob", "Charlie");
names.stream()
    .filter(name -> name.startsWith("C"))
    .forEach(System.out::println);
----

3. 병렬 처리 지원
+
Lambda Expression과 Stream API는 병렬 처리를 쉽게 수행할 수 있도록 합니다. 복잡한 스레드 관리 없이 병렬로 처리하는 코드를 간단하 직성할 수 있습니다.
+
[source, java]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5);
numbers.parallelStream()
    .map(n -> n * n)
    .forEach(System.out::println);
----

4. 콜백 및 이벤트 처리 간소화
+
Lambda Expression을 사용하면 기존의 복잡했던 이벤트 리스너, 콜백 함수등을 작성할 때 간결한 코드를 쓸 수 있습니다.
+
[source, java]
----
button.setOnAction(event -> System.out.println("Button clicked!"));
----

Lambda Expression은 기존의 장황한 익명 클래스 코드를 간소화하고, 함수형 프로그래밍을 Java에 통합하여, 병렬 처리 및 데이터 처리와 같은 모던한 요구를 효과적으로 지우너합니다. 이를 통해 개발자는 생산성과 가독성을 동시에 높일 수 있습니다.