== 기본 생성자 사용

* 클래스에 생성자를 작성하지 않으면 기본 생성자가 생성됨
** public 접근 제한
** 클래스와 이름이 같음
** return 타입이 없음 – void가 아님
** 파라미터가 없음
** 모든 필드는 기본 값으로 초기화
* 생성자 구문

[source, java]
----
class Date {
    public Date() { … }
}
----

---

객체가 생성될 때, 프로그래머가 생성자를 작성하지 않았을 경우 컴파일러는 기본 생성자를 제공합니다.

[source, java]
----
class Date {
    private int year, month, day;
}

class Test {
    public static void main(String[] args) {
        Date today = new Date();
    }
}
----

Test 클래스의 main 메소드에서 new 연산자를 호출하여 메모리에 Date 객체가 존재할 수 있는 공간을 할당합니다. 그 후 클래스와 이름이 같은 특수한 형태의 메소드인 생성자(Constructor)를 호출하여 today가 참조하는 Date 타입 객체를 생성합니다. 

Date 클래스에서는 클래스의 이름과 같고 return 타입이 없는(void가 아님) 특수한 형태의 메소드를 작성하지 않았습니다. Test 클래스의 main 메소드에서 사용하는 생성자는 컴파일러가 제공하는 기본 생성자입니다.

== 기본 생성자

`Date` 클래스에서 실제로 일어난 일을 코드로 작성해 보면 다음과 같습니다.

[source, java]
----
class Date { 
    private int year, month, day;
    public Date( ) { 
        year = 0; 
        month = 0; 
        day = 0; 
    } 
}
----

특수한 형태의 메소드인 생성자는 아래와 같은 특징을 가지고 있습니다.

* 클래스 이름과 같은 이름 +
인스턴스 생성자는 클래스와 같은 이름의 메소드입니다. 이는 직관적인 정의이며 앞에서 보았던 예와 일치합니다.
+
[source, java]
----
Date today = new Date();
----
* return 타입이 없음 +
생성자의 또 다른 특징 중 하나는 메소드이지만 return 타입이 없다는 것입니다. 아무 값도 반환하는 않는다는 것을 의미하는 타입인 `void` 가 아닙니다. 생성자에는 return 타입이 아예 없습니다.

* 파라미터 인자를 필요로 하지 않음 +
인스턴스를 초기화하는데 필요하다면, 생성자에서 인자를 받을 수 있습니다. 컴파일러에 의해 생성되는 기본 생성자는 아무런 인자를 가지지 않습니다.

* 모든 필드는 기본값으로 초기화 됩니다. +
컴파일러에 의해 생성되는 기본 생상자는 클래스에 포함된 모든 비 정적 필드를 기본 값으로 초기화합니다.
** 숫자형 필드(int, double 등)은 0으로 초기화됩니다.
** boolean 필드는 false로 초기화 됩니다.
** 참조 타입은 null로 초기화 됩니다.
* `public` 접근 제한을 가집니다. +
객체가 생성되는 것을 허용합니다.

link:./03_object_creation.adoc[이전: 객체생성] +
link:./05_defailt_constructor_overriding.adoc[다음: 생성자 오버라이딩]