= 초기화 목록

* 오버로드 된 생성자는 같은 코드를 포함할 가능성이 높음
** 생성자를 서로 호출하도록 리팩토링
** this 키워드를 사용하여 초기화 목록을 호출

[source, java]
----
class Date {
    public Date() { 
        this(1971, 04, 28);
    }
    public Date(int year, int month, int day){ 
        ...
    }
}
----

초기자 목록(initializer list)이라는 특수 구문을 사용하여 한 생성자에서 오버로드된 다른 생성자를 호출하여 생성자를 구현할 수 있습니다.

== 초기화 코드 중복 회피
아래의 코드는 기본 생성자와 파라미터를 가지는 생성자, 두 생성자를 가지고 있습니다.

[source, java]
----
class Date {
    private int year, month, day;

    public Date() {
        this.year = 1070;
        this.month = 4;
        this.day = 28;
    }

    public Date(int year, int month, int day) {
        this.year = year;
        this.month = month;
        this.day = day;
    }
}
----

Date 클래스의 세 필드에 값을 할당하는 코드가 두 생성자 모두에 구현되어 있습니다. this.year = 코드는 두 생성자에서 중복됩니다. 완전히 중복되는 것은 아니지만 할당의 의미에서는 동일하므로, 이런 코드 중복은 피하는 것이 좋습니다. 만약 `Date` 객체 내부에서 날짜를 표현하는 방법을 바꾸기로 결정했다면, 두 생성자의 코드는 모두 수정되어야 합니다.

== 중복된 초기화를 피하여 리팩토링

이런 회피를 위한 가장 표준화된 방법은 공통된 코드를 다른 메소드로 분리하는 것입니다. 아래 코드는 그 예를 보여줍니다:

[source, java]
----
class Date {
    private int year, month, day;
    public Date() {
        init(1971, 04, 28);
    }
    
    public Date(int year, int month, int day) {
        this.init(year, month, day);
    }

    private void init(intt year, int month, int day) {
        this.year = year;
        this.month = month;
        this.day = day;
    }
}
----

위 코드는 `this.year`, `this.month`, `this.day` 에 값을 할당하는 코드가 중복되지 않습니다. 만약 내부에서 날짜를 표시하는 방법을 바꾸었다면 `init` 메소드만 수정하면 됩니다. 이런 방식의 리팩토링은 동작하지만, 동작하지 않는 경우도 있습니다. 객체 지향 프로그래밍 언어를 이런 문제를 보다 품위 있게 해결하는 방법을 제공합니다.

== 초기자 목록 사용

초기자 목록을 사용하면 동일한 클래스의 다른 오버로드된 생성자를 호출하는 생성자를 작성할 수 있습니다. this 키워드를 사용하고 생성자 내에서 호출하고자 하는 파라미터 타입과 개수에 맞는 인자를 명시하면 클래스내에 작성된 해당 오버로드된 생성자를 호출합니다.

[source, java]
----
class Date {
    private int year, month, day;
    public Date() {
        this(1971, 04, 28);
    }
    
    public Date(int year, int month, int day) {
        this.year = year;
        this.month = month;
        this.day = day;
    }
}
----

이 코드는 `init` 메소드를 작성하는 것 보다 효과적이며 품위있는 방법을 제공합니다.

== 초기자 목록 제한사항

초기자 목록에는 몇 가지 제한 사항이 있습니다.

* `this` 키워드를 사용해서 생성자를 호출하는 것은 생성자에서만 할 수 있습니다.

[source, java]
----
class Date {
    public Date(int year, int month, int day) { … }
    void init(int year, int month, int day) {
        this(year, month, day);	// 컴파일 시 오류
    }
}
----

* 초기자 목록에서 자신을 호출할 수 없습니다.

[source, java]
----
class Date {
    public Date(int year, int month, int day) { 
            this(int year, int month, int day);	// 컴파일 시 오류
    }
}
----

* this를 파라미터로 사용할 수 없습니다.

[source, java]
----
class Date {
    private int year, month, day;
    public Date() {
        this(this(1971, 04, 28));
    }
}
----

link:./07_initiate_data.adoc[이전: 데이터 초기화] +
link:./09_declare_constant.adoc[다음: 상수 선언]