= 객체 생명주기

* 객체 생성
** new 키워드를 사용하여 메모리에 객체 할당
** 생성자를 사용하여 메모리에서 객체 초기화
* 객체 사용
** 메소드 호출 등
* 객체 제거
** 원시 메모리 회수
** 메모리 할당 해제

---

Java에서 객체의 생명 주기는 크게 세 단계로 생각할 수 있습니다. 객체는 생성되고, 사용되며, 제거됩니다.

== 객체 생성

클래스의 인스턴스인 객체를 생성합니다. 
1.	new 키워드를 사용하여 필요한 메모리를 할당합니다.
2.	생성자를 사용하여 new 연산자로 획득한 원시 메모리에 객체를 생성합니다. 이때 객체의 상태는 Created가 됩니다.

== 객체 사용

프로그램에서 객체를 사용합니다. 

1.	In use or reachable (사용 중) +
객체가 생성되어 다른 객체에 의해 참조되어 있는 경우입니다. 이때 객체의 상태를 Strong referenced 상태라고 합니다.
2.	Invisible (사용 중이며 접근 불가) +
Strongly reference되어 있으나 직접 접근할 수 없는 상태이며 바로 가비지 컬렉터의 대상이 되지 않는 상태입니다. 이 경우 메모리 누수를 유발할 수 있어 명시적으로 null을 할당하는 것이 좋습니다.
3.	Unreachable (사용되지 않음) +
Strong reference가 존재하지 않는 경우이며 이 상태의 객체는 가비지 컬렉션의 후보가 됩니다. 이런 객체들은 가비지 컬렉터 체인에 의해 참조됩니다.

== 객체 제거

사용되지 않는 객체는 가비지 컬렉터에 의해 자동으로 제거됩니다.

1.	Collected (가비지 컬렉터의 대상이 됨) +
가비지 컬렉터가 객체의 finalize가 정의되어 있는지 판단하고 finalize가 있다면 finalizer 큐에 넣고 없으면 바로 다음 단계로 진행합니다.
2.	Finalized (제거) +
Finalizer를 통해 finalize가 실행된 상태로, 객체를 제거합니다.
3.	Deallocated (메모리 해제) +
메모리 반환이 끝나고 가비지 컬렉터의 동작이 마무리 됩니다.

link:./13_object_and_memory.adoc[이전: 객체와 메모리] +
link:./15_object_and_scope.adoc[다음: 객체와 범위]