= 디자인 패턴 개요

* 소프트웨어 설계 기법
** 특정 컨텍스트에서 반복적으로 발생하는 문제에 대한 재사용 가능한 해결책
** 다른 상황에 맞게 사용될 수 있는 문제들을 해결하는데 쓰이는 서술 또는 템플릿
** 프로그래머가 소프트웨어를 디자인 할 때, 공통된 문제들을 해결하는데 쓰이는 형식화된 관행
* 건축가 크리스토퍼 알렉산더가 건축 설계를 위한 개념으로 창안, 켄트 벡과 워드 커닝헌에 의해 소프트웨어 디자인을 위한 패턴으로 구체화 됨
* Design Patterns: Elements of Reusable Object-Oriented Sofrtware가 출판된 후 널리 알려짐
* 객체지향 설계 기법으로 유명해진 디자인 패턴은 아키텍처, 동시성 제어, 클라우드 아키텍처 등의 설계 기법으로 확장됨

---

소프트웨어 설계 기법은 여러 면에서 건축 설계 기법에 빚을 지고 있습니다. 건축가 크리스토퍼 알렉산더 footnote:[Christoper Alexander, 오스트리아 출신의 건축가. 1936 - 2022]는 패턴 랭귀지footnote:[Pattern Language, Christopher Alexander, Sara Iskikawa, Murray Silverstein, Oxford University Press, 1977]라는 책에서 “각각의 디자인 패턴은 기존 환경 내에서 반복적으로 일어나는 문제들을 설명하고, 그 문제들에 대한 해법의 핵심을 설명하는 것이다. 이렇게 하면 똑 같은 방법을 두 번 반복하지 않은 채 이 해법을 백만번 이상 반복할 수 있다.”라고 하였습니다.

알렉산더 크리스토퍼의 이 말은 시가지를 설계하거나 빌딩을 지을 때에 대한 이야기이긴 하지만, 이 원칙은 소프트웨어 설계에도 해당될 수 있습니다. 건축에서는 기후, 날씨, 생활양식과 관련되어 벽의 두께나 문의 높이 등을 결정하는 것에 관련된 문제를 해결하기 위한 관례화 된 패턴으로 이야기하지만, 소프트웨어 세계에서는 객체와 인터페이스에 관련된 이야기로 생각할 수 있습니다. 이 경우의 공통점은 패턴을 어떤 상황의 문제에 대한 해법으로 본다는 것입니다.

객체지향 소프트웨어를 설계한다는 것은 쉬운 일이 아닙니다. 객체지향의 궁극적인 목적인 다형성을 통한 극대화된 재 사용이 가능한 소프트웨어를 만들기는 어렵습니다. 객체지향 설계에 경험이 있는 사람들은 처음부터 제대로 재 가능한 소프트웨어를 설계하는 것은 불가능하다고 이야기합니다 하지만 경험이 많은 소프트웨어 설계자들은 좋은 객체지향 설계를 할 수 있습니다. 

경험자와 초보자가 다른 점은, 문제를 기초 단계에서 해결하지 않고 전에 사용했던 해결책을 다시 사용해 본다는 것입니다. 전에 사용했던 해결책이 당면한 문제를 해결하는데 도움이 되었다면 그 방법을 반복해서 사용하게 됩니다. 이런 경험을 통해 특정 컨텍스트에서 반복되는 문제는 유사한 객체간의 상호 작용 방법으로 해결될 수 있다는 것을 알고 정리하게 됩니다.

디자인 패턴은 소프트웨어 설계에서 얻은 경험들을 기록해 놓은 것입니다. 각각의 경험을 패턴화하고, 객체지향 방식의 이름을 지어주고, 중요하고 반복되는 설계를 평가하여 기록한 것이 디자인 패턴입니다.

디자인 패턴은 소프트웨어 설계 기법으로, 

* 특정 컨텍스트에서 반복적으로 발생하는 문제들에 대한 재사용 가능한 해결책이며,
* 다른 상황에 맞게 사용될 수 있는 문제들을 해결하는데 쓰이는 서술 템플릿이고,
* 프로그래머가 소프트웨어를 디자인할 때 공통된 문제를 해결하는데 쓰이는 형식화된 관행입니다.

link:./01_design_pattern.adoc[이전: 디자인 패턴] +
link:./03_element_design_pattern.adoc[다음: 디자인 패턴의 요소]