= 디자인 패턴의 요소

* 패턴의 이름(Name of Pattern)
** 설계 문제와 해법을 기술하며, 문서에서 패턴의 이름을 사용하여 설계의 의도를 표현할 수 있도록 함
* 문제(Problem)
** 언제 패턴을 사용하는지를 기술하며 해결된 문제와 그 배경을 설명함. 설계의 세밀한 문제를 설명할 수 있음
* 해법(Solution)
** 설계를 구성하는 요소들과 그 요소들 간의 설계, 책임 및 협력 관계를 서술
** 패턴은 다양한 경우에 적용할 수 있는 템플릿이므로 특정 구현을 설명하지 않음
* 결과(Consequences)
** 패턴을 적용해서 얻는 결과와 장단점을 서술
** 패턴의 결과는 시스템의 유연성, 확장성, 이식성 등에 대단한 영향을 주므로 결과를 잘 정리하는 것은 패턴을 이해하거나 평가하는데 도움을 줌

---

디자인 패턴은 일반적으로 다음 네 가지 요소를 정의합니다.

1. 패턴의 이름(Name of Pattern) +
잘된 추상적 기법을 사용하여 패턴의 이름을 기술합니다. 패턴의 이름만으로도 설계의 의도를 알아챌 수 있도록 이름을 붙이며, 설계에 대한 생각을 더욱 쉽게 할 수 있고 개발자들간의 의사소통을 명확하게 할 수 있도록 합니다. 좋은 이름을 짓는 것은 추상화의 시작이며, 이는 어려운 일입니다.
2. 문제 (Problem) +
해결해야 할 문제와 그 배경을 설명합니다. 문제를 해결하기 위해 언제 패턴을 사용하는지도 서술합니다. 문제를 제시함으로써 패턴을 적용하는 것이 의미 있는 경우들을 정의합니다.
3. 해법 (Solution) +
설계를 구성하는 요소들과 그 요소들 간의 관계, 책임 및 협력 관계를 서술합니다. 디자인 패턴에서의 해법은 구체적인 설계나 구현을 설명하지는 않습니다. 패턴은 적용할 수 있는 객체 구조의 템플릿이고, 따라서 문제에 대한 추상적인 설명을 제공하고 문제를 해결하기 위한 클래스나 객체의 배치 방법을 설명합니다.
4. 결과 (Consequences) +
디자인 패턴을 적용해서 얻는 결과와 장단점을 서술합니다. 객체지향의 궁극적인 목적인 다형성을 통한 재사용이므로, 패턴의 결과는 시스템의 유연성, 확장성, 이식성등에 대단한 영향을 줍니다. 따라서 설계의 결과를 잘 정리하는 것은 패턴을 이해하거나 평가하는데 도움이 됩니다.

link:./02_introduction_design_pattern.adoc[이전: 디자인 패턴 개요] +
link:./04_classify_design_pattern.adoc[다음: 디자인 패턴의 분류]