= 생성 패턴

* 객체의 생성과 관련된 패턴
* 객체의 생성과 조합을 캡슐화 해 특정 객체가 생성되거나 변경되어도 프로그램 구조에 영향을 크게 받지 않는 유연성을 제공
** 시스템이 어떤 클래스를 사용하는지를 캡슐화
** 클래스의 인스턴스를 어떻게 만드는지, 그리고 이들의 합성 방법을 어떻게 숨기는지 기술
* 종류
** 추상 팩토리(Abstract Factory) 패턴
** 빌더(Builder) 패턴
** 팩토리 메소드(Factory Method) 패턴
** 프로토타입(Prototype) 패턴
** 싱글턴(Singleton) 패턴

---

생성 패턴은 객체의 생성에 관련된 패턴으로 객체의 생성 절차를 추상화하는 패턴입니다. 객체를 생성-합성하는 방법 및 객체의 표현방법과 시스템을 분리합니다.

생성 패턴은 인스턴스로 만들 클래스를 다양하게 만들기 위한 용도로 사용하는 클래스 생성패턴과 인스턴스화 작업을 다른 객체가 하도록 떠넘기는 객체 생성 패턴으로 나눌 수 있습니다.

* 생성 패턴은 시스템이 어떤 콘트리트 클래스를 사용하는지에 대한 정보를 캡슐화합니다.
* 생성 패턴은 이들 클래스의 인스턴스들이 어떻게 만들어지고 어떻게 서로 맞붙는지에 대한 부분을 완전히 가립니다.

객체의 생성과 조합을 캡슐화 해 특정 객체가 생성되거나 변경되어도 프로그램 구조에 영향을 받지 않도록 유연성을 제공합니다.
GoF의 디자인 패턴에 정리된 생성 패턴은 다음과 같습니다:

* 추상 팩토리(Abstract Factory) 패턴 +
구체적인 클래스를 지정하지 않고 관련성을 갖는 객체들의 집합을 생성하거나 서로 독립적인 객체의 집합을 생성할 수 있는 인터페이스를 제공합니다.
* 빌더(Builder) 패턴 +
복합 객체의 생성 과정과 표현 방법을 분리함으로써 동일한 생성 공정이 서로 다른 표현을 만들 수 있게 합니다.
* 팩토리 메소드(Factory Method) 패턴 +
객체를 생성하는 인터페이스를 정리하지만, 인스턴스를 만들 클래스의 결정은 서브 클래스가 합니다. 팩토리 메소드 패턴에서는 인스턴스를 만드는 시점은 서브클래스로 미룹니다.
* 싱글턴(Singleton) 패턴 +
클래스의 인스턴스는 오직 하나임을 보장하며 이 인스턴스에 접근할 수 있는 방법을 제공합니다.

link:./04_classify_design_pattern.adoc[이전: 디자인 패턴 분류] +
link:./06_structural_pattern.adoc[다음: 구조 패턴]