= Java 패키지

* Java는 프로그래밍에 도움을 줄 수 있는 클래스 라이브러리(Class Librrary)를 제공
** 클래스들의 위치와 역할을 한 눈에 알 수 있도록 이름 공간으로 정리
** 패키지는 디렉토리로 구성됨
* 코드의 시작 부분에 import 문을 사용하여 사용할 패키지를 명시

[source, java]
----
import java.util.Scanner;
import java.io.*;
----

* 패키지 이름을 포함하는 전체 클래스 이름을 사용할 수 있음

[source, java]
----
String s1 = new String(“Hello”);
java.lang.String s2 = new java,lang.String(“Hello”);
----

---

Java는 프로그래밍에 도움을 줄 수 있는 여러 클래스들을 제공합니다. 이 클래스들의 위치와 역할을 한 눈에 알 수 있도록 하기 위해 Java는 클래스들을 이름공간으로 정리하며, 각 타입에 대한 고유한 이름 공간들을 제공합니다. 이 이름 공간을 패키지라고 부르며 패키지는 디렉토리로 구성됩니다.

Java에서 패키지에 포함된 클래스를 사용하기 위해서는 아래 두 가지 방법을 사용할 수 있습니다.

== `import` 문을 사용하여 코드의 시작 부분에서 사용할 패키지를 명시

`Scanner` 클래스는 `java.util` 패키지에 포함되어 있습니다. `Scanner` 클래스를 코드에서 사용하려면 아래와 같이 `import` 문으로 `Scanner` 클래스의 사용을 명시합니다.

[source, java]
----
import java.util.Scanner;
----

== 패키지 이름을 포함하는 전체 클래스 이름을 사용

`Scanner` 클래스는 `java.util` 클래스에 포함되어 있으므로 패키지 이름을 포함한 전체 클래스 이름(Full name)은 `java.util.Scanner` 가 됩니다. `import` 문을 사용하여 패키지 사용을 명시하지 않았다면 아래와 같이 객체를 생성하고 사용할 수 있습니다.

[source, java]
----
java.util.Scanner scanner = new java.util.Scanner(System.in);
----

Java에서 모든 클래스들의 기본 클래스가 되는 `Object` 클래스는 `java.lang` 패키지에 포함되어 있습니다. `java.lang` 패키지는 기본이 되는 클래스들을 포함하는 패키지로, `import` 문으로 패키지의 사용을 선언하지 않고도 포함된 클래스들을 사용할 수 있습니다. 예를 들어 `String` 클래스의 경우, 아래의 두 코드는 동일한 동작을 수행합니다.

[source, java]
----
String s1 = new String("Hello");
java.lang.String s2 = new java.lang.String("Hello");
----

link:./23_java_package.adoc[이전: Java 패키지] +
link:./25_java_lang_package.adoc[다음: java.lang 패키지]