= java.util 패키지

* 다용도로 사용할 수 있는 유용한 클래스들이 포함되어 있는 패키지
** Object 클래스의 보조 클래스인 Objects 클래스
** 날짜, 시간과 관련된 클래스
** 자료구조와 관련된 Collections Framework 관련 인터페이스와 클래스
** 이벤트 모델과 국제화 기능
** StringTokenizer, 난수 생성기
** Scanner 클래스 등 다양한 클래스와 인터페이스 포함

---

`java.util` 패키지는 java 프로그래밍에 유용한 클래스들을 모아둔 패키지입니다. 날짜, 시간과 관련된 클래스, 자료구조와 관련된 Collections Framework 관련 인터페이스와 클래스등이 포함되어 있습니다. 

* 날짜 관련 클래스 +
날짜 관련 정보를 표시할 수 있는 Date와 Calendar 클래스 등이 포함되어 있습니다. 지역화를 지원하여 다양한 지역의 날짜 형식을 사용할 수 있습니다. 
+
[source, java]
----
Date date = new Date();
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd", Locale.KOREAN);
----
+
`java.util` 패키지의 시간 관련 클래스들은 JDK 1.0부터 지원되었으며, 몇 가지 문제점이 발견되어 Java 8에서부터 지원되는 `java.time` 패키지의 클래스들을 많이 사용합니다.

* 자료 구조와 관련 Collection Framework 관련 인터페이스와 클래스 +
LinkedList, ArrayList, Stack, Vector, HashSet, LinkedHashSet, TreeSet, HashMap등 자료구조와 관련된 인터페이스와 클래스들을 포함하고 있습니다.

* Random 클래스
`Random` 클래스는 `Seed` 값에 의한 난수를 생성해 반환하는 클래스로 정수, 실수, 부울값 등을 생성하여 사용할 수 있습니다. 아래 예제는 min 보다 크거나 같고 max보다 작거나 같은 난수를 생성해 반환합니다.
+
[source, java]
--
Random random = new Random();
int max = 10, min = 1;
int value = random.nextInt(max - min + 1) + min;
System.out.println(value);
--

* StringTokenizer 클래스 +
`StringTokenizer` 클래스는 문자열을 토큰 단위로 나눕니다. `hasMoreTokens` 메소드에서 더 읽을 토큰이 있으면 `true를`, 아니면 `false를` 반환하며 `nextToken` 메소드로 토큰화 된 `String` 을 반환합니다. 아래 예제는 `String` 을 공백문자를 기준으로 `Tokenize` 하는 예를 보여줍니다.
+
[source, java]
--
String lyincs = "Yesterday all my troubles seems so farawat";
StringTokenizer tokenizer = new StringTokenizer(lyincs);
while(tokenizer.hasMoreTokens()) {
	System.out.println(tokenizer.nextToken());
}
--

그 외 앞 모듈에서 사용했던 `Scanner` 클래스 등 많은 유용한 클래스들을 포함합니다.

link:./25_java_lang_package.adoc[이전: java.lang 패키지] +
link:./27_java_io_package.adoc[다음: java.io 패키지]