= 슈퍼 클래스/서브 클래스 변환

* 슈퍼 클래스로 변환
** 암시적(Implicit) / 명시적(Explicit) 모두 가능
** 언제나 변환에 성공함
** Object로 변환 가능
* 서브 클래스로 변환
** 명시적(Explicit)으로 변환
** 바른 타입으로 변환되는지 점검
** 변환되지 않을 경우 ClassCastException 발생

---

특정 조건을 만족한다면 서브 클래스의 객체를 슈퍼 클래스의 객체로 또는 그 반대로 변환할 수 있습니다.

== 슈퍼 클래스 참조로 변환

클래스가 다른 클래스를 직접적으로 또는 간접적으로 상속하는 경우, 클래스 타입을 다른 클래스 타입으로 변환할 수 있습니다. 

객체는 슈퍼 클래스 타입 객체로 언제나 변환될 수 있습니다. 이 변환은 암시적 또는 명시적 두 가지 방법을 모두 사용할 수 있습니다.

동물을 객체로 모델링한 예를 생각해 봅시다. 동물과 새, 두 타입이 있을 경우 동물은 새의 슈퍼 클래스가 됩니다. 이는 새가 동물을 상속한다는 것과 동일한 뜻입니다. 동물 타입 객체와 새 타입 객체가 있을 경우, 새는 동물로 변환될 수 있습니다. 두 클래스가 아래와 같다고 할 때:

[source, java]
----
class Animal {
    void eat() {}
}

class Bird extends Animal {
    void fly() {}
}
----

아래와 같이 두 타입 변수가 선언되고 Bird 클래스 객체를 생성하였을 경우

[source, java]
----
Animal a;
Bird b = new Bird();
----

`Bird` 클래스는 `Animal` 클래스를 상속합니다. `Bird` 클래스는 `Animal` 클래스의 서브 타입이므로 암시적 형 변환이 가능합니다. 

[source, java]
----
a = b;
----

`Animal` 타입인 `a` 는 `eat` 메소드만을 가지고 있습니다. `Animal` 을 상속하는 `Bird` 타입인 `b` 는 `eat` 와 `fly` 두 메소드를 가집니다. `b` 가 `a` 로 변환되면, 즉 `Bird` 타입에서 `Animal` 타입으로 변환되면 `b` 는 `Bird` 의 인스턴스이지만 `Animal` 타입이므로 `Animal` 이 가진 `eat` 메소드만을 가지게 됩니다.

서브 클래스에서 슈퍼 클래스로 타입 변환은 명시적으로도 가능합니다.

[source, java]
----
a = (Animal)b;
----

이 경우 암시적 타입 변환과 명시적 타입 변환은 똑 같이 동작합니다.

== 서브 클래스로 타입 변환

슈퍼 클래스는 서브 클래스로 변환될 수 있습니다. 이 경우에는 반드시 명시적으로 타입 변환되어야 합니다. 명시적 타입 변환은 런타임에 타입 변환이 가능한지 체크한 후, 가능할 경우 변환이 이루어집니다.

[source, java]
----
Bird b = (Bird)a;
----

이 코드는 성공적으로 컴파일 됩니다. 런타임에 타입 변환이 가능한지 여부를 체크 한 후, 변환 가능하다면 문제 없이 동작합니다. 하지만 런타임에 타입 변환이 불가능하다면, ClassCastException이 발생합니다.

서브 클래스에서 슈퍼 클래스로 타입을 변환하고자 할 때는 반드시 명시적으로 변환해야 합니다. 암시적으로 변환할 경우 컴파일시 오류가 발생합니다.


[source, java]
----
Animal animal = new Animal();
Bird b = animal;	// 컴파일 오류
----

타입 변환 오류는 예외로 처리될 수 있습니다.

[source, java]
----
try {
    Animal animal = new Animal();
    Bird b = (Bird)animal;
}
catch (Exception e) {
    e.printStackTrace();
}
----

link:./32_boxing_unboxing.adoc[이전: Boxing과 Unboxing] +
link:./34_instanceof.adoc[다음: instanceof 연산자]