= Lab 8-2: 타입 변환

== 연습 1 인터페이스 구현 여부 테스트

이 연습에서는 이전 연습에서 작성한 `Utilities` 클래스에 `isCharSequence` 메소드를 추가합니다. `isCharSequence` 메소드는 `Object` 타입 파라미터를 가지며, 이 파라미터에 인자로 전달된 객체가 `Formattable` 타입인지 아닌지를 판별합니다.

`CharSequence` 인터페이스는 다양한 종류의 `Char` 타입에 대한 균일한 읽기 전용 액세스를 제공하는지의 여부를 나타냅니다. `CharSequence` 인터페이스를 구현하는 타입은 `charAt()` 메소드를 구현합니다.

=== isCharSequence 메소드 정의

1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab8-2\Starter 폴더를 엽니다.
3.	//To-do: add add isCharSequence method here 부분에 아래와 같이 `isCharSequence` 메소드를 작성합니다.
A.	`isCharSequence` 메소드는 정적이며, `Utilities` 클래스 안에 작성됩니다. 
B.	`Object` 타입의 `object` 를 파라미터로 가지며, `boolean` 타입을 반환합니다.
C.	`instanceof` 연산자를 사용하여 파라미터 인자로 전달된 `object` 가 `CharSequence` 타입인지 판별하고 맞으면 `true`, 아니면 `false를` 반환합니다.
D.	완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public static boolean isCharSequence(Object object) {
    if (object instanceof CharSequence) {
        return true;
    } else {
        return false;
    }
}
----

=== isCharSequence 메소드 테스트

1.	Visual Studio Code 탐색기에서 Test.java 파일을 엽니다.
2.	`main` 메소드의 To-do: add test code here 부분에, int 타입 변수 `i` 를 선언하고 0으로 초기화합니다.
3.	Integer 타입 변수 `number` 를 선언하고 1을 값으로 객체를 생성합니다.
4.	String 타입 변수 `s` 를 선언하고 “Hello”로 초기화 합니다.
5.	위에서 작성한 `Utilities.isCharSequence` 메소드를 사용해서 `i`, `number`, `s` 변수가 `CharSequence` 로 변환될 수 있는 서브 타입인지 확인하는 코드를 작성합니다.
6.	완성한 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public static void main(String[] args) {
    int i = 0;
    Integer number = 1;
    String s = "Hello";

    System.out.println(Utilities.isCharSequence(i));
    System.out.println(Utilities.isCharSequence(number));
    System.out.println(Utilities.isCharSequence(s));
}
----
7.	터미널을 열고 아래 명령을 수행하여 프로그램을 컴파일 합니다.
+
----
> javac Utilities.java Test.java
----
+
8.	터미널을 열고 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
> java Test
false
false
true
----

== 연습 2 인터페이스 작업

이 연습에서는 `Utilities` 클래스에 `display` 메소드를 작성하고 `IPrintable` 인터페이스를 구현하는 클래스이면 클래스의 정보를 보여주는 프로그램을 작성합니다. 이 프로그램은 미리 작성된 `IPrintable` 인터페이스를 사용합니다.

1.	Visual Studio Code의 탐색기에서 IPrintable.java 파일을 엽니다.
2.	파일의 코드를 확인합니다. `IPrintable` 인터페이스와 `Message` 클래스가 작성되어 있습니다.
+
[source, java]
----
public interface IPrintable {
    void print();
}

class Message implements IPrintable {
    private String message;

    public Message(String message) {
        this.message = message;
    }

    public void print() {
        System.out.println(this.message);
    }
}
----
+
3.	Utilities.java 파일을 엽니다.
4.	`Utilities` 클래스에 `display` 메소드를 아래와 같이 추가합니다.
A.	`static` 이며, `Object` 타입의 `item` 을 파라미터로 가지며 return 값은 없습니다. 
B.	메소드에 `IPrintable` 타입의 `ip` 를 선언합니다.
C.	파라미터 인자로 받은 `item` 객체가 `IPrintable` 이면 객체를 `IPrintable` 타입으로 변환한 후 `print` 메소드를 호출하고 아니면 객체의 `toString` 메소드 호출 결과를 출력합니다.
D.	완성한 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public static void display(Object item) {
    IPrintable printable;
    if (item instanceof IPrintable) {
        printable = (IPrintable)item;
        printable.print();
    } 
    else {
        System.out.println(item.toString());
    }
}
----
+
E.	작업을 저장합니다.

== Display 메소드 테스트

1.	Test.java 파일을 엽니다.
2.	`main` 메소드에서, `Message` 타입 변수 `message` 를 선언하고 "Greetings" 생성 파라미터로 객체를 생성합니다.
3.	위 연습에서 사용한 `number` 변수(Integer 타입)를 파라미터 인자로 `Utilities` 클래스의 display 메소드를 호출합니다.
4.	`message` 변수를 파라미터 인자로 `Utilities` 클래스의 `display` 메소드를 호출합니다.
5.	작업을 저장합니다.
6.	아래 명령을 수행하여 프로그램을 컴파일 합니다.
+
----
> javac *.java
----
+
7.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
> java Test
…
1
Greetings
----

link:./36_interface_casting.adoc[이전: 인터페이스 타입 변환] +
link:./38_review.adoc[다음: 검토]