= 인터페이스의 default 메소드

* 인터페이스는 타입을 선언하며, 일반적으로 타입은 행위(Behavior)로 표현된다
** 인터페이스의 메소드는 구현을 포함하지 않음
** 인터페이스(타입)의 메소드는 인터페이스를 구현하는 서브타입(subtype)에서 구현함
* 인터페이스에 추가적인 동작이 필요할 때
** 타입에서 공통적으로 동작하는 기능이 있음
** 공통적으로 동작하는 기능이라도 인터페이스에 메소드 선언이 추가되면 모든 서브타입 클래스를 수정해야 함
* 인터페이스에 타입에서 공통적인 기능을 메소드로 선언하고 구현(body)을 포함

[source, java]
----
interface InterfaceWithDefaultMethod {
    void aMethod();
    void default Method() { ... }
}
----

---

인터페이스를 사용하여 타입을 선언할 수 있습니다. 타입은 일반적으로 행위(Behavior)로 표현되며, Java에서는 인터페이스를 통해 선언된 타입을 구현하는 클래스에서 인터페이스의 메소드를 각각 구현하도록 하여 다형성을 구현합니다. 따라서, 인터페이스의 서브타입은 인터페이스에 선언된 모든 행위를 수행해야 하며 이는 구현하는 모든 클래스(인터페이스 타입의 서브타입)은 인터페이스에 선언된 모든 메소드를 구현해야 한다는 것을 의미합니다.

선언된 인터페이스에 추가 기능이 필요할 경우, 인터페이스에 메소드를 추가하면 인터페이스를 구현하는 모든 클래스는 인터페이스에 추가된 메소드를 구현해야 합니다. 이는 전체 응용 프로그램의 대규모 수정을 의미할 수 있으며, 확장에는 열려있고 수정에는 닫혀 있어애 하는 객체지향의 기본 원칙을 위반하는 수정이 될 수 있습니다.

C++등 다른 언어보다 '쉬운 언어'를 지행했던 Java에서는 기본 원칙을 지키기 위해 인터페이스는 추상 메소드만을 가지는 것을 허용했으며, Java 8 버전에서 이런 단점을 해결하기 위해 두 가지를 추가했습니다.

1. 인터페이스에 정적 메소드(static method)를 사용할 수 있다.
2. 인터페이스의 기본 구현을 제공할 수 있도록 디폴드 메소드(default method) 사용할 수 있다.

== default method 활용

default 메소드는 선택형 메소드(optional method), 동작 다중 상속(multuple inheritance of behavior) 두 가지 패턴을 사용하여 활용할 수 있습니다.

=== Optional Method 패턴

Java의 Collections Framework에서 제공하는 Iterator 인터페이스에는 remove 메소드가 선언되어 있습니다.

[source, java]
----
// Java 8 이후의 Iterator 인터페이스
public interface Iterator<E> {
    ...

    default void remove() {
        throw new UnsupportdOperationException("remove");
    }
}
----

Java 8 이전의 Iterator 인터페이스에서 remove 인터페이스는 추상 메소드로 선언되었습니다.

반복 읽기를 구현하는 Iterator 인터페이스를 구현하는 객체에서 값을 제거하는 작업은 흔하지 않아, Java 8 이전의 많은 클래스에서는 Iterator를 상속하는 많은 클래스들이 remove() 메소드에 빈 바디를 쓰는 경우가 많았습니다. 

[source, java]
----
// Java 8 이전의 Iterator 인터페이스 구현에서 많은 경우의 클래스
public class CollectionIterator<E> implements Iterator<E> {
    public boolean hasNext() {
        ...
    }

    public E next() {
        ....
    }

    public void move() {

    }
}
----

인터페이스의 default 메소드를 사용하면 사용하지 않는 메소드를 인터페이스에서 default로 구현해 사용하지 않는 클래스에서 구현을 강제할 필요가 없어 불필요한 코드를 줄일 수 있습니다.

=== 기능 중복 배제

아래와 같이, 탈것을 표현하는 추상 클래스가 있고,

[source, java]
----
public abstract class Vehicle {
    int speed;
    Location location;

    void move(Location location) {
        this.location = location;
    }
}
----

출력을 지정하여 가속이 가능한 자동차를 표현하는 SportsCar 인터페이스가 있으며,

[source, java]
----
public interface SportsCar {
    void setOutput(int output);
    int getOutput();
}
----

Vehicle 클래스의 서브 클래스이며, SportsCar 구현하는 Porche 클래스가 있는 경우를 가정해 봅시다.

[source, java]
----
public class Porche extends Vehicle implements SportsCar {
    int output;
    void setOutput(int output) {
        this.output = output;
    }

    int getOutput() {
        return this.output;
    }
}
----

후에 SportsCar 인터페이스에 급가속(Boost) 기능이 포함되어야 하는 경우, 새 메소드를 작성하지 않고 기존의 setOutput 메소드와 getOutput 메소드를 사용하여 메소드를 작성할 수 있습니다. 이런 형식의 메소드를 템플릿 메소드(template method)라고 합니다.

[source, java]
----
public interface SportsCar {
    void setOutput(int output);
    int getOutput();
    default void setBoost() {
        setOutput(getOutput() * 2);
    }
}
----

link:./14_implement_interface_method.adoc[이전: 인터페이스 메소드 구현] +
link:./16_static_method_in_interface.adoc[다음: 인터페이스에서 static 메소드 구현]