= 프로세스 개요

* 실행중에 있는 프로그램을 의미함
* 스케줄링의 대상이 되는 작업(Task)와 같은 의미로 쓰임
* 하드 디스크의 프로그램을 실행하면, 실행을 위해서 메모리 할당이 이루어지고 할당된 메모리 공간으로 바이너리 코드가 적재됨
* 이 순간부터 프로세스라고 불림

---

프로세스(Process)는 컴퓨터에서 연속적으로 실행되고 있는 컴퓨터 프로그램을 말합니다. 종종 스케줄링의 대상이 되는 작업(Task)과 같은 용어로 쓰입니다.

프로그램은 일반적으로 보조 기억 장치에 저장되어 있는 실행 코드를 뜻하고, 프로세스는 프로그램을 구동하여 프로그램 자체와 프로그램의 상태가 메모리상에서 실행되는 작업 단위를 지칭합니다. 하나의 프로그램을 여러 번 실행하면 프로세스가 메모리 상에서 실행됩니다. 프로그램은 명령어 리스트를 내용으로 가진 디스크에 저장된 파일(일반적으로 실행 파일이라고 불리는) 수동적인 존재(Passive entity)이며, 프로세스는 다음에 실행할 명령어를 지정하는 프로그램 카운터와 관련 자원의 집합을 가진 능동적인 존재(Active Entity)입니다. 실행 파일이 메모리에 적재될 때 프로그램은 프로세스가 됩니다.
같은 시간에 여러 개의 프로그램을 실행하는 시분할 방식을 멀티 태스킹이라고 하며, 대부분의 모던 운영체제는 시분할 방식을 지원합니다. 

초기의 컴퓨터 시스템은 한 번에 하나의 프로그램만을 실행하도록 허용하였습니다. 실행된 하나의 프로그램이 시스템을 완전히 제어하고, 시스템의 모든 자원에 접근할 수 있었습니다. 최근의 컴퓨터 시스템들은 메모리에 여러 프로그램이 적재되어 동시에 실행되는 것을 허용합니다. 이는 동시에 실행되는 다양한 프로그램을 보다 견고하게 나누고 제어하는 것을 필요로 했습니다. 이런 필요가 프로세스라는 개념을 낳았습니다. 프로세스는 실행중인 프로그램을 말하며, 프로세스는 현대의 컴퓨팅에서 작업의 단위를 의미합니다.

하나의 시스템은 일부는 사용자 코드를 실행하고 일부는 운영체제 코드를 실행하는 프로세스의 집합체입니다. 모든 프로세스는 동시 실행이 가능하고, CPU는 이 프로세스들에서 다중화됩니다. 

link:./11_프로세스.adoc[다음: 프로세스]