= Lab 17-1: synchronized를 이용한 Thread 동기화

Java는 Thread 동기화를 위한 synchronized 기법을 제공합니다. 이번 연습에서는 synchronize를 사용한 동기화를 연습합니다.

1.	Windows 탐색기에서 c:\Labs\Lab17-1\Starter 폴더를 엽니다. (없으면 생성합니다.)
2.	Visual Studio Code를 실행하고 파일 메뉴에서 폴더 열기를 클릭합니다.
3.	c:\Labs\Lab17-1\Starter 폴더를 선택하고 열기를 클릭합니다.
4.	파일 작성자 신뢰 대화상자에서 예, 작성자를 신뢰합니다 버튼을 클릭합니다.

== 공유 객체 클래스 작성

1.	Visual Studio Code 탐색기에서 새 파일 버튼을 클릭합니다.
2.	파일의 이름이 Calculator.java인 파일을 생성합니다.
3.	아래와 같이 Calculator 클래스를 작성합니다. +
Calculator 클래스는 정수형 변수 memory와 getter를 가지고 있으며, setMemory 메소드에서 memory 변수의 값을 수정한 후 2초간 슬립하고 접근한 Thread의 이름과 memory 값을 출력합니다. 

[source, java]
----
public class Calculator {
    private int memory;

    public int getMemory() {
        return this.memory;
    }

    public void setMemory(int value) {
        this.memory = value;
        try {
            Thread.sleep(2000);
            System.out.println(Thread.currentThread().getName() + ":" + this.memory);
        }
        catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
----

파일을 컴파일 합니다. 오류가 있으면 수정합니다.

== Thread 객체 클래스 작성

1.	Visual Studio Code 탐색기에서 새 파일 버튼을 클릭합니다.
2.	파일의 이름이 User.java인 파일을 생성합니다.
3.	아래와 같이 파일의 이름이 User 인 클래스를 작성합니다.+
User 클래스는 Calculator 타입의 전역 공유 변수 calculator를 가지고 setCalculator 메소드에서 전역 공유 변수 calculator에 Calculator 객체를 할당합니다.

[source, java]
----
public class User extends Thread {
    private Calculator calculator;
    int memory;

    public User(String name, int memory) {
        this.setName(name);
        this.memory = memory;
    }

    public void setCalculator(Calculator calculator) {
        this.calculator = calculator;
    }

    @Override
    public void run() {
        calculator.setMemory(this.memory);
    }
}
----
파일을 컴파일 합니다. 오류가 있으면 수정합니다.

== Thread를 테스트하는 Test 클래스 작성

1.	Visual Studio Code 탐색기에서 새 파일 버튼을 클릭합니다.
2.	파일의 이름이 Test.java인 파일을 생성합니다.
3.	아래와 같이 파일의 이름이 User 인 클래스를 작성합니다. +
Test 클래스는 응용 프로그램 진입점을 가지고, Calculator 타입 객체를 생성합니다. 두 개의 User 타입 객체를 생성한 후 공유 객체인 Calculator 타입 객체 calculator를 두 User 타입에 할당한 후 Thread를 시작합니다.
+
[source, java]
----
public class Test {
    public static void main(String[] args) {
        Calculator calculator = new Calculator();

        User user1 = new User("User 1", 100);
        User user2 = new User("User 2", 50);

        user1.setCalculator(calculator);
        user1.start();

        user2.setCalculator(calculator);
        user2.start();
    }
}
----
+
4. 파일을 컴파일 합니다. 오류가 있으면 수정합니다.
5. 아래 명령을 실행하여 응용 프로그램을 시작합니다.
+
----
% java Test
----
+
6. 실행 결과는 아래와 유사할 것입니다. +
`User1` 객체는 `calculator` 객체의 `memory` 값이 100을, `user2` 객체는 `calculator` 객체의 `memory` 값에 50을 지정했지만 결과는 모두 50으로 출력됩니다.
+
----
% java Test
User 2:50
User 1:50
----

== 임계 구역을 설정하고 Thread 동기화 수행

1.	Calculator.java 파일을 엽니다.
2.	setMemory 메소드를 아래와 같이 수정합니다.
+
[source, java]
----
public synchronized void setMemory(int value) {
    this.memory = value;
    try {
        Thread.sleep(2000);
        System.out.println(Thread.currentThread().getName() + ":" + this.memory);
    }
    catch (InterruptedException e) {
        e.printStackTrace();
    }
}
----
+
3. 아래 명령을 실행하여 Calculator 클래스를 다시 컴파일 합니다.
+
----
% javac Calculator.java
----
+
4. 아래 명령을 실행하여 응용 프로그램을 시작합니다.
+
----
% java Test
User 2:100
User 1:50
----
+
5. 연습이 종료되었습니다.

link:./29_Thread_상태_변화.adoc[다음: Thread 상태 변화]