= 프로세스 제어 블록

* 각 프로세스는 운영체제에서 프로세스 제어 블록(Process Control Block – PCB)으로 표현됨
* 프로세스 제어 블록은 특정 프로세스와 연관된 여러 정보를 수록함
* 프로세스를 시작/재시작 시키는데 필요한 모든 데이터를 위한 저장소 역할

---

프로세스 제어 블록(Process Control Block)은 특정한 프로세스를 관리할 필요가 있는 정보를 포함하는 운영 체제 커널의 자료 구조입니다. 작업 제어 블록(Task Control Block)또는 작업 구조라고도 합니다. 

프로세스 제어 블록은 운영체제에 따라 포함되는 항목이 다를 수 있지만, 일반적으로 다음과 같은 정보가 포함되어 있습니다.

* 프로세스 ID +
운영체제에서 프로세스를 식별할 수 있는 식별자 정보를 포함합니다.
* 프로세스 상태 +
New, Ready, Running, Waiting, Halted 등의 프로세스 상태 정보를 포함합니다.
* 프로그램 카운터 +
프로세스가 다음에 실행할 명령어의 주소를 가리킵니다.
* CPU 레지스터 +
CPU 레지스터는 누산기, 데이터 레지스터, 주소 레지스터, 범용 레지스터 등 컴퓨터의 구조에 따라 다양한 수와 유형을 가집니다. 레지스터에는 상태 코드(State Code)가 포함되며, CPU 레지스터는 프로세스가 다시 스케줄링 될 때 계속 바르게 실행되도록 하기 위하여 인터럽트 발생시 저장되어야 합니다.
+ CPU 스케줄링 정보 +
프로세스의 우선순위, 스케줄링 큐에 대한 포인터와 스케줄링 파라미터를 포함합니다.
+ 메모리 관리 정보 +
운영체제에 의해 사용되는 메모리 시스템에 따라 기준 레지스터와 한계 레지스터의 값, 페이지 테이블 또는 세그먼트 테이블 등과 같은 정보를 포함합니다.
* 어카운팅 정보 +
CPU 사용 시간과 경과된 시간, 시간 제한, 프로세스 번호 등을 포함합니다.
* 입출력 상태 정보 +
프로세스에 할당된 입출력 장치들과 열린 파일의 목록을 포함합니다.

link:./14_프로세스간_통신.adoc[다음: 프로세스간 통신]