= 프로세스와 Thread

* 하나의 프로세스는 여러 개의 Thread로 구성 가능
* 하나의 프로세스를 구성하는 Thread는 프로세스에 할당된 
* 각 Thread별로 Stack과 Register를 가지고 있음
* 한 번에 하나의 Thread만 실행 가능

---s

== 프로세스와 Thread

프로세스는 운영체제로부터 자원을 할당 받은 작업의 단위이며 Thread는 프로세스가 할당받은 자원을 이용하는 실행 단위입니다. 프로세스는 실행 중인 프로그램으로 디스크로부터 메모리에 적재되어 CPU의 할당을 받을 수 있는 것으로 의미합니다. 그러므로 프로세스를 생성한다는 것은 많은 시간과 자원을 필요로 합니다.

Thread는 프로세스 내의 실행단위라고 할 수 있습니다. 한 프로세스 내에서 동작하는 여러 실행 흐름으로 프로세스 내의 주소 공간이나 자원을 공유할 수 있습니다. 각각 Thread는 독립적인 작업을 수행함으로 각자의 stack과 pc register 값을 가지고 있습니다
 
== Thread의 특징

* 독립된 Stack +
stack은 method 호출 시 전달되는 인자, 되돌아갈 주소값 등을 저장하기 위해 사용되는 메모리 공간입니다. 즉 stack 메모리가 독립적으로 동작함으로써 독립적인 함수 호출이 가능하며 독립적인
실행 흐름을 가져갈 수 있습니다.
* 독립적인 할당 PC Resister +
Resister 값은 thread 명령어의 어디까지 수행했는지를 기억하고 있습니다. thread는 CPU를 할당받았다가 스케줄러에 의해서 다시 선점당하게 됩니다. 그렇기 때문에 명령이 연속적으로 수행되지 못하고 일정 부분 수행 후 다시 수행하기 위해서 어느 부분까지 수행했는지 기억해야 합니다. 그래서 PC Resister를 독립적으로 할당합니다. +
+
프로세스 내의 Thread들은 프로세스처럼 독립적이지 않습니다. 모든 Thread는 똑 같은 전역 변수를 공유하고 있음을 뜻하는 똑 같은 주소 공간을 갖습니다. 각 Thread가 프로세스 주소 공간에서 메모리 주소를 액세스 할 수 있기 때문에 Thread는 읽기 쓰기가 가능하며 심지어는 다른 Thread의 스택까지도 지워버릴 수 있습니다. Thread 간에는 보호가 불가능하고 실제로 필요 없기 때문에 어떤 보호 기능도 존재하지 않습니다.

link:./22_Thread의_장점.adoc[다음: Thread의 장점]