= Thread의 장점

* 응답성 (Responsiveness) +
응용 프로그램의 일부분이 봉쇄되거나, 긴 작업을 수행하더라도 프로그램의 수행이 계속되는 것을 허용함
* 자원 공유(Resource Sharing) +
프로세스와 달리, 명시적으로 공유가 처리되지 않아도 자동으로 자원을 공유함
* 경제성(Economy) +
프로세스의 생성보다 시간과 자원을 덜 소모함
* 규모 적응성(Scalability) +
각각의 Thread가 다른 처리기에서 병렬로 수행될 수 있음

---

Multi Thread 프로그래밍의 이점은 아래와 같이 4가지로 생각할 수 있습니다.

* 응답성(Responsiveness) +
대화형 응용 프로그램을 다중 Thread화하면 응용 프로그램의 일부분이 봉쇄되거나, 응용 프로그램이 긴 작업을 수행하더라도 프로그램의 수행이 계속되는 것을 허용함으로써 사용자에 대한 응답성을 증가시킵니다. 이 특징은 사용자 인터페이스를 설계하는데 있어서 특히 유용합니다. 예를 들어 사용자가 시간이 많이 걸리는 연산을 시작하는 단추를 클릭했을 때 어떻게 되는지 생각해 봅시다. 단일 Thread 응용은 그 연산이 완료될 때까지 사용자에게 응답하지 않습니다. 대조적으로 시간이 오래 걸리는 연산이 비동기적 Thread에서 실행된다면 응용은 여전히 사용자에게 응답할 수 있습니다.
* 자원 공유(Resource Sharing) +
프로세스는 공유 메모리에서 메시지 전달 기법을 통해서만 자원을 공유할 수 있습니다. 이런 기법은 프로그래머에 의해 명시적으로 처리되어야 합니다. Thread는 자동으로 그들이 속한 프로세스의 자원들과 메모리를 공유합니다. 코드와 데이터 공유의 이점은 한 응용 프로그램이 같은 주소 공간 내에 여러 개의 작업을 하는 Thread를 가질 수 있습니다.
* 경제성(Economy) +
프로세스 생성을 위해 메모리와 자원을 할당하는 것은 비용이 많이 듭니다. Thread는 자신이 속한 프로세스의 자원들을 공유하기 때문에, Thread를 생성하고 컨텍스트를 교환하는 것이 더 경제적입니다. 일반적으로 Thread의 생성은 프로세스의 생성보다 시간과 메모리를 덜 소모합니다. 또한 컨텍스트 스위칭은 일반적으로 프로세스 사이에서 보다 Thread드 사이에서 다 빠릅니다.
* 규모 적응성(Scalability) +
다중 Thread의 이점은 멀티 프로세서 구조에서 더욱 증가할 수 있습니다. 멀티 프로세서 구조에서는 각각의 Thread가 다른 프로세서에서 병렬로 실행될 수 있기 때문입니다. 단일 Thread 프로세스는 프로세서가 아무리 많더라도 한 프로세서에서만 처리됩니다.

link:./23_Java_Thread_프로그래밍.adoc[다음: Java Thread 프로그래밍]