= 객체(Object)란?

* 클래스의 인스턴스
* 객체의 세 가지 특징:
** identity(ID): 한 객체는 다른 객체와 구분될 수 있음
** Behavior(행위): 객체는 작업을 수행함
** State(상태): 객체는 상태를 포함함

---

자동차라는 단어는 일반적으로 바퀴와 엔진, 핸들을 가진 탈것을 의미하는 용어로 사용됩니다. 자동차라는 단어는 거의 모든 사람이 알고 있고 그 의미에 동의합니다. “자동차”라고 하면 보통 그 탈것의 일반적인 개념을 이야기합니다. 하지만 “내 차”라고 하면 바퀴와 엔진, 핸들을 가진 탈것에 대한 개념을 의미하지 않습니다. “내 차”라고 한다면 자동차라는 단어가 의미하는 개념을 이용해서 공장 등에서 만들어진 실제적으로 탑승하여 운전할 수 있는 만져질 수 있는 차를 의미합니다. 프로그래머는 객체(object) 또는 인스턴스(instance)라는 용어를 사용하여 특정 차를 나타냅니다. 이 차이는 매우 중요합니다.

Identity(ID), Behavior(행동), State(상태)이 세 가지 특성과 객체의 관계를 이해하면 객체가 무엇인지 이해할 수 있습니다.

**Identity(ID)** +
Identity는 한 객체를 같은 클래스에서 인스턴스화 된 다른 객체와 구별하는 특성입니다. 자동차 회사는 자동차를 생산하기 위해 설계도를 만들고, 설계도 대로 똑 같은 자동차를 생산합니다. 같은 아파트에 사는 두 사람이 2015년형 현대 아반떼를 구입한 경우를 생각해봅시다. 두 차는 동일한 종류의 자동차이지만 등록번호는 각 차가 고유한 것으로 보장됩니다. 자동차 등록 번호는 자동차의 유일성을 보장합니다. 법적으로도 두 자동차는 구별되어야 한다고 규정합니다. 2015년 현대 아반떼는 950,000대가 넘게 판매되었지만, 모든 차는 유일성이 보장됩니다.

**Behavior (행위)** +
Behavior는 객체를 사용할 수 있게 만드는 특징입니다. 객체는 Behavior를 제공하기 위해 존재합니다. 자동차가 유용한 이유는 달릴 수 있기 때문입니다. Behavior는 액세스 할 수 있는 객체의 행위이며, 객체의 행위는 객체를 분류할 수 있는 강력한 도구입니다. 같은 클래스의 객체는 같은 행위를 가집니다. 자동차는 운전할 수 있으므로 자동차로 분류됩니다.

**State (상태)** +
상태는 정의된 행위를 제공하도록 할 수 있는 객체 내부의 일들을 나타냅니다. 이는 추상화의 개념과 밀접하게 연결되어 있습니다. 자동차를 운전할 때, 속도를 높이기 위해 액셀러레이터를 밟지만 어떻게 가속되는지 신경 쓰지 않습니다. 액셀러레이터를 밟으면 속도가 올라갑니다. 속도는 자동차의 상태 중 하나이지만 그 상태가 어떻게 변화하는지는 숨겨져 있습니다. 두 객체는 우연히 같은 상태를 가질 수 있지만 분명히 다른 객체입니다. 쌍둥이는 정확히 같은 상태(DNA)를 포함하지만 명백히 다른 사람입니다.

link:./03_class.adoc[이전: 클래스(class)란?] +
link:./05_abstraction.adoc[다음: 추상화(Abstraction)]