= Lab 7-1 : 클래스를 만들고 사용

== 연습 1: 클래스의 생성과 사용

이 연습에서는 은행 계좌 클래스를 생성합니다. 데이터 멤버를 private으로 선언하고, 데이터에 액세스 하는 public 메소드를 선언합니다. 계정 객체를 생성하고, 사용자가 지정한 계정 번호와 잔고를 채우는 여러 메소드를 만들고, 데이터를 출력합니다.

=== BankAccount 클래스 정의

1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab7-1\CreateAccount\Starter 폴더를 엽니다.
3.	작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 BankAccount.java 파일을 엽니다.
5.	코드를 확인합니다. `BankAccount` 클래스와 `CreateAccount` 두 클래스가 있습니다.
6.	터미널 메뉴에서 새 터미널을 클릭하고 BankAccount.java 파일을 컴파일합니다. 컴파일에 실패합니다.
+
----
BankAccount.java:13: error: variable newAccount might not have been initialized
----
+
7.	`CreateAccount` 클래스의 `createNewBankAccount` 정적 메소드에서 코드를 아래와 같이 수정합니다.
+
[source, java]
----
public static BankAccount createNewBankAccount(String accountNumber, String ownerName, BigDecimal balance) {
    BankAccount newAccount = new BankAccount();
            
    newAccount.accountNumber = accountNumber;
    newAccount.ownerName = ownerName;
    newAccount.balance = balance;

    return newAccount;
}
----
+
8.	`CreateAccount` 클래스의 `main` 메소드의 주석을 해제합니다.
9.	BankAccount.java 파일을 다시 컴파일합니다. 오류가 있으면 수정합니다.
10.	아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 1
Owner Name: Vesper Lind
Balance: 0.0
----

=== BankAccount 클래스 캡슐화

1.	BankAccount 클래스에서 모든 데이터 멤버는 public으로 선언되어 있습니다. BankAccount 클래스의 모든 멤버의 접근 제한자를 아래와 같이 private으로 변경합니다.
+
[source, java]
----
public class BankAccount {
    private long accountNumber;
    private String ownerName;
    private BigDecimal balance;

    …
}
----
+
2.	BankAccount.java 프로그램을 컴파일 합니다. 오류가 발생합니다.
+
----
BankAccount.java:19: error: accountNumber has private access in BankAccount
----
+
[source, java]
----
public static BankAccount createNewBankAccount(String accountNumber, String ownerName, BigDecimal balance) {
    BankAccount newAccount = new BankAccount();
            
    newAccount.accountNumber = accountNumber;	// 오류 발생
    newAccount.ownerName = ownerName;		    // 오류 발생
    newAccount.balance = balance;		        // 오류 발생

    return newAccount;
}
----
+
3.	`BankAccount` 의 멤버에 데이터를 할당하는 코드는 데이터 멤버가 `private` 이기 때문에 실패합니다. `BankAccount` 클래스 내의 메소드만 `BankAccount` 데이터 멤버에 액세스 할 수 있습니다. `BankAccount` 클래스의 멤버에 값을 할당하려면 `public` 메소드를 `BankAccount` 클래스에 작성해야 합니다. 다음 단계를 수행합니다.
A.	`BankAccount` 에 `SetData` 라는 `public` 메소드를 작성합니다.
B.	`SetData` 메소드의 반환 타입은 `void` 이며 `String` 타입의 `accountNumber`, `String` 타입의 `ownerName`, `BigDecimal` 타입의 `balance` 를 파라미터로 가집니다.
C.	메소드의 바디 블록에는 각 파라미터를 각 클래스 변수에 할당합니다.
+
완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public void setData(long accountNumber, String ownerName, BigDecimal balance) {
    this.accountNumber = accountNumber;
    this.ownerName = ownerName;
    this.balance = balance;
}
----
+
4.	`CreateAccount` 클래스의 `createNewAccount` 메소드에서 클래스의 멤버에 값을 할당하는 코드를 주석처리하고 `createNewAccount` 메소드에서 전달받은 파라미터를 인자로 `setData` 메소드를 호출하여 `BankAccount` 객체에 데이터를 할당하는 코드를 작성합니다. 코드는 아래와 유사할 것입니다:
+
[source, java]
----
BankAccount newAccount = new BankAccount();

//newAccount.accountNumber = accountNumber;
//newAccount.ownerName = ownerName;
//newAccount.balance = balance;

newAccount.setData(accountNumber, ownerName, balance);
----
+
5.	작업을 저장합니다.
6.	BankAccount.java 프로그램을 컴파일 합니다. 여전히 오류가 발생합니다. `CreateAccount` 클래스의 `printAccount` 메소드는 여전히 객체 멤버를 참조하고 있기 때문입니다. 각 필드의 값을 외부에서 볼 수 있게 하는 세 메소드를 작성해야 합니다. 아래 절차에 따릅니다.
A.	`BankAccount` 클래스에 `getNumber` 라는 이름의 동적 메소드를 작성합니다. 이 메소드는 파라미터가 없으며 `long` 타입인 `accountNumber` 를 반환합니다. 
B.	`BankAccount` 클래스에 `getOwnerName` 이라는 이름의 동적 메소드를 작성합니다. 이 메소드는 파라미터가 없으며 String 타입인 `ownerName` 을 반환합니다.
C.	`BankAccount` 클래스에 `getBalance` 라는 이름의 동적 메소드를 작성합니다. 이 메소드는 파라미터가 없으며 BigDecimal 타입인 `balance` 를 반환합니다.
+
완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public long getNumber() {
    return this.accountNumber;
}

public String getOwnerName() {
    return this.ownerName;
}

public BigDecimal getBalance() {
    return this.balance;
}
----
+
7.	`CreateAccount` 클래스의 `printAccount` 메소드가 `BankAccount` 클래스에 작성한 public 메소드를 호출하도록 수정합니다. 완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public static void printBankAccount(BankAccount account) {
    System.out.println("Account Number: " + account.getNumber());
    System.out.println("Owner Name: " + account.getOwnerName());
    System.out.println("Balance: " + account.getBalance());
}
----
+
8.	작업을 저장합니다.
9.	BankAccount.java 파일을 컴파일 하고 오류가 있으면 수정합니다.
10.	아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 1
Owner Name: Vesper Lind
Balance: 0.0
----
+
11.	Visual Studio Code를 닫습니다.

== 연습 2: 계좌 번호 생성

이 연습에서는 이전 연습의 `BankAccount` 클래스를 수정하여 고유한 계좌번호를 생성합니다. `BankAccount` 클래스에 정적 변수를 추가하고 변수의 값을 증가시키고 반환하는 메소드를 작성합니다. `CreateAccount` 클래스에서 새 계정을 생성할 때 메소드를 호출하여 계좌 번호를 생성합니다.

1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab07-1\AccountNumbers\Starter 폴더를 엽니다.
3.	작성자 신뢰 경고 창에서, _예, 작성자를 신뢰합니다_ 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 BankAccount.java 파일을 엽니다.
5.	`BankAccount` 클래스에, 아래와 같이 private static long `nextAccountNo` 변수를 선언합니다. 
+
[source, java]
----
public class BankAccount {
    private long accountNumber;
    private String ownerName;
    private BigDecimal balance;

    private static long nextAccountNumber;
    …
}
----
+
6.	`BankAccount` 클래스에 `nextNumber` 메소드를 public static으로 선언합니다. 이 메소드는 파라미터가 없고 long 타입인 `nextAccountNumber` 정적 변수에 1을 더한 값을 반환합니다.
+
[source, java]
----
public class BankAccount {
    private long accountNumber;
    private String ownerName;
    private BigDecimal balance;

    private static long nextAccountNumber;

    public static long nextNumber() {
        return nextAccountNumber++;
    }
    …
}
----
+
7.	`CreateAccount` 클래스의 `createNewBankAccount` 메소드에서 첫 번째 파라미터(long 타입의 accountNumber)를 삭제합니다.
8.	`CreateAccount` 클래스의 `createNewBankAccount` 메소드에 long 타입 `accountNumber` 를 선언하고 `BankAccount` 클래스의 `nextNumber` 정적 메소드 호출 반환값을 할당합니다.
9.	완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public static BankAccount createNewBankAccount(String ownerName, BigDecimal balance) {
    BankAccount newAccount = new BankAccount();
    long accountNumber = BankAccount.nextNumber();
    newAccount.setData(accountNumber, ownerName, balance);

    return newAccount;
}
----
+
10.	`main` 메소드의 코드를 확인합니다. `createNewBankAccount` 메소드를 호출할 때 계좌 번호를 입력 받지 않으며, 두 개의 계좌를 생성합니다.
11.	작업을 저장합니다.
12.	BankAccount.java 파일을 컴파일 하고 오류가 있으면 수정합니다.
13.	아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 0
Owner Name: Vesper Lind
Balance: 0.0
Account Number: 1
Owner Name: Celine
Balance: 0.0
----

=== BankAccount 클래스에 캡슐화 기능 강화

1.	`BankAccount` 클래스의 `setData` 메소드에서 첫 번째 파라미터(long 타입의 accountNumber)를 삭제하고, `accountNumber` 변수에 정적 메소드 `nextNumber` 호출 반환값을 할당합니다.
+
[source, java]
----
public void setData(String ownerName, BigDecimal balance) {
    this.accountNumber = nextNumber();
    this.ownerName = ownerName;
    this.balance = balance;
}
----
+
2.	`BankAccount` 클래스의 정적 메소드 `nextNumber` 의 접근 제한자를 `private` 으로 변경합니다.
+
[source, java]
----
public class BankAccount {
    …
    private static long nextAccountNumber;

    private static long nextNumber() {
        return nextAccountNumber++;
    }
    ...
}
----
+
3.	`CreateAccount` 클래스의 `createNewBankAccount` 메소드에 작성한 `accountNumber` 변수에 값을 할당하는 코드를 주석 처리하고 `setData` 메소드를 호출하는 코드의 첫 번째 파라미터를 삭제합니다.
+
[source, java]
----
public static BankAccount createNewBankAccount(String ownerName, BigDecimal balance) {
    BankAccount newAccount = new BankAccount();
    //long accountNumber = BankAccount.nextNumber();
    newAccount.setData(ownerName, balance);
    …
}
----
+
4.	작업을 저장합니다.
5.	BankAccount.java 파일을 컴파일 하고 오류가 있으면 수정합니다.
6.	아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 0
Owner Name: Vesper Lind
Balance: 0.0
Account Number: 1
Owner Name: Celine
Balance: 0.0
----
+
7.	Visual Studio Code를 닫습니다.

== 연습 3: public 메소드 추가

이 연습에서는 `BankAccount` 클래스에 `withDraw` 와 `deposit` 두 메소드를 추가합니다. 

`withDraw` 메소드는 `BigDecimal` 파라미터를 사용하고 `balance` 에서 주어진 금액을 공제합니다. 계정의 잔고보다 많은 금액이 출금되면 안되므로, 인출이 가능한지 여부를 먼저 체크하고, 인출이 성공했는지 여부를 나타내는 `boolean` 값을 반환합니다.

`deposit` 메소드는 역시 `BigDecimal` 파라미터를 사용하고 `balance` 에 값을 더합니다. 메소드는 새 `balance` 값을 반환합니다.

=== BankAccount 클래스에 deposit 메소드 추가
1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab07-1\MoreMethods\Starter 폴더를 엽니다.
3.	작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 BankAccount.java 파일을 엽니다.
5.	`BankAccount` 클래스에 `deposit` 메소드를 추가합니다. 이 메소드는 동적이며, `BigDecimal` 파라미터를 받아 클래스 멤버 `balance` 에 값을 더하고 새 값을 반환합니다. 코드는 아래와 같이 됩니다:
+
[source, java]
----
public class BankAccount {
    …
    public BigDecimal deposit(BigDecimal amount) {
        this.balance = this.balance.add(amount);
        return this.balance;
    }
    …
}
----
+
6.	`CreateAccount` 클래스에 `TestDeposit` 메소드를 추가합니다. `TestDeposit` 메소드는 값을 반환하지 않으며, 콘솔에서 입금할 값을 입력 받아 `deposit` 메소드를 호출하여 입금을 완료합니다. 코드는 아래와 같이 됩니다:
+
[source, java]
----
class CreateAccount {
    …
    public static void TestDeposit(BankAccount account) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter amount to deposit: ");
        BigDecimal amount = new BigDecimal(scanner.next());
        account.deposit(amount);
        scanner.close();
    }
    …
}
----
+
7.	`main` 메소드에서 두 계좌에 값을 입금하고, 입금 전과 입금 후 계좌의 데이터를 출력하는 코드를 작성합니다.
+
[source, java]
----
class CreateAccount {
    …

    public static void main(String[] args) {
        BankAccount bankAccount = CreateAccount.createNewBankAccount("Vesper Lind", new BigDecimal("0.0"));
        printBankAccount(bankAccount);
        TestDeposit(bankAccount);
        printBankAccount(bankAccount);

        BankAccount bankAccount2 = CreateAccount.createNewBankAccount("Celine ", new BigDecimal("0.0"));      
        printBankAccount(bankAccount2);
        TestDeposit(bankAccount2);
        printBankAccount(bankAccount2);
    }
    …
}
----
+
8.	작업을 저장합니다.
9.	BankAccount.java 파일을 컴파일 하고 오류가 있으면 수정합니다.
10.	아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 0
Owner Name: Vesper Lind
Balance: 0.0

Enter amount to deposut: 100
Account Number: 0
Owner Name: Vesper Lind
Balance: 100.0

Account Number: 1
Owner Name: Celine
Balance: 0.0

Enter amount to deposut: 35
Account Number: 1
Owner Name: Celine
Balance: 35.0
----

=== BankAccount 클래스에 withDraw 메소드 추가

1.	아래 코드와 같이 `BankAccount`` 클래스에 `withDraw`` 메소드를 작성합니다. 이 메소드는 `BigDecimal` 파라미터를 전달받아 잔고보다 적은지를 확인한 후, 값이 잔고보다 크거나 같으면(즉, 출금이 불가능하면) `false` 를 반환하고 값이 잔고보다 적으면 잔고에서 요청한 값을 뺀 후 `true` 를 반환합니다. 코드는 아래와 같습니다:
+
[source, java]
----
public boolean withDraw(BigDecimal amount) {
    if (amount.compareTo(this.balance) == 1 || amount.compareTo(this.balance) == 0) {
        return false;
    }
    else {
        balance = balance.subtract(amount);
        return true;
    }
}
----
+
2.	`CreateAccount` 클래스에 `testWithDraw` 메소드를 작성합니다. 이 메소드는 값을 반환하지 않으며 하나의 `BankAccount` 타입을 파라미터로 받습니다. 콘솔에서 입금할 값을 입력 받아 `withDraw` 메소드를 호출하여 입금을 완료합니다. 입력한 값이 잔고보다 많아 출금이 불가능한 경우에는 "Insufficient funds!"를 출력합니다.
+
[source, java]
----
class CreateAccount {
    …
    public static void TestWithDraw(BankAccount account) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter amount to withdraw: ");
        BigDecimal amount = new BigDecimal(scanner.next());
        if(!account.withDraw(amount)) {
            System.out.println("Insufficient funds!");
        }
    }
    …
}
----
3.	`CreateAccount` 클래스의 `main` 메소드에 `TestWithDraw` 메소드를 호출하여 계좌의 값을 출력하는 테스트 코드를 작성합니다. 출금 전과 출금 후 계좌의 데이터를 출력합니다.
+
[source, java]
----
public static void main(String[] args) {
    BankAccount bankAccount = CreateAccount.createNewBankAccount("Vesper Lind", new BigDecimal("0.0"));
    printBankAccount(bankAccount);
    TestDeposit(bankAccount);
    printBankAccount(bankAccount);
    TestWithDraw(bankAccount);
    printBankAccount(bankAccount);

    BankAccount bankAccount2 = CreateAccount.createNewBankAccount("Celine ", new BigDecimal("0.0"));      
    printBankAccount(bankAccount2);
    TestDeposit(bankAccount2);
    printBankAccount(bankAccount2);
    TestWithDraw(bankAccount2);
    printBankAccount(bankAccount2);
}
----
+
4.	작업을 저장합니다.
5.	BankAccount.java 파일을 컴파일 하고 오류가 있으면 수정합니다.
6.	실행을 확인합니다.

link:./18_access_nested_class.adoc[이전: 포함된 클래스에 접근] +
link:./20_oo_system.adoc[다음: 객체지향 시스템 정의]