= Java 프로그래밍 언어

* Sun Microsystems의 제임스 고슬링(James Gosling)이 1995년 개발한 객체 지향 언어
* C/C++와는 다르게 처음부터 객체 지향 언어로 개발됨
* Java 프로그래밍 언어의 5가지 핵심 목표
** 객체 지향 방법론을 사용해야 한다.
** 같은 프로그램(바이트코드)이 여러 운영체제(마이크로프로세서)에 탑재되어야 한다.
** 컴퓨터 네트워크 접근 기능이 기본적으로 탑재되어 있어야 한다.
** 원격 코드를 안전하게 실행할 수 있어야 한다.
** 다른 객체 지향 언어들의 좋은 부분만 가지고 와서 사용하기 편해야 한다.

[source, mermaid]
----
graph LR
    A[Java Source Code] --> B[Java Virtual Machine]
    B --> C[실행]
----

---

Java는 Sun Microsystems의 제임스 고슬링과 연구원들이 개발해 1995년 발표한 객체 지향 프로그래밍 언어입니다. 처음에는 가전제품 내에 탑재해 동작하는 프로그램을 위해 개발했지만 현재 전체적으로 가장 많이 사용하는 프로그래밍 언어중의 하나가 되었으며 모바일 기기용 응용 프로그램 개발에도 많이 사용됩니다.

Java는 C에서 진화한 C\++와는 다르게 초기 설계부터 객체 지향 언어로 설계되었으며, 같은 코드로 어떤 마이크로프로세서에서나 실행되는 것을 목표로 했습니다. 이 결과로 Java 소스코드를 컴파일하면 Java 실행 코드인 바이트코드가 생성되며, 생성된 바이트코드는 Java 가상 머신에 의해 실행됩니다. C/C++ 코드로 작성되어 중간 실행 과정이 없는 네이티브 프로그램보다는 실행속도가 느리지만, 같은 코드로 다양한 플랫폼이나 운영체제에서 실행될 수 있다는 장점이 있습니다.

Java의 개발사인 Sun Microsystems는 자바를 GPL 라이선스로 오픈하였으며, 대부분의 코어 부분을 오픈하였습니다. 2009년 Sun Microsystems가 Oracle과 인수 합병됨에 따라 Java에 대한 권리 및 유지보수는 Oracle이 가지고 있습니다.


link:./03_java_software_platform.adoc[이전: Java 소프트웨어 플랫폼] +
link:./05_write_once_run_anywher.adoc[다음: Write Once Run Anywhere]