= Decomposition(분해)과 Abstraction(추상화)

* Decomposition(분해)
** 큰 문제를 해결하기 위한 기본 패러다임: 분할과 정복(Divide and Conquer)
** 간단하고 잘 정의된 방식으로 서로 상호작용하는 작은 프로그램을 만드는 것
** 다음과 같은 방식으로 분리 가능한 하위 문제로 분해
*** 각 하위 문제는 동일한 세부 수준에 있음
*** 각 하위 문제는 독립적으로 해결할 수 있음
*** 하위 문제에 대한 솔루션을 결합하여 원래 문제를 해결할 수 있음
* Abstraction(추상화)
** 고려할 세부 수준을 변경하여 분해를 생산적으로 수행하는 방법
** 문제를 더 간단한 문제로 변환하기 위해 특정 세부 사항을 무시하는데 동의
** 프로그램 설계 프로세스의 전형
** 분해를 위한 구성요소의 좋은 선택

---

== Decomposition(분해)
큰 문제를 해결하기 위한 기본적인 패러다임은 **분할과 정복(Divide and Conquer)**입니다. 여기서 중요한 것은 문제를 나누는 방법을 정확히 선택하는 것입니다.

문제 분할의 목표는 간단하고 잘 정의된 방식으로 서로 상호작용하는 작은 프로그램인 모듈을 만드는 것입니다. 이 목표가 이루어지면 작업에 참여하는 프로그래머가 많은 의사 소통 없이 독립적으로 작업할 수 있으며, 그 결과로 모듈은 함께 동작하게 만들 수 있습니다. 또한 프로그램 수정 및 유지 관리 중에 다른 모듈에 영향을 주지 않고 모듈을 수정할 수 있습니다.

문제를 분할할 때, 다음과 같은 원칙을 사용합니다:
* 각 하위 문제는 동일한 세부 수준에 있습니다.
* 각 하위 문제는 독립적으로 해결할 수 있습니다.
* 하위 문제에 대한 솔루션을 결합하여 원래의 문제를 해결할 수 있습니다.

분해는 많은 분야에서 유용한 기술이며, 사용되어왔습니다. 그러나 분해는 만병 통치약이 아니며 제대로 사용하지 못하면 해로운 영향을 끼칠 수 있습니다. 문제가 제대로 이해되지 못하면 제대로 분해하기 어렵습니다. 가장 일반적인 문제는 명시된 하위 문제를 해결하지만 원래 문제를 해결하기 위해 결합하지 않는 개별 구성 요소를 만드는 것입니다.

== Abstraction(추상화)
추상화는 고려할 세부 수준을 변경하여 분해를 생산적으로 수행하는 방법입니다. 문제를 추상화할 때 원래 문제를 더 간단한 문제로 변환하기 위해 특정 세부사항을 무시하는데 동의합니다.


추상화하고 분해하는 패러다임은 프로그램 설계 프로세스의 전형입니다. 분해는 원래 문제를 해결하기 위해 결합할 수 있는 구성요소로 소프트웨어를 나누는 데 사용됩니다. 추상화는 구성 요소의 좋은 선택을 표시하는데 도움이 됩니다. 원래 문제의 해결 방법을 이미 알고 있는 일련의 문제로 축소할 때까지 두 프로세스를 번갈아 가며 진행합니다.

link:./01_abstraction.adoc[이전: Abstraction] +
link:./03_introduction_abstraction.adoc[다음: Abstraction 개요]