= Lab 10-2: ArrayList와 LinkedList 구현

List는 여러개의 객체 또는 데이터를 포함할 수 있는 객체를 의미하며, 일반적으로 포함할 수 있는 객체 또는 데이터의 수가 동적으로 조절됩니다. Java에서 기본으로 제공되는 자료구조인 배열과 달리, 요소를 추가하거나 제거할 때 배열의 크기를 자동으로 조정할 수 있여 유연하게 데이터를 관리할 수 있습니다.

이 연습에서는 아래와 같은 두 가지 형태의 List를 만듭니다.

* 객체 또는 데이터를 저장하는 자료구조로 배열을 사용하는 ArrayList
* 객체 또는 데이터를 저장하는 노드 객체를 만들고 노드 객체의 연결로 데이터를 관리하는 LinkedList

== Java 응용 프로그램 생성

1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab10-2\Starter 폴더를 엽니다.
3.	작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 Adder.java 파일을 열고 코드를 확인합니다.

== 연습 1: ArrayList 작성

이 연습에서는 객체 또는 데이터를 저장하는 자료구조로 배열을 사용하는 ArrayList 클래스를 작성합니다. 아래 절차에 따릅니다.

=== List 인터페이스 확인

미리 작성되어 있는 List 인터페이스는 타입으로서 List의 동작을 정의합니다. 여기에서 List는 요소를 추가하고, 파라미터로 전달받은 index 값에 해당하는 위치의 요소를 return하며, 파라미터로 전달받은 요소를 삭제하고, List가 포함하고 있는 요소의 개수를 return하는 동작을 수행합니다.

List.java 파일을 열고 List 인터페이스를 확인합니다. 

[source, java]
----
public interface List {
    void add(Object item);
    Object get(int index);
    void remove(int index);
    int size();
}
----

=== ArrayList 클래스 작성

==== List 인터페이스 상속

1. 탐색기에서, ArrayList.java 파일을 클릭해서 엽니다.
2. ArrayList 클래스에 선언되어 있는 Object 배열 element와 정수형 필드 index를 확인합니다. index 변수는 0으로 초기화됩니다.
3. ArrayList 선언에서, ArrayList 클래스가 List 인터페이스를 상속하도록 선언합니다.
4. 코드는 아래와 같이 작성될 것입니다.
+
[source, java]
----
public class ArrayList implements List {
    private Object[] elements;
    private int index = 0;

    //
    // To-do: Add Constructor here
    //

    //
    // To-do Add overloaded constructor here
    //

    //
    // To-do: add add method here
    //

    //
    // To-do: add get method here
    //

    //
    // To-do: add remove method here
    //

    // 
    // To-do: add size method here
    //

    public boolean isEmpty() {
        return this.index == 0 ? true : false;
    }
}
----

==== 생성자 작성

ArrayList 생성자는 ArrayList 클래스의 필드로 선언된 Object 배열을 인스턴스화 합니다. ArrayList 클래스는 두 개의 오버로드된 생성자를 가집니다. 

첫 번째 생성자는 기본 생성자로, Object 배열을 10개의 원소를 가진 배열로 생성하며, 두 번째 생성자는 정수를 파라미터로 받아 파라미터로 받은 정수 만큼 크기의 배열을 생성합니다. 아래 절차에 따릅니다.

1. 첫 번째 생성자를 추가합니다. 생성자는 기본 생성자를 오버라이드하며, elements 배열을 10개의 크기로 초기화합니다.
2. 두 번째 생성자를 추가합니다. 두 번째 생성자는 파라미터로 정수형 size를 가지며, elements 배열은 size 변수 만큼의 크기로 초기화됩니다.
3. 작성한 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public class ArrayList implements List {
    Object[] elements;
    private int index = 0;

    public ArrayList() {
        this.elements = new Object[10];
    }

    public ArrayList(int size) {
        this.elements = new Object[size];
    }

    ...
}
----

==== add 메소드 구현

add 메소드는 Object 타입 객체를 파라미터로 받아 ArrayList 객체의 elements 배열에 추가합니다. 아래 절차에 따릅니다.

1. public 접근 제한자를 가지고, return 타입은 void 이며, Object 타입 파라미터 item을 받는 add 메소드를 선언합니다.
2. 파라미터로 받은 item 객체를 elements 배열의 index 번째 요소에 할당하는 코드를 작성합니다.
3. index 변수를 1 만큼 증가시키는 코드를 작성합니다.
4. 완성된 add 메소드의 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public void add(Object item) {
    this.elements[this.index] = item;
    this.index++;
}
----

==== get 메소드 구현

get 메소드는 정수형 index 파라미터를 가지며, elements 배열에서 해당 파라미터 번째에 해당하는 원소를 return 합니다. 아래 절차에 따릅니다.

1. public 접근 제한자를 가지고, return 타입은 Object 이며, 정수형 파라미터 index를 받는 get 메소드를 작성합니다.
2. elements 배열에서 파라미터로 받은 index에 해당하는 요소를 return 하는 코드를 작성합니다.
3. 완성된 get 메소드는 아래와 유사할 것입니다.
+
[source, java]
----
public Object get(int index) {
    return this.elements[index];
}
----

==== remove 메소드 구현

remove 메소드는 정수형 index 파라미터를 가지며, elements 배열에서 해당 파라미터 번째에 해당하는 원소를 삭제합니다. 원소의 삭제는 elements 배열에서 해당 원소 뒤의 모든 원소를 한 칸 앞으로 이동하여 원소가 삭제되었음을 표시해야 합니다. 아래 절차에 따릅니다.

1. public 접근 제한자를 가지고, return 타입은 void 이며, 정수형 파라미터 index를 받는 remove 메소드를 작성합니다.
2. elements 배열에서 파라미트로 받은 index 보다 큰 위치의 원소들을 앞으로 한 칸 이동하는 코드를 작성합니다.
3. ArrayList 클래스의 index 필드를 1 감소시키는 코드를 작성합니다.
4. 완성된 remove 메소드는 아래와 유사할 것입니다.
+
[source, java]
----
public void remove(int index) {
    for (int i = index; i < this.index; i++) {
        this.elements[i] = this.elements[i + 1];
    }
    this.index--;
}
----

==== size 메소드 구현

size 메소드는 파라미터가 없으며, ArrayList가 가진 원소수, 즉 index 필드 값을 return 합니다. 아래 절차에 따릅니다.

1. public 접근 제한자를 가지고, 파라미터가 없으며 정수 타입을 반환하는 size 메소드를 작성합니다.
2. index 필드를 return하는 코드를 작성합니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public int size() {
    return this.index;
}
----

==== 배열을 반환하는 getElements 메소드 작성

getElements 메소드는 ArrayList의 모든 요소를 보여주기 위해 elements 배열을 return 합니다. 아래 절차에 따릅니다.

1. public 접근 제한자를 가지고, Object 배열 타입을 return 하며, 파라미터가 없는 getElements 메소드를 작성합니다.
2. elements 배열을 return 하는 코드를 작성합니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public Object[] getElements() {
    return this.elements;
}
----

==== 응용 프로그램 테스트

여기에서는 작성한 ArrayList 응용 프로그램을 테스트합니다. 아래 절차에 따릅니다.

1. 탐색기에서 Test.java 파일을 열고 코드를 확인합니다. 코드는 아래와 같습니다.
+
[source, java]
----
public class Test {
    public static void main(String[] args) {
        List list = new ArrayList();

        list.add(1);
        list.add("Celine");
        list.add(1.0);

        for (int i = 0; i < list.size(); i++) {
            System.out.println(((ArrayList)list).getElements()[i]);
        }

        list.remove(1);

        for (int i = 0; i < list.size(); i++) {
            System.out.println(((ArrayList)list).getElements()[i]);
        }
    }
}
----
+
2. 터미널을 실행하고, 아래 명령을 실행하여 프로그램을 컴파일 합니다.
+
----
$ javac Test.java
----
+
3. 아래 명령을 실행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
$ java Test
1
Celine
1.0

1
1.0
----

---

link:./23_lab_10-1.adoc[이전: Lab 10-1: 상속을 사용하여 인터페이스 구현] +
link:./25_lab_10-3.adoc[다음: Lab 10-3: ArrayList와 LinkedList의 Iterator 구현]