= Generic 메소드 오버라이딩

* 타입 파라미터 이름은 중요하지 않음
** T와 U는 이름만 다를 뿐 동일한 타입 파라미터로 간주됨
* Generic 클래스 상속 시 구체화 가능
** 자식 클래스에서 부모의 제네릭 타입을 고정하거나 유지 가능
* 와일드카드 사용 가능
** List<?>와 같은 형태로도 오버라이딩 가능
* 다형성(Polymorphism) 유지
** 부모 타입 참조 변수로 자식 클래스의 오버라이딩 메서드 호출 가능

---

Generic 메서드 오버라이딩은 슈퍼 클래스에 정의된 Generic 메서드를 버스스 클래스에서 재정의(Override)하는 것을 의미합니다. 기본적으로 오버라이딩은 슈퍼 클래스의 메서드와 동일한 시그니처(메서드 이름, 파라미터 목록, 반환 타입)를 유지해야 합니다. Generic 메서드의 경우에도 이 원칙이 동일하게 적용되지만, 여기에 타입 파라미터(Type Parameter)라는 개념이 추가되어 조금 더 유연하면서도 까다로울 수 있습니다.

[source, java]
----
class Parent {
    public <T> void display(T data) {  // Generic 메서드
        System.out.println("Parent: " + data);
    }
}

class Child extends Parent {
    @Override
    public <T> void display(T data) {  // Generic 메서드 오버라이딩
        System.out.println("Child: " + data);
    }
}

public class Main {
    public static void main(String[] args) {
        Parent p = new Parent();
        Child c = new Child();
        Parent pc = new Child();

        p.display("Hello");   // 출력: Parent: Hello
        c.display(123);       // 출력: Child: 123
        pc.display(45.67);    // 출력: Child: 45.67
    }
}
----

== Generic 메소드 타입 파라미터와 메소드 시그너처

Generic 메소드의 타입 파라미터는 메소드 시그너처에 영향을 주지 않습니다. 아래 코드에서 Parent 클래스와 Child 클래스는 상속 관계에 있고, display 메소드의 타입 파라미터가 다르지만 같은 시그너처이므로 메소드 오버라이딩으로 처리됩니다.

[source, java]
----
class Parent {
    public <T> void print(T data) {
        System.out.println("Parent: " + data);
    }
}

class Child extends Parent {
    @Override
    public <U> void print(U data) {  
        System.out.println("Child: " + data);
    }
}
----

== 슈퍼 클래스만 Generic 클래스일 경우

아래 코드에서 Parent<T> 클래스는 Generic 클래스이고, 서브 클래스인 Child 클래스에서 T 타입이 String으로 고정됩니다. 이런 경우 오버라이딩시 타입이 구체화되며, Generic을 사용할 필요 없이 명확한 타입으로 정의 가능합니다.

[source, java]
----
class Parent<T> {
    public void show(T data) {  // 제네릭 클래스의 메서드
        System.out.println("Parent: " + data);
    }
}

class Child extends Parent<String> {  // String으로 타입 고정
    @Override
    public void show(String data) {    // String 타입으로 오버라이딩
        System.out.println("Child: " + data.toUpperCase());
    }
}

public class Main {
    public static void main(String[] args) {
        Parent<String> p = new Parent<>();
        Child c = new Child();

        p.show("parent");    // 출력: Parent: parent
        c.show("child");     // 출력: Child: CHILD
    }
}
----

== 슈퍼 클래스와 서버 클래스 모두 Generic 클래스인 경우

아래 코드와 같이 슈퍼 클래스와 서브 클래스 모두 Generic인 경우 같은 타입 파라미터 T를 공유하며 메소드 오버라이딩 할 수 있습니다.

[source, java]
----
class Parent<T> {
    public void display(T data) {
        System.out.println("Parent: " + data);
    }
}

class Child<T> extends Parent<T> {
    @Override
    public void display(T data) {  // 부모의 T 그대로 사용
        System.out.println("Child: " + data);
    }
}

public class Main {
    public static void main(String[] args) {
        Child<Integer> child = new Child<>();
        child.display(100);  // 출력: Child: 100
    }
}
----

== 와일드카드 오버라이딩

와일드카드는 오버라이딩에 영향을 주지 않습니다.

---

link:./29_generic_class_inheritance.adoc[이전: Generic 클래스 상속]