= 객체 생성

* 1단계: 메모리 할당
** new 키워드를 사용하여 Heap 영역에 메모리 할당
* 2단계: 생성자를 사용하여 객체 초기화
** 클래스 이름과 괄호를 사용

[source, java]
----
Date now = new Date();
----

---

Java에서 객체를 생성할 때는 다음의 두 단계를 따릅니다.

1.	new 키워드를 사용하여 객체 생성에 요구되는 메모리를 할당합니다.
2.	생성자를 사용하여 할당된 메모리 공간에서 객체를 초기화 합니다.

생성은 두 단계로 이루어지지만 실제 하나의 식에서 두 단계를 모두 실행합니다. 위 코드처럼 Date가 클래스 이름인 경우 객체의 이름과 같은 메소드를 호출하여 메모리를 할당하고 메모리 공간에서 객체를 초기화 합니다.

[source, java]
----
Date now = new Date();
----

== 1단계: 메모리 할당
객체 생성의 첫 번째 단계는 객체를 위한 메모리를 할당하는 것입니다. 모든 객체는 `new` 연산자를 사용하여 생성됩니다. 이 규칙에 예외는 없습니다. `String` 이나 Wrapper 클래스에서와 같이 명시적으로 new 연산자를 호출하지 않더라도 컴파일러가 `new` 연산자를 호출합니다.

배열의 경우 아래와 같이 선언되고 초기화 되도록 코드가 작성되면,

[source, java]
----
int[] array = {1, 2, 3, 4};
----

컴파일러는 실제로 아래와 같이 수행합니다.

[source, java]
----
int[] array = new int[4] {1, 2, 3, 4};
----

== 2단계: 생성자를 사용하여 객체 초기화

객체 생성의 두 번째 단계는 생성자를 호출하는 것입니다. 생성자는 new 연산자로 호출된 메모리 공간을 객체로 채웁니다. 

`new` 연산자의 유일한 목적은 초기화 되지 않은 원시 메모리(raw memory)를 획득하는 것이며, 인스턴스 생성자의 목적은 메모리를 초기화하고 사용할 수 있는 객체로 변환하는 것입니다. `new` 는 초기화와 관련이 없으며 생성자는 어떠한 방식으로든 메모리 획득에 관여하지 않습니다.

`new` 연산자와 생성자는 완벽히 별도의 작업을 수행하지만 프로그래머는 이를 따로 사용할 수 없습니다. 이것은 Java가 메모리를 읽기 전에 항상 유효한 값으로 설정하도록 하는 방법으로, 이런 방식을 확정 할당 (definite assignment)이라고 합니다.

|===
|**참고** C++에서는 메모리를 할당하고 초기화하는 작업을 분리할 수 있습니다. Java에서는 이런 식의 작업 분리가 불가능합니다.
|===

link:./02_constructor.adoc[이전: 생성자] +
link:./04_using_default_constructor.adoc[다음: 기본 생성자 사용]