= 생성자 오버라이딩

* 많은 경우 기본 생성자는 객체 초기화에 적당하지 않음
* 상속되는 기본 생성자 대신 객체만의 기본 생성자를 정의

[source, java]
--
class Date {
    private int year, month, day;
    public Date() {
        year = 1971;
        month = 04;
        day = 28;
    }
}
--

---

컴파일러에서 생성한 기본 생성자가 프로그램에서 요구하는 객체 초기화에 적당하지 않은 경우가 많습니다. 이런 경우 컴파일러가 생성한 기본 생성자 대신 프로그래머가 원하는 방식으로 객체를 초기화하는 객체 고유의 생성자를 작성할 수 있습니다.

== 기본 생성자가 적당하지 않은 경우

컴파일러가 생성한 기본 생성자가 적당하지 않은 여러가지 경우가 있습니다.

* `public` 액세스가 적당하지 않은 경우 +
Factory Method 패턴은 `public` 이 아닌 생성자를 사용합니다. `COS` 이나 `SIN` 같은 절차적 함수들은 `private` 생성자를 사용하는 경우가 많습니다.
`Singleton` 패턴은 일반적으로 `private` 생성자를 사용합니다.
* 기본값으로 초기화하는 것이 적당하지 않은 경우 +
컴파일러가 생성하는 기본 생성자를 생각해봅시다.
+
[source, java]
----
class Date {
    private int year, month, day;
}
----
+
기본 생성자는 `year`, `month`, `day` 필드 모두를 0으로 초기화합니다. 이는 생성되는 객체가 날짜를 표시하는데 적합한 동작이 아닐 수 있습니다.

* 보이지 않는 코드는 관리하기 어렵습니다. +
컴파일러가 생성한 기본 생상자는 볼 수가 없습니다. 이는 문제가 될 수 있습니다. 단계별로 진행하여 코드를 검증하는 디버깅을 할 수 없으며, 필드의 모든 값을 기본 값으로 초기화 하는 것이 프로그래머의 의도였다고 해도 이를 알아채기는 어렵습니다.

== 기본 생성자 작성

컴파일러가 생성하는 기본 생성자가 적당하지 않은 경우, 프로그래머는 기본 생성자를 직접 작성해야 합니다. 프로그래머는 클래스의 필드를 초기화하는 코드만 가진 생성자를 쓸 수 있습니다. 이 경우 생성자에서 초기화하지 않은 모든 필드는 기본 값으로 초기화 됩니다.

[source, java]
----
class Date {
    public int year, month, day;
    public Date() {
        year = 1971;
        month = 04;
        // day는 기본 값으로 초기화됨
    }
}

class Test {
    public static void main(String[] args) {
        Date aDay = new Date();
        System.out.println(aDay.year);		// 1971
        System.out.println(aDay.month);	// 0
        System.out.println(aDay.day);		// 0
    }
}
----

생성자에서 단순이 필드의 초기화를 넘어선 다른 코드를 작성하는 것에는 주의를 기울여야 합니다. 작성한 모든 코드는 오류의 가능성이 있습니다. 생성자에서 오류를 일으키는 코드를 처리하는 유일한 방법은 예외 처리입니다.

초기화에 성공하면, 사용할 수 있는 객체를 얻습니다. 초기화에 실패하면 객체를 사용할 수 없습니다.

link:./04_using_default_constructor.adoc[이전: 기본 생성자 사용] +
link:./06_constructor_overloadng.adoc[다음: 생성자 오버로딩]