= 생성자 오버로딩

* 생성자는 메소드이므로, 오버로딩 할 수 있음
** 같은 범위, 같은 이름, 다른 파라미터를 사용하여 정의
** 객체가 다른 방법으로 초기화 되는 것을 허용
* 주의
** 생성자를 정의하면, 컴파일러는 기본 생성자를 정의하지 않음

[source, java]
----
class Date {
    public Date() { ... }
    public Date(int year, int month, int day){ 
        ...
    }
}
----

---

생성자는 특수한 형태의 메소드입니다. 메소드는 오버로드 할 수 있고, 따라서 생성자 또한 오버로드 할 수 있습니다.

== 오버로딩이란?
오버로딩은 같은 이름의, 같은 가시성 범위를 가진 메소드를 두 개 이상 정의할 수 있는 기술을 말합니다. 아래는 간단한 예제입니다.

[source, java]
----
class Overload {
    public void aMethod() { … }
    public void aMethod(int x) { … }
}

class Test {
    public static void main(String[] args) {
        Overload overload = new Overload();
        overload.aMethod();
        overload.aMethod(28);
    }
}
----

위 코드는 메소드 오버로딩의 간단한 예를 보여줍니다. `Overload` 클래스에 `aMethod` 라는 이름을 가진 두 개의 메소드가 있고 두 메소드 모두 `Test` 클래스의 `main` 메소드에서 호출합니다. 같은 이름의 메소드이지만 다른 개수와 타입을 가진 파라미터를 가지고 다른 방법으로 호출하므로 충돌하지 않습니다.

== 다른 방법으로 객체 초기화

객체는 다양한 방법으로 초기화 될 필요가 있다는 것이 생성자 오버로딩의 목적입니다. 생성자는 특별한 종류의 메소드이며 메소드에서와 같은 방식으로 초기화 될 수 있습니다. 이는 객체를 초기화하는 다양한 방법을 정의할 수 있음을 의미합니다. 다음은 간단한 예제입니다:

[source, java]
----
class Overload {
    public int data;

    public Overload() {}
    public Overload(int data) {
        this.data = data;
    }
}

class Test {
    static void main() {
        Overload o1 = new Overload();
        Overload o2 = new Overload(28);
    }
}
----

객체 `o1` 은 기본 생성자를 사용하지만 파라미터 인자를 가지지 않습니다. 이 경우 객체의 필드는 기본값(int의 경우 0)으로 초기화됩니다. 객체 o2는 하나의 정수를 인자로 생성자를 호출했습니다. `o2` 필드의 객체는 28로 초기화 됩니다.

== 기본 값이 아닌 값으로 필드 초기화

필드를 0이 아닌 값으로 초기화 해야 하는 수 없이 많은 경우가 있을 것입니다. 이런 경우, 생성자를 정의하고 요구에 맞는 만큼의 파라미터를 지정하여 필드를 초기화 할 수 있습니다.

[source, java]
----
class Date {
    private int year, month, day;
    public Date(int year, int month, int day) {
        year = year;
        month = month;
        day = day;
    }
}
----

== 기본 생성자 오버로드

클래스에 생성자를 정의하면, 컴파일러는 기본 생성자를 생성하지 않습니다.

[source, java]
----
class Date {
    private int year, month, day;
    public Date(int year, int month, int day) { ...  }
}


class Test {
    static void main() {
        Date today = new Date();	// 컴파일 시 오류
    }
}
----

이는 클래스에 파라미터를 가지는 생성자를 정의했다면, 파라미터 없이는 객체를 생성할 수 없다는 것을 의미합니다. 파라미터를 가지는 생성자와 기본 생성자를 모두 정의해야 한다면 명시적으로 둘 모두를 선언해야 합니다.

[source, java]
----
class Date {
    private int year, month, day;
    public Date() { ... }
    public Date(int year, int month, int day) { ...  }
}

class Test {
    static void main() {
        Date today = new Date();	
    }
}
----

link:./05_default_constructor_overriding.adoc[이전: 기본 생성자 오버로딩] +
link:./07_initiate_data.adoc[다음: 데이터 초기화]