= Lab 9-1: 객체 생성

== 연습 1 생성자 구현

이 연습에서는 `BankAccount` 클래스에 계정 유형을 나타내는 enum을 추가하고, 이전 연습에서 만든 `BankAccount` 클래스를 수정하여 계좌 번호 및 인스턴스 변수를 채우는 메소드를 제거하고 `BacnkAccount` 객체가 생성될 때 사용할 수 있는 생성자로 변경합니다.

기본 생성자를 재정의하여 객체가 생성될 때 계정 번호를 생성하고 `AccountType` 을 `Checking` 으로, 잔액을 0으로, 계좌 주인을 `Unknown` 으로 설정합니다.

그리고 파라미터가 다른 세 생성자를 더 생성합니다.

* 첫 번째 생성자는 `AccountType` 을 파라미터로 가집니다. 생성자는 계좌 번호를 생성하고, 잔고를 0으로, 계좌 주인을 `Unknown` 으로 설정하며 계좌 유형을 메소드 인자로 받은 값으로 설정합니다.
* 두 번째 생성자는 `BigDecimal` 과 `String` 을 파라미터로 가집니다. 생성자는 계좌 번호를 생성하고, 계좌 유형을 `Checking` 으로 초기화합니다. 잔고와 계좌 주인은 메소드 인자로 받은 값으로 설정합니다.
* 세 번째 생성자는 `AccountType` 과 `BigDecimal`, `String을` 파라미터로 가집니다. 생성자는 계좌 번호를 생성하고, 계좌 유형과 잔고 및 계좌 주인을 메소드 인자로 받은 값으로 설정합니다.

== AccountType enum 추가

1.	Visual Studio Code를 실행합니다.
2.	파일 메뉴에서 폴더 열기를 클릭하고 c:\Labs\Lab9-1\Starter 폴더를 엽니다.
3.	작성자 신뢰 경고 창에서, 예, 작성자를 신뢰합니다 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 BankAccount.java 파일을 엽니다.
5.	Visual Studio 탐색기에서 새 파일 아이콘을 클릭하고 파일 이름을 AccountType.java로 지정합니다.
6.	AccountType.java 파일을 열고, `AccountType` enum을 추가합니다. `AccountType` enum은 `Checking` 과 `Saving`, `Deposit` 세 열거 상수를 가집니다.
7.	완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
enum AccountType {
    Checking,
    Deposit,
    Saving
}
----

== 기본 생성자 생성

1.	BankAccount.java 파일을 엽니다.
2.	BankAccount 클래스의 To-do: Add AccountType variable here 구역에 AccountType 변수 accountType을 private으로 선언합니다.
3.	`setData` 메소드를 삭제합니다.
4.	기본 생성자를 생성합니다.
A.	생성자 이름을 `BankAccount` 로 지정합니다.
B.	`public` 으로 지정합니다.
C.	파라미터가 없습니다.
D.	return type이 없습니다. (void가 아닙니다)
E.	생성자의 코드에서, 정적 메소드 `nextNumber` 를 호출하여 return 값을 `accountNumber` 필드에 할당합니다.
F.	`ownerName` 필드를 `Unknown` 으로, `accountType` 을 `Checking` 으로, `balance` 를 0으로 초기화합니다. +
완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public BankAccount() {
    this.accountNumber = nextNumber();
    this.accountType = AccountType.Checking;
    this.balance = new BigDecimal("0");
}
----
+
5.	`getBalance` 메소드 아래에 `accountType` 을 return하는 public 메소드 `getAccountType` 를 작성합니다.

== 세 오버로드 된 생성자 생성

1.	`accountType` 이라는 이름의 `AccountType` 파라미터를 가지는 생성자를 추가합니다. 
A.	`accountNumber` 를 같은 방법으로 생성하여 할당합니다.
B.	`ownerName` 필드에 `Unknown` 을 할당합니다.
C.	`accountType` 필드에 파라미터 인자로 전달받은 `accountType` 을 할당합니다.
D.	`balance` 에 0을 할당합니다.
2.	`String` 타입 `ownerName` 와 `BigDecimal` 타입 `balance` 파라미터를 가지는 생성자를 추가합니다.
A.	`accountNumber` 를 같은 방법으로 생성하여 할당합니다.
B.	`ownerName` 필드에 `ownerName` 인자를 할당합니다.
C.	`accountType` 필드를 `Checking` 으로 지정합니다.
D.	`balance` 필드에 파라미터 인자로 받은 `balance` 를 할당합니다.
3.	`String` 타입 `ownerName`, `BigDecimal` 타입 `balance`, `AccountType` 타입 `accountType` 을 파라미터로 가지는 생성자를 추가합니다.
A.	`accountNumber` 를 같은 방법으로 생성하여 할당합니다.
B.	`ownerName` 필드에 `ownerName` 인자를 할당합니다.
C.	`accountType` 필드에 `accountType` 인자를 할당합니다.
D.	`balance` 필드에 `balance` 인자를 할당합니다.
4.	완성돤 코드는 아래와 유사할 것입니다
+
[source, java]
----
public BankAccount(AccountType accountType) {
    this.accountNumber = nextNumber();
    this.ownerName = "Unknown";
    this.accountType = accountType;
    this.balance = new BigDecimal("0");
}

public BankAccount(String ownerName, BigDecimal balance) {
    this.accountNumber = nextNumber();
    this.ownerName = ownerName;
    this.accountType = AccountType.Checking;
    this.balance = balance;
}

public BankAccount(String ownerName, AccountType accountType, BigDecimal balance) {
    this.accountNumber = nextNumber();
    this.ownerName = ownerName;
    this.accountType = accountType;
    this.balance = balance;
}
----

== 생성자 테스트

1.	`CreateAccount` 클래스의 `main` 메소드에서, `BankAccount` 타입 변수 `account1`, `account2`, `account3`, `account4를` 선언합니다.
2.	`account1` 변수를 기본 생성자를 사용하여 생성합니다.
3.	`account2` 변수를 `AccountType` 인자 하나만을 사용하여 생성합니다. `AccountType` 은 `AccountType.Deposit`으로 설정합니다.
4.	`account3` 변수를 `String` 과 `BigDecimal`, 두 인자를 사용하여 생성합니다. `String` 은 "James", `BigDecimal` 은 100으로 설정합니다.
5.	`account4` 변수를 String, `AccountType`, `BigDecimal` 세 인자를 사용하여 생성합니다. `String` 은 "Jason", `AccountType` 은 `AccountType.Saving`, `BigDecimal` 은 500으로 지정합니다.
6.	`CreateAccount` 클래스의 `printBankAccount` 메소드를 사용하여 네 계좌를 출력합니다. 완성된 코드는 아래와 유사할 것입니다:
+
[source, java]
----
public static void main(String[] args) {
    BankAccount account1, account2, account3, account4;

    account1 = new BankAccount();
    account2 = new BankAccount(AccountType.Deposit);
    account3 = new BankAccount("James", new BigDecimal("100"));
    account4 = new BankAccount("Jason", AccountType.Saving, new BigDecimal("500"));

    printBankAccount(account1);
    printBankAccount(account2);
    printBankAccount(account3);
    printBankAccount(account4);
}
----
+
7.	터미널을 열고 아래 명령을 실행하여 프로그램을 컴파일 합니다. 오류가 있으면 수정합니다.
+
----
> javac BankAccount.java
----
+
8.	아래 명령을 수행하여 프로그램을 실행하고 결과를 확인합니다.
+
----
> java CreateAccount
Account Number: 0
Owner Name: Unknown
Account Type: Checking
Balance: 0

Account Number: 1
Owner Name: Unknown
Account Type: Deposit
Balance: 0

Account Number: 2
Owner Name: James
Account Type: Checking
Balance: 100

Account Number: 3
Owner Name: Jason
Account Type: Saving
Balance: 500
----

link:./11_static_constructor.adoc[이전: static 생성자] +
link:./13_object_and_memory.adoc[다음: 객체와 메모리]