=    Generic 타입 제약

* Generic 타입은 타입 변환 될 수 없으며, instanceof 연산자를 사용할 수 없음
** 타입 파라미터는 모두 컴파일시 Object로 치환됨
** 컴파일러에서 타입 변환은 참조 타입의 경우 상속 관계만 확인
** 타입 파라미터가 Object 타입으로 치환되어 instanceof로 구분이 어려움
* Generic 타입의 배열은 생성할 수 없음
** Java의 배열은 공변적이지만 Generic 타입은 불공변적
** Java의 배열은 타입 안전을 보장할 수 없음
* Exception 타입의 서브 타입이 될 수 없음
** Generic 클래스는 Throwable 클래스를 직접적 또는 간접적으로 확장할 수 없음

---

Generic 타입은 클래스 내에서 일반적인 형태를 가지게 되고, 컴파일시 Object 또는 선언된 타입으로 지원되는 형식이어서 일반적인 타입에 비해 여러 제약을 가집니다. 

== 타입 변환 불가, instanceof 연산자 사용 불가

Java 컴파일러는 지네릭 코드의 모든 타입 파라미터를 지우고 치환하기 때문에 런타임에 지니렉 타입에 어떤 파라니터가 사용되었는지 알 수 없습니다. 런타임에는 타입 파라미터를 추적할 수 없으므로, Generic 타입의 차이를 알 수 없어 타입 변환할 수 없으며, instanceof 연산자를 사용할 수 없습니다.

== Generic 타입의 배열은 생성할 수 없음

* 배열의 경우 `A \<: B` (A가 B의 서브 타입)일 때 `A[] \<: B[]` 가 됩니다.(공변적)
* Generic 타입의 경우 `A \<: B` 이더라도 `List\<A\> \<: List\<B\>` 가 성립하지 않습니다.(불공변적)

[source, java]
----
Object[] array = new String[5];
Object[0] = 1
----

위 코드에서 array는 Object 타입 배열이므로, array 요소에 1 을 할당해도 컴파일 시에는 오류가 발생하지 않으나, 런타임에 array는 String 타입 배열이 되어 오류가 발생합니다.

[source, java]
----
ArrayList<Object> list = new ArrayList<String>();
----

Generic은 뷸공변하기 때문에 위 코드는 컴파일 오류가 발생합니다. 

배열은 런타임에 실체화되고, Generic은 런타임에 소거되므로, 다르게 동작합니다.

[source, java]
----
// 실제로 작성된 코드
ArrayList<String> stringList = new ArrayList<String>();
ArrayList<Integer> integerList = new ArrayList<Integer>();
----

[source, java]
----
// 런타임에 변환되는 코드
ArrayList stringList = new ArrayList();
ArrayList integerList = new ArrayList();
----

Java에서 Generic 배열이 가능하다면 아래와 같은 문제가 발생할 수 있습니다.

[source, java]
----
// 실제로는 컴파일 오류가 발생함
ArrayList<String>[] stringLists = new ArrayList<String>[1]; // 런타임시에는 제네릭
ArrayList<Integer> intList = Arrays.asList(1); // 타입소거로 인해 런타임시 ArrayList가 됨 
Object[] objects = stringLists; // 배열은 공변성, Object[]는 ArrayList[]가 될 수 있음. 
objects[0] = intList; // intList또한 ArrayList이므로 배열의 요소가 될 수 있음
String s = stringLists[0].get(0) // String 타입을 가져야 하지만 Integer이므로 예외 발생
----

Java에서 Generic 배열을 생성하려면 와일드 카드 타입을 사용할 수 있습니다.

[source, java]
----
List<?> lists = new List<?>[2];
lists[0] = Arrays.asList(1);
lists[1] = Arrays.asList("A");

for (List<?> list : lists) {
    System.out.println(list);
}
----

== Exception 타입의 서브 타입이 될 수 없음

Generic 클래스는 Throwable 타입을 직접 또는 간접적으로 확장할 수 없습니다.

[source, java]
----
// 직접적으로 Exception 클래스 확장
class MathException<T> extends Exception { /* ... */ } // 컴파일시 오류 
// Throwable 직접적으로 확장
class QueueFullException<T> extends Throwable { /* ... */ } // 컴파일시 오류
----

link:./24_type_parameter_limitation.adoc[이전: 타입 파라미터 제약] +
link:./26_method_overloading_limitations.adoc[다음: 메소드 오버로딩 제약]

