= Lab 11-1 Generics를 이용한 응용 프로그램 작성

== 연습 1 일반 클래스를 Generic 클래스로 변경

이 연습에서는 Generics를 이용해 클래스를 선언하고, 실제 코드에서 사용하는 것을 연습합니다. 아래 절차에 따릅니다.

=== 데이터를 저장할 수 있는 Box 클래스 생성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio 탐색기에서 GenericBoxExample.java 파일을 엽니다.
5. `Box` 클래스를 확인합니다.
6. 아래 명령을 수행하여 GenericBoxExample.java 파일을 컴파일합니다.
+
----
$ javac GenericBoxExample.java
----
+
7. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java GenericBoxExample.java
box has 1
----

== 정수 Box 클래스를 GenerixBox 클래스로 변경
1. Box 클래스의 이름 뒤에 T 형식의 타입 파라미터를 추가합니다.
2. Box 클래스의 Integer를 모두 T 형식으로 변경합니다.
3. 완성된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public class Box<T> {
    String name;
    T value;

    Box(String name) {
        this.name = name;
    }

    public String getName() {
       return this.name;
    }
    public void setValue(T value) {
        this.value = value;
    }

     public T getValue() {
        return this.value;
    }
}
----
+
4. GenericBoxExample 클래스의 run 메소드에서, Box 클래스를 생성하는 코드에 Generic 파라미터를 적용합니다.
+
[source, java]
----
Box<Integer> box1 = new Box<Integer>("box 1");
----
+
5. 아래 명령을 수행하여 GenericBoxExample.java 파일을 컴파일합니다.
+
[source, java]
----
$ java GenrericBoxExample.java
----
+
6. 아래 명령을 수행하여 프로그램을 실행합니다.
+
[source, java]
----
$ java GenericBoxExample
box 1 has 1
----

== 연습 2 Generic 클래스 생성

이 연습에서는 Generics 클래스를 이용해 클래스를 선언하고 실제 코드에 적용합니다.

=== 데이터를 저장하는 Box 클래스 작성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio 탐색기에서 MultipleTypeParametersExample.java 파일을 엽니다.
5. Box 클래스를 확인합니다.
6. 아래 명령을 수행하여 MultipleTypeParametersExample.java 파일을 컴파일합니다.
+
----
$ MultipleTypeParametersExample.java
----
+
7. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ javac MultipleTypeParametersExample
box1 has 1
----

=== 단일 타입 파라미터를 두 개로 변경

1. Box 클래스의 타입 파라미터 <T>를 타입 파라미터 2개의 <T, U>로 변경하고, name의 타입을 타입 파라미터 U로 변경합니다.
2. 수정된 Box 클래스는 아래와 유사할 것입니다.
+
[source, java]
----
public class Box<T, U> {
    U name;
    T value;

    Box(U name) {
        this.name = name;
    }

    public U getName() {
        return this.name;
    }
    public void setValue(T value) {
        this.value = value;
    }

    public T getValue() {
       return this.value;
    }
}
----
3. MultipleTypeParametersExample 클래스의 run 메소드에서, Box 클래스 생성 타입 파라미터를 <Integer, String>으로 변경합니다.
+
[source, java]
----
Box<Integer, String> box1 = new Box<>("box1");
----
+
4. 아래 명령을 수행하여 MultipleTypeParametersExample.java 파일을 컴파일합니다.
+
[source, java]
----
$ javac MultipleTypeParametersExample.java
----
+
5. 아래 명령을 수행하여 MultipleTypeParametersExample 프로그램을 실행합니다.
+
----
$ java MultipleTypeParametersExample
box has 1;
----
+
6. Box 클래스의 run 메소드에서, Box 클래스의 U 타입 파라미터를 Interger로 변경하고, 생성자 파라미터를 1로 변경합니다.
+
----
Box<Integer, Integer> box 1 = new Box<>(1);
----
+
7. 아래 명령을 수행하여 MultipleTypeParametersExample.java 파일을 컴파일합니다.
+
----
$ javac MultipleTypeParametersExample.java
----
+
8. 아래 명령을 수행하여 `MultipleTypeParametersExample` 프로그램을 실행합니다.
+
----
$ java MultipleTypeParametersExample
1 has 1;
----

== 연습 3 경계 유형 클래스 생성

이 연습에서는 Generic 클래스를 정의하여 클래스에서 사용될 타입 파라미터를 특정 타입으로 제한합니다.

=== 데이터를 저장하는 Box 클래스 생성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio 탐색기에서 BoundedGenericBoxExample.java 파일을 엽니다.
5. Box 클래스를 확인합니다.
6. 아래 명령을 수행하여 BoundedGenericBoxExample.java 파일을 컴파일 합니다.
+
----
$ javac BoundedGenericBoxExample.java
----
+
7. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java BoundedGenericBoxExample
box1 has 1
box2 has Hello
----

=== 타입 파라미터를 숫자로 제한
1. Box 클래스에서, Box<T>의 타입 파라미터를 숫자로 제한하도록 변경합니다.
2. 수정한 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public class Box<T extends Number> {
    String name;
    T value;

    Box(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setValue(T value) {
        this.value = value;
    }

    public T getValue() {
        return this.value;
    }
}
----
+
3. 작업을 저장합니다.
4. 아래 명령을 수행하여 프로그램을 컴파일하고 오류를 확인합니다.
+
----
$ javac BoundedGenericBoxExample.java
BoundedGenericBoxExample.java:25: error: type argument String is not within bounds of type-variable T
        Box<String> box2 = new Box<String>("box2");
            ^
  where T is a type-variable:
    T extends Number declared in class BoundedGenericBoxExample.Box
BoundedGenericBoxExample.java:25: error: type argument String is not within bounds of type-variable T
        Box<String> box2 = new Box<String>("box2");
                                   ^
  where T is a type-variable:
    T extends Number declared in class BoundedGenericBoxExample.Box
2 errors
----
+
5. BoundedGenericBoxExample 클래스의 run 메소드에서, String 타입 파라미터를 Double로 변경하고, box2 객체의 setValue 메소드의 파라미터를 Double 값으로 변경합니다.
+
[source, java]
----
public void run() {
    Box<Integer> box1 = new Box<Integer>("box1");
    Box<Double> box2 = new Box<Double>("box2");

    box1.setValue(1);
    box2.setValue(3.2);
    System.out.println("Box1 has " + box1.getValue());
    System.out.println("Box2 has " + box2.getValue());
}
----
+
6. 아래 명령을 수행하여 BoundedGenericBoxExample.java 파일을 컴파일합니다.
+
----
> javac BoundedGenericBoxExample.java
----
+
7. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
> java BoundedGenericBoxExample
box1 has 1
box2 has 3.2
----

== 연습 4 와일드카드 사용

이 연습에서는 Generic 메소드에서 와일드카드를 정의하고 사용합니다.

=== 와일드카드 메소드를 포함하는 클래스 생성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio 탐색기에서 WildcardExample.java 파일을 엽니다.
    a. Generic 메소드 showList를 포함하고 있습니다.
    b. showList 메소드는 List<T> 타입의 파라미터를 받아 요소를 출력합니다.
    c. main 메소드는 두 배열을 만드록 이를 List로 반환하여 showList 메소드의 인자로 호출합니다.
5. 아래 명령을 수행하여 WildcardExample.java 파일을 컴파일합니다.
+
----
$ javac WildcardExample.java
----
6. 아래 명령을 수행하여 WildcardExample.java 파일을 컴파일합니다.
+
----
$ java WildcardExample.java
1 2 3
one two three
----

=== 와일드카드 적용

1.	Visual Studio Code 탐색기에서 WildcardExample.java 파일을 엽니다.
2.	WildcardExample 클래스의 showList 메소드에서, 타입 파라미터 T를 와일드 카드로 변경합니다.
3.	수정한 코드는 아래와 유사할 것입니다.
+
[source, java]
----
static <T> void showList(List<?> list) {
    Iterator<?> it = list.iterator();
    ...
    System.out.println("");
}
----
+
4.	아래 명령을 수행하여 WildcardExample.java 파일을 컴파일합니다.
+
----
$ javac WildcardExample.java
----
+
5.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
> java WildcardExample
1 2 3
one two three
----


== 연습 5 수퍼 타입 제한 와일드카드 사용

이 연습에서는 Generic 메소드에서 와일드카드 사용시 적용가능한 타입을 서브타입으로 제한합니다.

=== 와일드카드 메소드를 포함하는 클래스 생성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio Code 탐색기에서 UpperBoundedWildcardExample.java 파일을 엽니다.
5. Box 클래스와 UpperBoundedWildcardExample 클래스의 addItem, showList 메소드를 확인합니다.
+
[source, java]
----
public static <T> void addItem(List<T> list, Box<T> item) {
    list.add(item.getValue());
}

public static <T> void showList(List<T> list) {
    Iterator<T> it = list.iterator();
    while(it.hasNext()) {
        System.out.print(it.next().toString() + ' ');
    }
    System.out.println("");
}
----
+
6. 아래 명령을 수행하여 WildcardExample.java 파일을 컴파일합니다.
+
----
$ javac UpperBoundedWildcardExample.java
----
+
7. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java UpperBoundedWildcardExample
1 2
----

=== 슈퍼 타입 제한 와일드카드 사용
1.	Visual Studio Code 탐색기에서 UpperBoundedWildcardExample.java 파일을 엽니다.
2.	List에 Integer와 Double을 모두 담기 위해서, List의 타입 파라미터를 Number로 변경합니다.
3.	box2 객체를 생성하는 Box 클래스의 Generic 파라미터를 Double로 변경하고 box2의 setValue 메소드를 호출하는 인자를 2.0으로 변경합니다.
4.	수정한 코드는 아래와 유사할 것입니다.
+
[source, java]
----
List<Number> list = new ArrayList<>();
Box<Integer> box1 = new Box<>("box1");
Box<Double> box2 = new Box<>("box2");
box1.setValue(1);
box2.setValue(2.0);
addItem(list, box1);
addItem(list, box2);
showList(list);
----
+
5. 아래 명령을 수행하여 UpperBoundedWildcardExample.java 파일을 컴파일하고 오류를 확인합니다.
+
----
$ javac UpperBoundedWildcardExample.java
UpperBoundedWildcardExample.java:46: error: method addItem in class UpperBoundedWildcardExample cannot be applied to given types;
        addItem(list, box2);
        ^
  required: List<T>,Box<T>
  found:    List<Integer>,Box<Double>
  reason: inference variable T has incompatible equality constraints Double,Integer
  where T is a type-variable:
    T extends Object declared in method <T>addItem(List<T>,Box<T>)
1 error
----
+
6. addItem 메소드에서, Box의 타입 파라미터를 T로 제한하지 않고 T의 하위 타입으로 확장합니다.
+
[source, java]
----
public static <T> void addItem(List<T> list, Box<? extends T> item) {
    list.add(item.getValue());
}
----
+
7.	아래 명령을 수행하여 UpperBoundedWildcardExample.java 파일을 컴파일 합니다.
+
----
$ javac UpperBoundedWildcardExample.java
----
+
8.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java UpperBoundedWildcardExample
1 2.0
----

== 연습 6 서브타입 제한 와일드 카드

이 연습에서는 지네릭 메소드에서 와일드카드 사용시 적용 가능한 타입을 수퍼 타입으로 제한합니다.

=== 와일드 카드 메소드를 포함하는 클래스 생성

1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4. Visual Studio Code 탐색기에서 LowerBoundedWildcardExample.java 파일을 엽니다.
5. 아래 명령을 수행하여 LowerBoundedWildcardExample.java 파일을 컴파일 합니다.
+
[source, java]
----
$ javac LowerBoundedWildcardExample.java
----
+
6. 아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java LowerBoundedWildcardExample
Mammul: dog cat
----

=== 서브타입 제한 와일드카드 적용

1. LowerBoundedWildcardExample 클래스의 addMammul 메소드를 확인합니다.
+
[source, java]
----
public static void addMammal(List<Mammal> list, Mammal mammal) {
    list.add(mammal);
}
----
+
2. addMammul 메소드는 Animal 타입을 리스트에 추가할 수 없습니다. addMammal 메소드가 Animal 타입을 추가할 수 있도록 하기 위해, List의 타입 파라미터에 Mammal의 서브타입 제한 와일드 카드를 적용합니다.
3. 수정한 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public static void addMammal(List<? super Mammal> list, Mammal mammal) {
    list.add(mammal);
}
----
+
4. List<Animal>의 모든 요소를 출력하는 showAnimal 메소드를 작성하고 추가합니다. showAnimal 메소드는 아래와 유사할 것입니다.
+
[source, java]
----
public static void showAnimals(List<Animal> list) {
    System.out.print("Animal: ");
    for(Animal animal : list) {
        System.out.print(animal.getName() + " ");
    }
    System.out.println("");
}
----
+
5.	LowerBoundedWildcardExample 클래스의 main 메소드에서 Animal 타입을 타입 파라미터로 가지는 List animals를 선언하고 초기화합니다.
6.	animals 리스트에 dog. cat을 추가하고 출력합니다.
7.	수정된 main 메소드는 아래와 유사할 것입니다.
+
[source, java]
----
public static void main(String[] args) {
    List<Animal> animals = new ArrayList<>();
    List<Mammal> mammals = new ArrayList<>();

    Dog dog = new Dog();
    Cat cat = new Cat();

    addMammal(mammals, dog);
    addMammal(mammals, cat);
    showMammals(mammals);

    addMammal(animals, dog);
    addMammal(animals, cat);
    showAnimals(animals);
}
----
+
8.	아래 명령을 수행하여 LowerBoundedWildcardExample.java 파일을 컴파일 합니다.
+
----
$ javac LowerBoundedWildcardExample.java
----
+
9.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java LowerBoundedWildcardExample
Mammul: dog cat
Animal: dog cat
----

== 연습 7 Generic 메소드 생성

이 연습에서는 Generics를 이용해 메소드를 선언하고, 사용합니다.

=== 정수 배열을 받아 정렬을 수행하는 클래스 작성
1. Labs 폴더의 Lab11-1/Starter 디렉토리에서 내용을 확인합니다.
2. Labs11-1/Starter 디렉토리를 Visual Studio에서 엽니다.
3. **작성자 신뢰 경고** 창에서, **예, 작성자를 신뢰합니다.** 버튼을 클릭합니다.
4.	Visual Studio Code 탐색기에서 BubbleSortExample.java 파일을 열고 bubbleSort 메소드를 확인합니다.
5.	아래 명령을 수행하여 BubbleSortExample.java를 컴파일하고 오류를 확인합니다.
+
----
$ javac -encoding UTF-8 BubbleSortExample.java
BubbleSortExample.java:30: error: incompatible types: String[] cannot be converted to Integer[]
        bubbleSort(stringList);
                   ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
----

=== bubbleSort 메소드를 지네릭 메소드로 수정
1. bubbleSort 메소드에 타입 파라미터를 추가합니다.
2. 정렬 대상 배열 타입을 타입 파라미터로 변경합니다.
3. 수정된 메소드는 아래와 유사할 것입니다.
+
[source, java]
----
public <T> void bubbleSort(T[] items) {
    for(int i = items.length - 1 ; i > 0 ; i--) {
        for(int j = 0 ; j < i ; j++)  {
            if (items[j] > items[j+1]) {
                T item = items[j];
                items[j] = items[j+1];
                items[j+1] = item;
            }
        }
        System.out.println((items.length - i) + "회 순환 후 : " + Arrays.toString(items));
    }
}
----
+
4.	아래 명령을 수행하여 BubbleSortExample.java를 컴파일하고 오류를 확인합니다.
+
----
$ javac -encoding UTF-8 BubbleSortExample.java
BubbleSortExample.java:20: error: bad operand types for binary operator '>'
                if (items[j] > items[j+1]) {
                             ^
  first type:  T
  second type: T
  where T is a type-variable:
    T extends Object declared in method <T>bubbleSort(T[])
1 error
----
+
5. 정수는 비교 연산자의 사용이 가능하지만, 타입 파라미터로 전달된 T는 비교 연산자의 사용이 가능한 지 알 수 없으므로 컴파일러는 오류를 발생합니다.
6. bubbleSort 메소드의 타입 파라미터를 비교 가능 인터페이스 Comparable의 하위 타입으로 제한합니다.
7. 배열 요소의 값을 비교하는 코드를 compareTo 메소드로 변경합니다.
8. 수정된 코드는 아래와 유사할 것입니다.
+
[source, java]
----
public <T extends Comparable<T>> void bubbleSort(T[] items) {
    for(int i = items.length - 1; i > 0; i--) {
        for(int j = 0 ; j < i ; j++)  {
            if (items[j].compareTo(items[j+1]) > 0) {
                T item = items[j];
                items[j] = items[j+1];
                items[j+1] = item;
            }
        }
        System.out.println((items.length - i) + "회 순환 후 : " + Arrays.toString(items));
    }
}
----
+
9.	아래 명령을 수행하여 BubbleSortExample.java 파일을 컴파일 합니다.
+
----
$ javac -encoding UTF-8 BubbleSortExample.java
----
+
10.	아래 명령을 수행하여 프로그램을 실행합니다.
+
----
$ java BubbleSortExample
정렬 전 : [1, 10, 7, 2, 5, 4, 9, 8, 3, 6]
1회 순환 후 : [1, 7, 2, 5, 4, 9, 8, 3, 6, 10]
2회 순환 후 : [1, 2, 5, 4, 7, 8, 3, 6, 9, 10]
3회 순환 후 : [1, 2, 4, 5, 7, 3, 6, 8, 9, 10]
4회 순환 후 : [1, 2, 4, 5, 3, 6, 7, 8, 9, 10]
5회 순환 후 : [1, 2, 4, 3, 5, 6, 7, 8, 9, 10]
6회 순환 후 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
7회 순환 후 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8회 순환 후 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
9회 순환 후 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
정렬 후 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
정렬 전 : [James, Robert, John, Michael, William, Noah, Liam, Jacob]
1회 순환 후 : [James, John, Michael, Robert, Noah, Liam, Jacob, William]
2회 순환 후 : [James, John, Michael, Noah, Liam, Jacob, Robert, William]
3회 순환 후 : [James, John, Michael, Liam, Jacob, Noah, Robert, William]
4회 순환 후 : [James, John, Liam, Jacob, Michael, Noah, Robert, William]
5회 순환 후 : [James, John, Jacob, Liam, Michael, Noah, Robert, William]
6회 순환 후 : [James, Jacob, John, Liam, Michael, Noah, Robert, William]
7회 순환 후 : [Jacob, James, John, Liam, Michael, Noah, Robert, William]
정렬 후 : [Jacob, James, John, Liam, Michael, Noah, Robert, William]
----

link:./26_method_overloading_limitations.adoc[이전: 메소드 오버로딩 제약] +
link:./28_review.adoc[다음: 검토]