= 배열을 파라미터로 전달

* 배열 파라미터는 배열 변수의 복사본

[source, java]
----
class Example {
    public static void main(String[] args) {
        int[] argument = {1, 2, 3, 4};
        chahgeArrayElement(argument);
        System.out.println(argument[0]);
    }
    static void changeArrayElement(int[] parameter) {
        parameter[0]++;
    }
}
----

---

배열 변수를 메서드에 파라미터 인자로 전달하면 파라미터로 전달된 배열 변수와 원본 배열 변수가 모두 동일한 인스턴스를 참조합니다.


[source, java]
----
class Example {
    public static void main(String[] args) {
        int[] argument = {1, 2, 3, 4};
        changeArrayElement(argument);
        System.out.println(argument[0]);
    }
    static void changeArrayElement(int[] parameter) {
        parameter[0]++;
    }
}
----

위 코드에서 `main`` 메소드의 `argument`` 배열은 int 타입 1, 2, 3, 4로 초기화됩니다. 그런 다음 `changeArrayElement` 메소드에 인자로 전달됩니다. `createChangeElement` 메소드는 `argument` 를 파라미터로 받아들입니다. 즉, `argument` 와 파라미터는 모두 동일한 배열 인스턴스(main 메소드에서 초기화된 argument 배열 인스턴스)를 참조합니다. 그 후 `changeArrayElement` 메소드에서 전달받은 배열의 첫 번째 요소를 1 증가시킵니다. 그리고 `changeArrayElement` 메소드에서 호출한 `main` 메소드로 돌아가고 `argument` 배열 인스턴스의 첫 번째 요소를 표준 출력합니다. 파라미터는 동일한 배열 인스턴스를 참조했으므로 2가 출력됩니다.

배열을 파라미터로 전달해면 배열 인스턴스의 복제본이 생성되지 않기 때문에 배열을 파라미터로 전달하는 것은 매우 빠릅니다. 메소드가 배열 인스턴스에 대한 쓰기를 허용하는 것이 목적인 경우 이 동작(shadow copy)은 적절합니다.

배열의 `clone` 메소드는 배열의 복제본 인스턴스를 생성합니다. 만약 메소드로 배열 인스턴스가 복사된 새 배열을 만들어 전달하고 싶다면 아래와 같이 할 수 있습니다.

[source, java]
----
public static void main(String[] args) {
    int[] argument = {1, 2, 3, 4};
    changeArrayElement(argument);
    System.out.println(argument[0]);
}
----

link:./19_return_array.adpc[이전: 메소드에서 배열 return] +
link:./21_command_argument.adoc[다음: 명령줄 인자]