= 파라미터화에 의한 추상화(Abstraction by Parameterization)

* 데이터를 파라미터로 대체하여 데이터의 ID에서 Abstraction
* 형식 파라미터(formal parameter)를 사용하여 계산을 Abstraction
* 프로그램에서 일반성을 달성하는 중요한 수단
* 절차를 일반화하고 더 유용하게 만듦

---

파라미터의 도입으로 파라미터에 의한 Abstraction을 통해 모든 연산의 Abstraction인 단일 프로그램으로 무한한 계산 집합을 나타낼 수 있습니다. 아래 식은 어떤 정수 변수에 저장된 값을 제곱하는 계산 집합을 설명합니다.

----
x * x + y * y
----

이를 람다 표현식(Lambda expression)으로 표시하면 다음과 같습니다.

----
λ x, y: int.(x * x + y * y)
----

여기에서는 변수가 선언됩니다. 이 정수 변수는 임시로 x라고 하고 여기에 임시로 y라고 하는 다른 정수 변수에 저장된 값의 제곱을 더합니다. 이런 람다 식에서 x와 y를 형식 파라미터로, x * x + y * y를 식의 본문으로 참조합니다. 형식 파라미터를 인수에 바인딩한 다음 본문을 평가하여 계산을 호출합니다. 예를 들어, 아래 식은

----
λ x, y: int.(x * x + y * y) (w, z)
----

다음 식과 동일합니다.

----
w * w = z * z
----

더 친숙한 프로그래밍 언어 표기법으로 람다식을 아래와 같이 나타낼 수 있습니다.

----
int squares(int x, y) {
    return x * x + y * y;
}
----

형식 파라미터와 실제 인자의 바인딩 및 프로세서 호출에 의해 아래와 같이 호출되고 계산됩니다.

----
u = squares(w, z);
----

프로그래머는 파라미터화에 의한 Abstraction을 사용하고 있다는 사실을 인지하지 못하고 Abstraction을 사용하곤 합니다. 예를 들어 정수 배열을 정렬하는 프로시저가 필요하다고 할 때, 정렬해야 할 배열은 다양합니다. 이런 경우 절차를 일반화하고 더 유용하게 만들기 위해 파라미터화에 의한 Abstraction을 사용합니다.

파라미터화에 의한 Abstraction은 프로그램에서 일반성을 달성하기 위한 중요한 수단입니다. 모든 정수 배열을 정렬할 수 있는 루틴은 특정 배열 하나만을 정렬할 수 있는 배열보다 유용합니다. 추가 Abstraction을 통해 더 많은 일반성을 얻을 수 있습니다. 정수 배열뿐만 아니라 실수 배열을 정렬하는 Abstraction을 정의하거나 배열과 유사한 구조에서 작동하는 Abstraction을 정의할 수 있습니다.

파라미터화에 의한 Abstraction은 매우 강력한 매커니즘입니다. 거의 무한한 계산을 상대적으로 간단하게 설명할 수 있게 해줄 뿐 아니라 프로그래밍 언어를 사용하여 쉽고 효율적으로 구현할 수 있습니다.

link:./03_introduction_abstraction.adoc[이전: 추상화 소개] +
link:./05_abstraction_by_specification.adoc[다음: 명세에 의한 추상화]