= DIP, Dependency Inversion Principle

* 의존성 역전 원칙
* 프로그래머는 추상화에 의존해야 하며, 구체화에 의존하면 안된다
** 상위 모듈은 하위 모듈에 의존해서는 안된다
** Abstraction은 세부 사항에 의존해서는 안되며, 세부 사항이 Abstractopm에 의존해야 한다
* 소프트웨어 모듈을 분리하는 특정 형식을 지칭
* 상위 계층이 하위 계층에 의존하는 전통적인 의존 관계를 반전시킴으로서 상위 계층이 하위 계층의 구현으로부터 독립되게 한다
* “상위와 하위 객체 모두 동일한 Abstraction에 의존해야 한다”는 객체지향 설계의 대원칙 제공

---

A. HIGH LEVEL MODULES SHOULD NOT FOR DEPEND UPON LOW LEVEL MODULES. BOTH SHOULD DEPEND UPON ABSTRACTIONS.
B. ABSTRACTIONS SHOULD NOT DEPEND UPON DETAILS. DETAILS SHOULD DEPEND UPON ABSTRACTIONS.

**Dependency Inversion Principle**, DIP라고 불리는 의존 관계 역전 원칙은 추상화에 의존해야 하며, 세부 사항 적인 것에 의존해서는 안된다는 원칙입니다. 클래스 사이에는 의존 관계가 존재하기 마련입니다. 다만 구체적인 클래스에 의존하지 말고 최대한 추상화한 클래스에 의존하라는 뜻이며, 타입(Java와 같은 객체지향 언어에서 Interface)에 기반한 응용 프로그램을 작성하라는 의미이기도 합니다.

쉽게 설명하자면, 구조적 설계에서 발생하는 하위 레벨 모듈의 변경이 상위 레벨 모듈의 변경을 요구하는 관계를 끊는 의미의 역전을 의미합니다. 실제 사용 관계는 바뀌지 않으며, 추상화를 매개로 메시지를 주고받으면서 관계를 최대한 느슨하게 만들 수 있습니다.

DIP를 이해하기 위해서는 IoC(Inversion of Control)이라는 용어를 이해할 필요가 있습니다. IoC는 GoF Design Pattern의 저자 Ralph F. Johnson의 논문 <Designing Resuable Classes> footnote:[Designing Reusable Classes, Journel of Object-Oriented Programming, 1988] 에서 처음 등장하였는데, **헐리우드 원칙**이라고도 불리는 아래와 같은 간단한 문장으로 설명됩니다.

> Don't call us, we'll call you.



link:./19_lab15-5.adoc[이전: Lab 15-5] +
link:./21_lab15-6.adoc[다음: Lab 15-6]