= String 클래스 메소드, 연산자

* length 메소드
* charAt 메소드
* indexOf 메소드
* split 메소드
* concat 메소드
* trim 메소드
* toUpper와 toLower 메소드

---

`String` 클래스는 문자열을 조작할 수 있는 많은 메소드를 제공합니다.

* length 메소드 +
`length()` 메소드는 String 클래스에 포함된 문자열의 길이를 int 타입으로 return합니다.
[source, java]
----
String title = "Yesterday";
int length = title.length();
System.out.println(length);	// 9 출력 
----
* charAt 메소드 +
`charAt()` 메소드는 해당 문자열의 특성 인덱스에 해당하는 문자를 return합니다. 해당 문자열의 길이보다 큰 인덱스나 음수가 전달되면 `IndexOutOfBoundsException` 예외가 발생합니다.

[source, java]
----
String title = "Yesterday";
for (int i = 0; i < title.length(); i++) {
    System.out.print(title.charAt(i) + " ");
}
----
* indexOf 메소드 +
`indexOf()` 메소드는 해당 문자열에서 특정 문자나 문자열이 처음으로 등장하는 위치의 정수형 인덱스를 return합니다. 만약 문자열에 전달된 문자나 문자열이 포함되어 있지 않으면 -1을 return합니다.

[source, java]
----
String title = "Yesterday";
System.out.println(title.indexOf(“day”));
System.out.println(title.indexOf(“d”));
----

* split 메소드 +
`split()` 메소드는 파라미터 인자로 받은 정규 표현식 또는 특정 문자를 기준으로 문자열을 잘라서 String 배열로 return합니다.

[source, java]
----
String lyrics = "all my troubles seems so far away";
String[] result = lyrics.split(" ");
for(String s: result) {
    System.out.println(s);
};
----

* concat 메소드 +
`concat()` 메소드는 해당 문자열의 뒤에 파라미터 인자로 전달된 문자열을 추가한 새로운 문자열을 return 합니다. 인자로 전달된 문자열의 길이가 0이면 해당 문자열을 그대로 return합니다.

[source, java]
----
String title = "Sweet child";
String result = title.concat(" O' mine");
System.out.println(result);
----

* trim 메소드 +
`trim()` 메소드는 해당 문자열의 앞과 뒤에 포함된 모든 공백 문자를 제거합니다.

[source, java]
----
String word = "   Bang!   ";
String result = word.trim();
System.out.println(result);
----
* toUpperCase와 toLowerCase 메소드 +
`toUpperCase()` 메소드와 `toLowerCase()` 메소드는 해당 문자열의 모든 문자를 대문자로 변환하거나 소문자로 변환합니다.

[source, java]
----
String title = "Top Gun";
String upperCaseTitle = title.toUpperCase();
String lowerCaseTitle = title.toLowerCase();
System.out.println(upperCaseTitle);
System.out.println(lowerCaseTitle);
----

link:./16_string_class[이전: String 클래스] +
link:./18_string_compariaion.adoc[다음: String 값 비교]