= 공통 메소드

* 모든 참조 타입의 공통 메소드
* 모든 클래스의 슈퍼 클래스
** toString 메소드
** equals 메소드
** clone 메소드
** finalize 메소드

---

Object 타입은 Object를 상속하는 모든 객체가 공통적으로 가지는 몇 개의 메소드를 제공합니다.

== 모든 참조 타입 객체를 위한 공용 메소드

Object 타입은 여러 개의 공통 메소드를 제공합니다. 모든 객체는 Object에서 상속되고, 파생된 타입들은 이 메소드를 공통으로 가지고 사용할 수 있습니다. 아래는 Object 클래스에서 파생된, 많이 사용되는 메소드들입니다.
* toString 메소드
* equals 메소드
* clone 메소드
* finalize 메소드

* toString 메소드 +
`toString()` 메소드는 해당 인스턴스에 대한 정보를 문자열로 반환합니다. 문자열은 클래스의 이름과 함께 구분자로 ‘@’가 사용되며, 그 뒤로 16진수 해시코드가 추가됩니다. 16진수 해시코드 값은 인스턴스의 주소를 가리키는 값으로, 인스턴스마다 다릅니다.

[source, java]
----
BankAccount account = new BankAccount();
System.out.println(account);
----

* equals 메소드 +
`equals()` 메소드는 해당 인스턴스와 파라미터 인자로 전달받은 두 객체의 값을 비교하여 그 결과를 반환합니다. 참조 타입 변수의 값은 참조하고 있는 객체의 위치(주소 값)입니다.

[source, java]
----
BankAccount account1 = new BankAccount();
BankAccount account2 = new BankAccount();
System.out.println(account1.equals(account2));
System.out.println(account1.equals(account1));
----

* clone 메소드 +
`clone()` 메소드는 해당 인스턴스를 복제하여, 새로운 인스턴스를 생성해 return합니다. `clone` 메소드는 필드의 값만 복사하는 shadow copy를 수행해 return 하며, deep copy를 위해서는 `clone()` 메소드를 오버라이드 해야 합니다. `clone` 메소드는 데이터의 보호를 이유로 `Cloneable` 인터페이스를 구현한 클래스의 인스턴스만이 사용할 수 있습니다.

* finalize 메소드 +
해당 객체의 사용이 끝난 경우(아무도 참조하지 않는 경우) Garbage Collector가 객체의 리소스를 정리할 것을 표시합니다.

link:./21_object_type.adoc[이전: Object 타입] +
link:./23_java_package.adoc[다음: Java 패키지]