= 슈퍼 클래스 멤버에 액세스

* protected 멤버는 암시적으로 파생된 클래스에 상속됨
* 파생된 클래스의 메소드에서 상속된 protected 멤버에 액세스 할 수 있음

[source, java]
----
class Product {
    ...
    protected String name;
}

class IDCard extends Product {
    ... 
    public String getTitle() {
        return name;
    }
}

class External {
    void access(Product product) {
        product.name;	// 컴파일시 오류
    }
}
----

---

`protected` 접근 제한자는 접근 제한자가 있는 클래스와 접근 제한자가 있는 멤버에 액세스 하려는 클래스간의 관계, 그리고 클래스가 속한 패키지에 따라 다릅니다.

같은 패키지에 있는 클래스이거나 서브 클래스의 멤버는 슈퍼 클래스의 `protected` 멤버에 액세스 할 수 있습니다. 같은 패키지에 있는 클래스 또는 서브 클래스에서 `protected` 키워드는 `public` 키워드처럼 동작합니다. 위 코드에서 `IDCard` 클래스의 `getTitle` 메소드는 `Product` 클래스의 `protected` 멤버에 액세스 할 수 있습니다.

다른 패키지에 있거나 서브 클래스와 슈퍼 클래스 관계로 연관되지 않은 클래스 사이에서는 `protected` 멤버는 `private` 멤버처럼 동작합니다. 위 코드에서 `External` 클래스의 `access` 메소드는 `Product` 클래스의 `protected` 멤버인 `name` 에 액세스 할 수 없습니다.

== protected 멤버 상속

서브 클래스가 `protected` 멤버를 상속하는 경우 해당 멤버는 암시적으로 서브 클래스의 `protected` 멤버이기도 합니다. 계층 구조에 있는 모든 서브 클래스가 `protected` 멤버에 액세스 할 수 있음을 의미합니다. 

[source, java]
----
class SuperClass { 
    protected String name; 
} 

class SubClass extends SuperClass { 

} 

class FurtherSubClass extends SubClass { 
    void success() { 
        System.out.println(name); // Okay 
    } 
}
----

link:./03_class_extension.adoc[이전: 클래스 확장] +
link:./05_invoke_constructorofsuper.adoc[다음: 슈퍼 클래스 생성자 호출]