= 예외를 왜 사용해야 하는가?

* 전통적인 절차적 오류 처리는 사용하기 번거로움
* 오류 처리를 위한 코드에서 오류를 일으킬 수 있음
* 오류가 의미를 포함하지 않음

----
int errorCode = 0;
FileInfo source = new FileInfo(“program.java”);	// 프로그램 로직
if (errorCode == -1) goto Failed;			// 오류 처리
int length = (int)source.length;			// 프로그램 로직
if (errorCode == -2) goto Failed;			// 오류 처리
char[] contents = new char[length];			// 프로그램 로직
if (errorCode == -3) goto Failed;			// 오류 처리
// 성공 …
Failed: …
----

---

모든 프로그램을 오류를 일으킬 수 있습니다. 경험있는 프로그래머는 작성한 코드에서 발생할 수 있는 오류를 예상하고 이를 처리할 수 있는 코드를 작성합니다. 이는 제대로 동작하는 프로그램을 작성하는데 있어 가장 중요한 부분입니다.

예를 들어, 프로그래머는 program.java 파일을 읽어 처리하는 프로그램을 작성하고자 할 때, 프로그래머는 java로 아래와 같은 코드를 작성할 수 있습니다.

[source, java]
----
FileInfo source = new FileInfo(“Program.java”);
int length = (int)source.length;
char[] contents = new char[length];
----

이 프로그램 로직은 많은 오류 가능성을 가지고 있습니다. 이를 처리하기 위해 전통적으로 많이 사용하는 분기(Jump)를 사용해서 오류를 처리하는 코드를 작성할 경우 아래와 같이 할 수 있습니다.

[source, java]
----
int errorCode = 0;
FileInfo source = new FileInfo(“program.java”);	// 프로그램 로직
if (errorCode == -1) goto Failed;			// 오류 처리
int length = (int)source.length;			// 프로그램 로직
if (errorCode == -2) goto Failed;			// 오류 처리
char[] contents = new char[length];			// 프로그램 로직
if (errorCode == -3) goto Failed;			// 오류 처리
// 성공 …
Failed: …
----

하지만 위와 같은 코드는 프로그램이 복잡해지고, 이는 프로그램 논리를 흐리게 할 수 있습니다. java의 경우 이런 식의 혼란을 방지하기 위해 goto문을 제공하지 않습니다.

* **프로그램 로직과 오류를 처리하는 코드가 혼합됩니다.** +
프로그램 로직이 오류 처리 코드와 혼합되면 개념적 완결성을 잃습니다. 이는 프로그램을 읽고 이해하기 어렵게 만듭니다.
* **오류 코드는 의미는 포함하고 있지 않습니다.** +
위의 코드에서 -1은 어떠한 뜻을 포함하고 있지 않습니다. “오류: 파일 없음”등의 오류가 의미하는 바를 알려면 문서를 찾아봐야 합니다. 정수 형식의 오류는 오류의 의미를 설명하지 않습니다.
* **오류 코드들은 비슷하게 보입니다.** +
검사를 위한 코드는 비슷합니다. 모두 if문을 사용하여 오류 코드를 테스트합니다. 중복 코드가 많아 읽기 어렵고 오류를 발생할 수 있습니다.
* **오류 코드는 무시되기 쉽습니다.** +
프로그래머는 함수가 실행 후 반환한 값을 무시하는 경우가 많습니다. 예를 들어, C언어의 printf 함수는 오류가 발생하면 -1을 반환하지만 개발자는 printf의 오류를 거의 신경 쓰지 않습니다.
전통적으로 오류를 처리하는 방식에 대한 대안이 필요합니다. 예외(Exception)는 더 유연하고 오버헤드가 적으며 의미 있는 오류 메시지를 담은 오류를 생성할 수 있습니다.

link:./20_exceptions.adoc[이전: 기본 예외 처리] +
link:./22_exception_object.adoc[다음: 예외 객체]