= 클래스(class)란?

* 철학자에게…
** 사람의 분류(classification)에 따라 정의된 인공물
** 행동(behavior)와 속성(attribute)에 따라 분류(classify)
** 분류한 이름과 설명에 모든 사람이 동의할 수 있음
** 어휘를 만들고, 소통하고, 생각함
* 객체지향 프로그래머에게…
** 일반적인 행위와 속성을 설명하는 이름 붙여진 문(statement)의 구조
** 데이터와 기능을 모두 포함하는 데이터 구조

---

클래스는 사전적으로 공통적인 성질을 가진 종류, 부류라는 뜻을 가지고 있습니다. 클래스는 분류를 표시하는 가장 근본적인 단어 중의 하나이며, 사물을 특정 종류(Class) 또는 부류(Class)로 구분하는 것은 프로그래머뿐만 아니라 문명이 탄생하던 순간부터 사람이 하던 일입니다.

모든 자동차는 공통 조작(방향 전환, 정지, 가속 등)과 공통 속성(바퀴, 엔진, 핸들 등)을 가지고 있습니다. 사람은 자동차라는 단어를 사용하여 이러한 모든 일반적인 속성과 행위를 나타냅니다. 일반적인 행동과 속성을 이름 지어진 개념으로 분류할 수 없다면 자동차라고 말하는 대신 자동차가 의미하는 모든 것을 말해야 합니다. 모든 사람이 단어의 의미에 동의하면, 즉 모두가 같은 의미를 공유하는 언어를 사용하는 한 원활한 의사 소통을 할 수 있습니다. 잘 정의된 분류와 걸맞은 이름을 통해 복잡하지만 명확한 생각을 간결한 형태로 표현할 수 있습니다. 그 후 이름 지어진 개념을 사용하여 더 높은 수준의 개념을 만들고 의사 소통의 표현력을 높일 수 있습니다.

모든 프로그래밍 언어는 공통 데이터와 공통 기능을 정의할 수 있습니다. 특정 데이터 또는 기능이 공통적으로 정의되면 한번 작성된 공통 기능을 가져다 사용할 수 있어 중복을 방지할 수 있습니다. 여러 군데 작성된 코드는 유지 관리가 어렵습니다. 객체지향 언어는 구조와 행위를 공유할 수 있는 클래스 정의를 가능하게 합니다. 이 패러다임이 제대로 동작한다면 실세계에서 사람들이 생각하고 대화하는 방식과 자연스럽게 맞아 들어가게 됩니다. 

클래스는 실세계에서 손으로 만져볼 수 있는 자동차와 같은 객체 분류에 사용되는 것 외에도 시간이나 만남과 같이 추상적인 개념을 분류하는데도 사용될 수 있습니다. 실세계에서 시간과 같은 추상적인 개념은 경계가 불분명하여 보다 명확하고 좋은 설계가 필요합니다. 클래스의 유일한 요구사항은 사람들이 대화하고 의사를 소통하는데 도움이 되어야 한다는 것입니다.

link:./02_class_and_object.adoc[이전: 클래스(Class)와 객체(Object)] +
link:./04_object.adoc[다음: 객체(Object)란?]