= 추상화(Abstraction)

* 추상화는 불필요한 것을 선택하고 제거하는 것
**  어떤 것이 중요하고 어떤 것이 중요하지 않은지에 대한 판단
**  어떤 것이 중요한지에 대해 초점을 맞추고 판단
**  어떤 것이 신뢰할 수 없고 필요 없는지에 대한 판단
**  캡슐화는 추상화의 강력한 도구

---

추상화(abstraction)는 대상에 대해 맥락에서 필요한 것에 대한 최소한의 형태가 남을 때까지 불필요한 것을 제거하는 전략입니다. 좋은 추상화는 중요하지 않은 세부 사항을 제거하고 중요한 사항들에 집중할 수 있도록 합니다.

추상화는 모든 프로그래밍에서 가장 중요한 소프트웨어 원칙입니다. 잘 설계된 클래스는 사용하기 쉽도록 클래스가 반드시 해야 하는 필수 행위들을 제공하는 최소한의 메소드를 노출합니다. 추상화는 쉽지 않습니다. 좋은 추상화를 위해서는 그 문제와 맥락에 대한 이해, 명확한 생각, 풍부한 경험이 필요합니다.

== 최소한의 종속성

잘 수행된 소프트웨어 추상화는 복잡한 것을 단순하게 만듭니다. 잘된 추상화는 클래스에서 불필요한 것들을 노출하지 않습니다. 필수적이지 않은 것을 숨기면 외부에서 클래스의 불필요한 부분을 보거나 그 상태 또는 행위에 종속되지 않습니다.

최소한의 종속성은 추상화의 중요한 원칙 중의 하나입니다. 소프트웨어 개발에서 코드의 변경은 불가피합니다. 소프트웨어에 대한 완벽한 이해는 사실상 불가능합니다. 문제에 대한 완벽한 이해 없이 내려진 결정은 재 검토 후 변경되는 것이 일반적입니다. 문제에 대한 이해가 깊어질수록 코드 수정은 많아집니다. 이런 변경이 빈번하게 일어나는 소프트웨어 개발에서, 최선의 방법은 변화가 발생했을 때 그 영향을 최소화할 수 있도록 코드를 작성하는 것입니다. 이는 클래스의 특정 행위나 상태에 대한 종속성을 줄일수록 변경에 대한 영향을 최소화할 수 있습니다.

link:./04_object.adoc[이전: 객체(Object)란?] +
link:./06_encapulation.adoc[다음: 캡슐화(encapsulation)]